### PR TITLE
Update site-design-rest-api.md

### PR DESCRIPTION
**Pull request by bcameron1231**
Including two site design endpoints missing from documentation. Endpoints include GetSiteDesignRun and GetSiteDesignStatusAndSchema for managing site designs.

#### Category
- [x] Content fix

#### What's in this Pull Request?
Two endpoints missing from documentation. GetSiteDesignRun and GetSiteDesignStatusAndSchema

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
It's actually slightly more complicated than that. It might be that they are not documented as planned as if they are documented, they are also supported for 3rd party... which is not necessarily the case. Let me loop in internally the feature crew to agree if we document or not there. Will be back later.

**Comment by bcameron1231** [comment]
Thanks for the feedback Vesa

**Comment by VesaJuvonen** [comment]
I get that... reality is that if something is in the PowerShell cmdlet, it does not mean that it's supported to be called outside of it, which does not help with the setup.

**Comment by VesaJuvonen** [comment]
Closing for now as we have not been able to get confirmation on these being supported from the feature crew. No can do.

**Pull request closed without merging**
