### PR TITLE
Fixing multiple documentation issues

### LINKED ISSUE #2401: gulp trust-dev-cert must be run from the project folder, otherwise you get an error
#### Category
- [ ] Question
- [ ] Typo
- [ ] Bug
- [x ] Additional article idea

#### Expected or Desired Behavior

Install and trust certificate

#### Observed Behavior

Error: "No gulpfile found"

#### Steps to Reproduce

Follow setup instructions and install the developer certificate without changing folders (no instructions to change folders in the article).  Going into a newly created project folder where you generated a new project using yo and running gulp trust-dev-cert returns a successful status.

### PR DESCRIPTION
**Pull request by andrewconnell**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #2401, #2433, #3201, #3202, #3203, #3204, #3212, #3215, #3188, #3171

#### What's in this Pull Request?

Multiple documentation fixes, addressing broken links, typos, and additional guidance when setting up a new dev. environment.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[f054b9a](https://github.com/andrewconnell/sp-dev-docs/pull/3227/commits/f054b9a002f7a0d457d7129000506d63769bdd5c)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[f054b9a](https://github.com/andrewconnell/sp-dev-docs/pull/3227/commits/f054b9a002f7a0d457d7129000506d63769bdd5c)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[f054b9a](https://github.com/andrewconnell/sp-dev-docs/pull/3227/commits/f054b9a002f7a0d457d7129000506d63769bdd5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview?branch=pr-en-us-3227) |
[docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint?branch=pr-en-us-3227) |
[docs/solution-guidance/feature-stapling-sharepoint-add-in.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/feature-stapling-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/feature-stapling-sharepoint-add-in?branch=pr-en-us-3227) |
[docs/solution-guidance/mms-manipulation-sharepoint-add-in.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/mms-manipulation-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/mms-manipulation-sharepoint-add-in?branch=pr-en-us-3227) |
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-3227) |
[docs/solution-guidance/security-apponly-azuread.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/security-apponly-azuread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread?branch=pr-en-us-3227) |
[docs/spfx/set-up-your-development-environment.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/spfx/set-up-your-development-environment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment?branch=pr-en-us-3227) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C9%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901091151326439-3227%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=b0Yx%2FWdq8vQW8kdnV9VQRERKr%2FBUF4veyRNyGAN1nUs%3D&st=2019-01-09T11%3A48%3A19Z&se=2019-02-09T11%3A53%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[4a75400](https://github.com/andrewconnell/sp-dev-docs/pull/3227/commits/4a75400eef71a46ff488206149616e608f761e13)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[4a75400](https://github.com/andrewconnell/sp-dev-docs/pull/3227/commits/4a75400eef71a46ff488206149616e608f761e13)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[4a75400](https://github.com/andrewconnell/sp-dev-docs/pull/3227/commits/4a75400eef71a46ff488206149616e608f761e13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview?branch=pr-en-us-3227) |
[docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint?branch=pr-en-us-3227) |
[docs/solution-guidance/feature-stapling-sharepoint-add-in.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/feature-stapling-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/feature-stapling-sharepoint-add-in?branch=pr-en-us-3227) |
[docs/solution-guidance/mms-manipulation-sharepoint-add-in.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/mms-manipulation-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/mms-manipulation-sharepoint-add-in?branch=pr-en-us-3227) |
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-3227) |
[docs/solution-guidance/security-apponly-azuread.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/solution-guidance/security-apponly-azuread.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread?branch=pr-en-us-3227) |
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-3227) |
[docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest?branch=pr-en-us-3227) |
[docs/spfx/set-up-your-development-environment.md](https://github.com/andrewconnell/sp-dev-docs/blob/docs-update/docs/spfx/set-up-your-development-environment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment?branch=pr-en-us-3227) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C9%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901091210545044-3227%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7oM5QZQpfH1sBdCiwnO1t%2FRkhNWL%2B1Dzy3baGs0bZOM%3D&st=2019-01-09T12%3A07%3A50Z&se=2019-02-09T12%3A12%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @andrewconnell, appreciated. Good stuff...

**Pull request merged**
