### PR TITLE
Update security-apponly.md

### PR DESCRIPTION
**Pull request by vman**
Updated doc to clarify that User Profile write operations do work with SharePoint App-Only principal

#### Category
- [x] Content fix
- [ ] New article

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[ccd071a](https://github.com/vman/sp-dev-docs/pull/3198/commits/ccd071a9909c817bb375cb0a4a88140d1268600d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[ccd071a](https://github.com/vman/sp-dev-docs/pull/3198/commits/ccd071a9909c817bb375cb0a4a88140d1268600d)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[ccd071a](https://github.com/vman/sp-dev-docs/pull/3198/commits/ccd071a9909c817bb375cb0a4a88140d1268600d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly.md](https://github.com/vman/sp-dev-docs/blob/patch-2/docs/solution-guidance/security-apponly.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly?branch=pr-en-us-3198) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901031635081828-3198%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=tNaQsRbpq%2BfjB%2BT1nVdobv368TOlUYqepZo3%2FM1Qh9Y%3D&st=2019-01-03T16%3A32%3A05Z&se=2019-02-03T16%3A37%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[a2066ff](https://github.com/vman/sp-dev-docs/pull/3198/commits/a2066ff974ab6f0866a2300a71a8b7d343e2d690)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by VesaJuvonen** [comment]
thx @vman, appreciated. Good edits... did do also a small update on the wording around ACS retirement in this one to combine that small edit with yours... just saving some time.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[a2066ff](https://github.com/vman/sp-dev-docs/pull/3198/commits/a2066ff974ab6f0866a2300a71a8b7d343e2d690)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[a2066ff](https://github.com/vman/sp-dev-docs/pull/3198/commits/a2066ff974ab6f0866a2300a71a8b7d343e2d690)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly.md](https://github.com/vman/sp-dev-docs/blob/patch-2/docs/solution-guidance/security-apponly.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly?branch=pr-en-us-3198) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C3%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901031650575912-3198%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4W2CT2BAhsnRitQIIGsIwoYbMaY78XJlGXQDE%2Fz%2BzCU%3D&st=2019-01-03T16%3A47%3A45Z&se=2019-02-03T16%3A52%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
