### PR TITLE
Edit pass on site design PnP provisioning article.

### PR DESCRIPTION
**Pull request by Lauragra**
| Q                   | A
| ---------------     | ---
| content fix?        | yes
| New article?        | no 
| Related issues?     | fixes #X, partially #Y, mentioned in #Z

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801081913238944-1214%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ftJQM3utqjaSbOa2oKmJV8bfd8x9JF7fjVKp65XVU3k%3D&st=2018-01-08T19%3A09%3A52Z&se=2018-02-08T19%3A14%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801082112451010-1214%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TH9JZwIm9LRV%2BpRlj%2FGy77CaZlu%2BEIQJBP6lOCPhAsQ%3D&st=2018-01-08T21%3A09%3A20Z&se=2018-02-08T21%3A14%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/get-started-create-site-design.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801082115377384-1214%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4geY9VEQpQ%2FDtn2AyJkmiMII%2Bk%2BnNEn%2FtpXG%2FzLb7Ac%3D&st=2018-01-08T21%3A11%3A39Z&se=2018-02-08T21%3A16%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/get-started-create-site-design.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-scoping.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801082118313011-1214%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FrwBMGOsSz3H1MVy6gTYtJWg%2BMYkML2tLWvn0q8KLKs%3D&st=2018-01-08T21%3A15%3A01Z&se=2018-02-08T21%3A20%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/get-started-create-site-design.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-scoping.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801082130076439-1214%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=1307RA%2BEpLtVB3f3JXIwm8FXIFIwVeJbC22SU9PsFkE%3D&st=2018-01-08T21%3A26%3A37Z&se=2018-02-08T21%3A31%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/get-started-create-site-design.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/get-started-create-site-design.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-powershell.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-powershell.md) | :white_check_mark:Succeeded | |
[docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-sitedesign-edit/docs/declarative-customization/site-design-scoping.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801082134113151-1214%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Nva4BWiL1OJZjF4sa%2BK3VL1tGEuq1mr3wsZ8aZdCD1o%3D&st=2018-01-08T21%3A30%3A46Z&se=2018-02-08T21%3A35%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thx Laura, good to get these polished.

**Pull request merged**
