### PR TITLE
Schema namespace incorrect

### PR DESCRIPTION
**Pull request by pgodwin**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

Example has `<webPart xmlns="https://schemas.microsoft.com/WebPart/v3">`, however this fails in with an incorrect namespace error:
```
Web Part Error: Cannot recognize the XML namespace of this Web Part. Correlation ID: 751853a0-d0d4-1000-5e8e-ce46b644d262.
```

Correct value should `<webPart xmlns="http://schemas.microsoft.com/WebPart/v3">`.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[9223110](https://github.com/pgodwin/sp-dev-docs/commits/922311025feed5a07899183b51523f7ddb3fa2bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/pgodwin/sp-dev-docs/blob/patch-1/docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in?branch=pr-en-us-8325) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202207210606504640-8325/BuildReport?accessString=12f8598acb2be4215595be5d1374e54dc15eec6542dfcf068adc047c6a0bb974).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[2982042](https://github.com/pgodwin/sp-dev-docs/commits/298204262b01f6384accf55a0f0cbd710172e86d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/pgodwin/sp-dev-docs/blob/patch-1/docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in?branch=pr-en-us-8325) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202207250532193554-8325/BuildReport?accessString=ee10d74c248cb25e1521f15d3a4e5a2b8fbf7d92703ee75154ed27c6eb2f35c9).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
Bump @pgodwin  ... please address feedback so we can process your PR.

**Comment by pgodwin** [comment]
> When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

Sorry yes this change was pushed in commit 2982042

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
