### PR TITLE
Validation: Removed Absolute Links

### PR DESCRIPTION
**Pull request by dereklh7**
## Category

- [x] Content fix
- [ ] New article

## Related issues

This PR is part of the Validation cleanup efforts.

## What's in this Pull Request?

Removed absolute links, removed disallowed HTML tags, and added missing descriptions.

### CODE REVIEW

**Comment by dereklh7** [comment]
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
Please resolve merge conflicts before we can merge this.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[80621b0](https://github.com/dereklh7/sp-dev-docs/commits/80621b033a366686a0b8633697bb0c5232b2bff6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth?branch=pr-en-us-8161) | [Details](#user-content-321c7e8b0e35b69d5aee1096d297d396-2e228b85)
[docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/add-a-custom-ribbon-to-your-sharepoint-site?branch=pr-en-us-8161) |
[docs/solution-guidance/Connect-SharePoint-app-parts-by-using-SignalR.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Connect-SharePoint-app-parts-by-using-SignalR.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/connect-sharepoint-app-parts-by-using-signalr?branch=pr-en-us-8161) |
[docs/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins?branch=pr-en-us-8161) |
[docs/solution-guidance/custom-actions-sharepoint-add-in.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/custom-actions-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/custom-actions-sharepoint-add-in?branch=pr-en-us-8161) |
[docs/solution-guidance/Customize-your-SharePoint-site-UI-by-using-JavaScript.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Customize-your-SharePoint-site-UI-by-using-JavaScript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/customize-your-sharepoint-site-ui-by-using-javascript?branch=pr-en-us-8161) |
[docs/solution-guidance/Embedding-JavaScript-into-SharePoint.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Embedding-JavaScript-into-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/embedding-javascript-into-sharepoint?branch=pr-en-us-8161) |
[docs/solution-guidance/implement-a-sharepoint-site-classification-solution.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/implement-a-sharepoint-site-classification-solution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/implement-a-sharepoint-site-classification-solution?branch=pr-en-us-8161) |
[docs/solution-guidance/Information-management-sample-app-for-SharePoint.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Information-management-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/information-management-sample-app-for-sharepoint?branch=pr-en-us-8161) |
[docs/solution-guidance/modern-experience-customizations.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/modern-experience-customizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations?branch=pr-en-us-8161) |
[docs/solution-guidance/modern-experience-customizations-customize-sites.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/modern-experience-customizations-customize-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites?branch=pr-en-us-8161) |
[docs/solution-guidance/multigeo-bcsandsecurestore.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/multigeo-bcsandsecurestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-bcsandsecurestore?branch=pr-en-us-8161) |
[docs/solution-guidance/multigeo-managedmetadata.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/multigeo-managedmetadata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-managedmetadata?branch=pr-en-us-8161) |

<a id="321c7e8b0e35b69d5aee1096d297d396-2e228b85"></a>
### [docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md)
 - **Line 82, Column 1**: **[Warning: merge-conflict]** `````File contains merge conflict markers.`````
 - **Line 84, Column 3**: **[Warning: multiple-h1s - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'TokenHelper.GetAuthorizationUrl returns a URL of the form https://contoso.sharepoint.com/_layouts/15/OAuthAuthorize.aspx?IsDlg=1client_id=<Client ID>scope=Web.Manageresponse_type=code, where <Client ID> is the add-in's Client ID. If your add-in is registered through the Seller Dashboard, any Office 365 site can install the add-in. If your add-in is not registered through the Seller Dashboard, you must register your add-in by using appregnew.aspx, and then update Core.DynamicPermissionsWeb\web.config. To learn more, seeRegister SharePoint Add-ins 2013.') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206271444595090-8161/BuildReport?accessString=5bc0886fabdd74be4dc86d7e69aedd46cd2249ed2d7b82c108cca33cd755a911).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[aa186e7](https://github.com/dereklh7/sp-dev-docs/commits/aa186e7034681d191aa9ce6726d9a0c622dd6e0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Add-a-custom-ribbon-to-your-SharePoint-site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/add-a-custom-ribbon-to-your-sharepoint-site?branch=pr-en-us-8161) |
[docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth?branch=pr-en-us-8161) |
[docs/solution-guidance/Connect-SharePoint-app-parts-by-using-SignalR.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Connect-SharePoint-app-parts-by-using-SignalR.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/connect-sharepoint-app-parts-by-using-signalr?branch=pr-en-us-8161) |
[docs/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/cross-domain-images-in-sharepoint-provider-hosted-add-ins?branch=pr-en-us-8161) |
[docs/solution-guidance/custom-actions-sharepoint-add-in.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/custom-actions-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/custom-actions-sharepoint-add-in?branch=pr-en-us-8161) |
[docs/solution-guidance/Customize-your-SharePoint-site-UI-by-using-JavaScript.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Customize-your-SharePoint-site-UI-by-using-JavaScript.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/customize-your-sharepoint-site-ui-by-using-javascript?branch=pr-en-us-8161) |
[docs/solution-guidance/Embedding-JavaScript-into-SharePoint.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Embedding-JavaScript-into-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/embedding-javascript-into-sharepoint?branch=pr-en-us-8161) |
[docs/solution-guidance/implement-a-sharepoint-site-classification-solution.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/implement-a-sharepoint-site-classification-solution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/implement-a-sharepoint-site-classification-solution?branch=pr-en-us-8161) |
[docs/solution-guidance/Information-management-sample-app-for-SharePoint.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/Information-management-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/information-management-sample-app-for-sharepoint?branch=pr-en-us-8161) |
[docs/solution-guidance/modern-experience-customizations.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/modern-experience-customizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations?branch=pr-en-us-8161) |
[docs/solution-guidance/modern-experience-customizations-customize-sites.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/modern-experience-customizations-customize-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites?branch=pr-en-us-8161) |
[docs/solution-guidance/multigeo-bcsandsecurestore.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/multigeo-bcsandsecurestore.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-bcsandsecurestore?branch=pr-en-us-8161) |
[docs/solution-guidance/multigeo-managedmetadata.md](https://github.com/dereklh7/sp-dev-docs/blob/Revert-6-13/docs/solution-guidance/multigeo-managedmetadata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-managedmetadata?branch=pr-en-us-8161) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206271447543876-8161/BuildReport?accessString=e2ae233088505f8af4142a42d33a0bf5352228342bda5255555cf537614d937e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
