### PR TITLE
Validation fixes

### PR DESCRIPTION
**Pull request by chrisms86**
## Category

- [x ] validation fixes

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[bc2080d](https://github.com/chrisms86/sp-dev-docs/commits/bc2080de8df53186343ed75b23585b368f82a919)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenario-guidance/Enterprise-Content-Management.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/scenario-guidance/Enterprise-Content-Management.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/enterprise-content-management?branch=pr-en-us-8033) | [Details](#user-content-3f8d4f56f1655e832a19ff0e78a0a2ec-1168defc)
[docs/scenario-guidance/Application-lifecycle-management.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/scenario-guidance/Application-lifecycle-management.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/application-lifecycle-management?branch=pr-en-us-8033) |

<a id="3f8d4f56f1655e832a19ff0e78a0a2ec-1168defc"></a>
### [docs/scenario-guidance/Enterprise-Content-Management.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/scenario-guidance/Enterprise-Content-Management.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Last modified: March 09, 2015' is duplicated in 'scenario-guidance/Enterprise-Content-Management.md(11,14)', 'schema/_authschemename-element-formsauthcredentials-complextypesps15xsdsearchset2.md(10,14)', 'schema/_authsubmissionmethod-element-formsauthcredentials-complextypesps15xsdsearchset2.md(10,14)', 'schema/_authsubmissionpath-element-formsauthcredentials-complextypesps15xsdsearchset2.md(10,14)', 'schema/_cookies-element-cookieauthdata-complextypesps15xsdsearchset2.md(10,14)'....`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206061723332393-8033/BuildReport?accessString=0115edfe016e837d802c7dc669149c8ea258fd6bda43bcfc85189df45c7eb067).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[8186301](https://github.com/chrisms86/sp-dev-docs/commits/818630175ccbe6a9f2f55b588b94cac98964c8de)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenario-guidance/Enterprise-Content-Management.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/scenario-guidance/Enterprise-Content-Management.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/enterprise-content-management?branch=pr-en-us-8033) | [Details](#user-content-3f8d4f56f1655e832a19ff0e78a0a2ec-4b7fefa0)
[docs/scenario-guidance/Application-lifecycle-management.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/scenario-guidance/Application-lifecycle-management.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/application-lifecycle-management?branch=pr-en-us-8033) |

<a id="3f8d4f56f1655e832a19ff0e78a0a2ec-4b7fefa0"></a>
### [docs/scenario-guidance/Enterprise-Content-Management.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/scenario-guidance/Enterprise-Content-Management.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206061728214637-8033/BuildReport?accessString=8a0974369a9b21b7bb004a9ec09132323a44722e700fd13c9af10d30756de6d6).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by chrisms86** [comment]
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

**Pull request merged**
