### PR TITLE
Added @currentWeb

### PR DESCRIPTION
**Pull request by thechriskent**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Added details about the new `@currentWeb` magic string.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[31eeafc](https://github.com/SharePoint/sp-dev-docs/pull/3221/commits/31eeafce1e12a970cb7a64133e25926fb9fc1220)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[31eeafc](https://github.com/SharePoint/sp-dev-docs/pull/3221/commits/31eeafce1e12a970cb7a64133e25926fb9fc1220)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[31eeafc](https://github.com/SharePoint/sp-dev-docs/pull/3221/commits/31eeafce1e12a970cb7a64133e25926fb9fc1220)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/thechriskent-patch-1/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-3221) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901082004576293-3221%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QJF8haDFatJMgF9PWFeULYe1aVB5ANzh32qHrMrlCGE%3D&st=2019-01-08T20%3A01%3A45Z&se=2019-02-08T20%3A06%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx Chris, appreciated.

**Pull request merged**
