### PR TITLE
Fixed typo from "WebTemplate 1" to "WebTemplate"

### PR DESCRIPTION
**Pull request by vijayysisodia**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

a) Fixed typo from "WebTemplate 1" to "WebTemplate"

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[275103b](https://github.com/vijayysisodia/sp-dev-docs/commits/275103b44882ad6130864bb9c344d9c185bec87b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/customize-default-site-design.md](https://github.com/vijayysisodia/sp-dev-docs/blob/patch-3/docs/declarative-customization/customize-default-site-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design?branch=pr-en-us-7355) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109270405210196-7355%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-28T04%3A06%3A37Z&sr=b&sp=r&sig=eM8bs%2BVtzWDTZ0y8scxZeD7w390al3jTYaxPbZiKFIU%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[0735b05](https://github.com/vijayysisodia/sp-dev-docs/commits/0735b05084cb645b9bcf98f4ab0cd356c371d6fa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e076047d)

<a id="e076047d"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281012204331-7355%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A12%3A49Z&sr=b&sp=r&sig=ZIpoqiaFR0UuHGfxPIhjK1FW77CnAZiaTGK2Jaz%2BtQ8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
update doc frontmatter to reflect update date

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[0735b05](https://github.com/vijayysisodia/sp-dev-docs/commits/0735b05084cb645b9bcf98f4ab0cd356c371d6fa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c400d060)

<a id="c400d060"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281015288509-7355%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A16%3A00Z&sr=b&sp=r&sig=KSZFwqChtvCokhehdlEFzq1%2FBHUHy9CGRi07FiroMj0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
@vijayysisodia Apparently you haven't signed the CLA (see above)... can you verify or sign it using the instructions: https://github.com/SharePoint/sp-dev-docs/pull/7355#issuecomment-929053609

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[d7901a5](https://github.com/vijayysisodia/sp-dev-docs/commits/d7901a5ef1f548314e14ac4705e0940c6806fc3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/customize-default-site-design.md](https://github.com/vijayysisodia/sp-dev-docs/blob/patch-3/docs/declarative-customization/customize-default-site-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/customize-default-site-design?branch=pr-en-us-7355) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281016559321-7355%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A18%3A13Z&sr=b&sp=r&sig=k4TvNKrK6Zw1%2Bc6xmPYLwXG%2B1o3zyhC6ZHkSgzQMg6E%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by vijayysisodia** [comment]
> @vijayysisodia Apparently you haven't signed the CLA (see above)... can you verify or sign it using the instructions: [#7355 (comment)](https://github.com/SharePoint/sp-dev-docs/pull/7355#issuecomment-929053609)

Thanks @andrewconnell for the above alert.  The needful has been done. Wishing you a great day ahead!

**Pull request merged**
