### PR TITLE
Documentation Updates - New Endpoint and Typos

### PR DESCRIPTION
**Pull request by bcameron1231**
Adding the new AddSiteDesignTaskToCurrentWeb endpoint to the documentation. This is an alternative to ApplySiteDesign to support more than  30 actions in a site script.

#### Category
- [x] Content fix
- [ ] New article

#### What's in this Pull Request?
Added the new AddSiteDesignTaskToCurrentWeb endpoint. 
Changed a typo in for id, to siteDesignId
Added a break between sections

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[a012e2e](https://github.com/bcameron1231/sp-dev-docs/pull/3235/commits/a012e2e2f2c73d5485da1c20da29fa443cbdac6d)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[a012e2e](https://github.com/bcameron1231/sp-dev-docs/pull/3235/commits/a012e2e2f2c73d5485da1c20da29fa443cbdac6d)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[a012e2e](https://github.com/bcameron1231/sp-dev-docs/pull/3235/commits/a012e2e2f2c73d5485da1c20da29fa443cbdac6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-rest-api.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-1/docs/declarative-customization/site-design-rest-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-rest-api?branch=pr-en-us-3235) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C10%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901101733378745-3235%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=mRyLbP3nP%2F65jCw2u%2B35OehLyjwngofZ1ZdZyOsygME%3D&st=2019-01-10T17%3A30%3A25Z&se=2019-02-10T17%3A35%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @bcameron1231, appreciated.

**Pull request merged**
