### PR TITLE
Update SPFx training page

### PR DESCRIPTION
**Pull request by andrewconnell**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

- added links to new training modules

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[8a862a2](https://github.com/andrewconnell/sp-dev-docs/pull/3163/commits/8a862a2e76f5cf1e509e0392028a98b4f865a6a1)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[8a862a2](https://github.com/andrewconnell/sp-dev-docs/pull/3163/commits/8a862a2e76f5cf1e509e0392028a98b4f865a6a1)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[8a862a2](https://github.com/andrewconnell/sp-dev-docs/pull/3163/commits/8a862a2e76f5cf1e509e0392028a98b4f865a6a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/training/training.md](https://github.com/andrewconnell/sp-dev-docs/blob/spfx-training-list-update/docs/training/training.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/training/training?branch=pr-en-us-3163) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C21%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812211454095320-3163%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=De9bxUVviMW2c6%2FNXTinGAEQwnI6S0PXwufkG8UqqlY%3D&st=2018-12-21T14%3A50%3A55Z&se=2019-01-21T14%3A55%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx AC, appreciated.

**Pull request merged**
