### PR TITLE
Resolving #5751

### LINKED ISSUE #5751: Update Create a multi-tenant enterprise API secured with Azure AD for AAD Authentication settings
## Category

- [ ] Question
- [ ] Typo
- [ ] Additional article idea
- [x] Update to existing documentation

The documentation for [Create a multi-tenant enterprise API secured with Azure AD](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md) is awesome. No doubt it's helpful. But there have been some UI change in Azure Portal , for e.g  *On the Azure Active Directory Settings blade, choose the Manage Application button* I could not see the settings here  instead I had to go to the **App Registrations** to configure the App ID URL. 
Should this document be improved to update that tiny information to help developers speed up their process to set things up (if they are new and trying to build something) ? 
Happy to help update it as well. 
Thanks,
Rabia

### PR DESCRIPTION
**Pull request by rabwill**
## Category

- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

## Related issues

- fixes #5751 

## What's in this Pull Request?

Content fixes for new Azure portal UI
Images to support the new Azure portal UI

### CODE REVIEW

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Great updates... thanks for the submission!

But... can you please take a look at the screenshots? Quite a few of the screenshots that have been replaced are HUGE with a lot of negative & unnecessary space. Many of them are very wide... for instance, one is 1900px wide. That's just not going to be useful because MSDocs will resize the image and make it so small people won't be able to read the contents.

The goal is for images to be no bigger than 800px wide

**Comment by rabwill** [comment]
Thanks @andrewconnell for reviewing this! I will update this and do a push soon 🙂

**Comment by andrewconnell** [comment]
Hi @rabwill - do you have an estimate on when you think you'll have an op to edit these images so we can push this PR through?

**Comment by rabwill** [comment]
This fell off my radar @andrewconnell , will update the images this week if the UI has not changed !

**Comment by rabwill** [comment]
@andrewconnell is there a way I could serve these pages to see how they look before submitting the PR? I have adjusted the width, would that work?

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
Microsoft employees have access to a preview of the PR's contents... just add `review.` to the prefix of the subdomain. There's a picker where you can change to view the build for the PR.

I'm going to merge this in, but at some point we still need to update these screenshots. Shrinking down to 800px wide is one step, but the point is to ensure people can read them. While an improvement, many of them still need to be addressed so only the important stuff is shown. For example, the first three have a lot of "extra" pixes that could be removed had the browser been resized so that only the important stuff was in focus when the screenshot was taken.

**Comment by rabwill** [comment]
Thanks @andrewconnell makes sense, I guess the trick is to use a regular monitor for these screenshots correct? Will keep this in my backlog to update, may be open an issue later and push these in. Thanks for your time 🎉

**Comment by andrewconnell** [comment]
That's not necessary... just don't go full screen on the browser. Just keep in mind the point of an image is to illustrate something... when there's a lot of unused space in the image, or the image is hard to read, it's not serving the purpose.

**Pull request merged**
