### PR TITLE
Extends the docs on creating modern team sites using the Office365 CLI

### PR DESCRIPTION
**Pull request by VelinGeorgiev**
#### Category
- [ ] Content fix
- [X] New article
- Related issues: fixes #X, partially #Y, mentioned in #1

#### What's in this Pull Request?

Extends SharePoint docs on creating modern team sites using the Office 365 CLI. Text describing how to create modern sites using the Office 365 CLI added after the C# and PowerShell paragraphs.

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/VelinGeorgiev/sp-dev-docs/blob/cli-modern-team-sites/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-1719) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C20%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201804202204491105-1719%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0ElQLlQ%2BdM8x8e8cknB1LPS8F28nq2HkxgRfgQ721DI%3D&st=2018-04-20T22%3A01%3A32Z&se=2018-05-21T22%3A06%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/VelinGeorgiev/sp-dev-docs/blob/cli-modern-team-sites/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-1719) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C10%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201805102255369822-1719%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=q8RLl9ENIYnodIB24%2BQbj0Ho5I%2FA8Cxb3GwFKcbm0rI%3D&st=2018-05-10T22%3A52%3A24Z&se=2018-06-10T22%3A57%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VelinGeorgiev** [comment]
Merge conflict fixed

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/VelinGeorgiev/sp-dev-docs/blob/cli-modern-team-sites/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-1719) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C10%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201805102304520700-1719%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=jQPUkd0CYtnVM2nK%2BqQtwgkXA6YQyF8hCJQbxRaWxXA%3D&st=2018-05-10T23%3A01%3A33Z&se=2018-06-10T23%3A06%3A33Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/VelinGeorgiev/sp-dev-docs/blob/cli-modern-team-sites/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-1719) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201805130807068629-1719%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=x06JuGf9KkigIyCGxO%2BFZtsxg65w4ukjLfMH8sJuHyg%3D&st=2018-05-13T08%3A03%3A50Z&se=2018-06-13T08%3A08%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VelinGeorgiev** [comment]
Ping. This has been added Apr 20. Its only two new paragraphs. It is not a hard read :+1:  :)

**Comment by VelinGeorgiev** [comment]
@spdevdocs  what "Merging is blocked" means, should I take any action? @waldekmastykarz

**Comment by waldekmastykarz** [comment]
I think it means you are not allowed to merge it yourself 🙂

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbe3436](https://github.com/VelinGeorgiev/sp-dev-docs/pull/1719/commits/cbe34366819001eba60ff747adf8e31a3f2b82fc)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by VesaJuvonen** [comment]
Fixed conflicts to get this merged. Should be good now.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbe3436](https://github.com/VelinGeorgiev/sp-dev-docs/pull/1719/commits/cbe34366819001eba60ff747adf8e31a3f2b82fc)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbe3436](https://github.com/VelinGeorgiev/sp-dev-docs/pull/1719/commits/cbe34366819001eba60ff747adf8e31a3f2b82fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/VelinGeorgiev/sp-dev-docs/blob/cli-modern-team-sites/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-1719) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812281558325802-1719%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yGeVm8zSpmHd9CpZ2V4SzO%2B2gCgMpTM0tUTaM1bF4LY%3D&st=2018-12-28T15%3A55%3A18Z&se=2019-01-28T16%3A00%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
