### PR TITLE
Update column formatting dev docs for SPSE 22H2

### PR DESCRIPTION
**Pull request by TroyStarr**
Updating the column formatting developer documentation for the SharePoint Server Subscription Edition Version 22H2 feature update.

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

Updating column formatting developer documentation for the SharePoint Server Subscription Edition Version 22H2 feature update.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a65e4c8](https://github.com/TroyStarr/sp-dev-docs/commits/a65e4c8d9fc58abb46b85e2dfb7016371f2cd03b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/TroyStarr/sp-dev-docs/blob/patch-1/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-8425) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/TroyStarr/sp-dev-docs/blob/patch-1/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8425) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202209082125356240-8425/BuildReport?accessString=6db914d267cdcd7cfce634256ccc8a3e5ad666beef75483a69b59aab6550383b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[5e2ac90](https://github.com/TroyStarr/sp-dev-docs/commits/5e2ac9011ef1f4e6e1e2666c5c49f382a0705f74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/TroyStarr/sp-dev-docs/blob/patch-1/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-8425) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/TroyStarr/sp-dev-docs/blob/patch-1/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8425) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202209082131050923-8425/BuildReport?accessString=d76e8bc83a382c98137be082164a1d7ceac3fb08c38c494ab93349a0ffd1af3d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[9a5141a](https://github.com/TroyStarr/sp-dev-docs/commits/9a5141aab8aaf79ea69f0c4b0d43407bef5f9fc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/TroyStarr/sp-dev-docs/blob/patch-1/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-8425) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/TroyStarr/sp-dev-docs/blob/patch-1/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8425) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202209082131519134-8425/BuildReport?accessString=6538d16f3358c29a5673041b1358dcce5135d4c1c3a8c4afea4866243dbb8ac8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by TroyStarr** [comment]
@VesaJuvonen, FYI that this developer documentation update should be published on September 13, 2022 ("Patch Tuesday").

**Pull request merged**
