### PR TITLE
Update how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md

### PR DESCRIPTION
**Pull request by edixon-github**
Added clarifying details on per-user throttling limits for search query requests.  New product functionality will enforce per-user QPS limits for search.  Limits were only hinted at in the Optimization and Page diagnostics tool doc.

## Category

- [x] Content fix
- [ ] New article

## Related issues
No issues.
Clarifying product functionality that will enforce per-user QPS limits for search.  Limits were only hinted at in the Optimization and Page diagnostics tool doc.

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?
Added clarifying details on per-user throttling limits for search query requests.  New product functionality will enforce per-user QPS limits for search.  Limits were only hinted at in the Optimization and Page diagnostics tool doc.
No related issues or bugs fixed.

### CODE REVIEW

**Comment by Lauragra** [comment]
@andrewconnell , can you help us get this PR merged? Thanks!

**Comment by edixon-github** [comment]
Thanks Laura.  @andrewconnell , new to this process, so please let me know what should be done to complete.

**Comment by andrewconnell** [comment]
@edixon-github said:
> Thanks @Lauragra . @andrewconnell , new to this process, so please let me know what should be done to complete.

Nothing more on your site. I'll review this PR when I review the other open ones later this week... please monitor your notifications in case there's follow-up work from the review. Thanks!

**Review by andrewconnell — APPROVED** [review]

**Comment by edixon-github** [comment]
Thanks for pushing this through @andrewconnell . I see it's been "committed" and I can see it in a "review" state (https://review.learn.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online?branch=main#scenario-specific-limits).  

What's the path and time until it is published on learn.microsoft.com?  (not trying to be pushy, just understand the process)

Thanks.

**Comment by andrewconnell** [comment]
Once content has been merged to the `master` branch, it then needs to be merged to the `live` branch which triggers deployment to production. I'm not clear if that's automated or manual, but I let the person who usually does that process there are updates to push.

As an external, I don't have the permission to do that...

**Comment by edixon-github** [comment]
@andrewconnell , thanks for all your help.  I see it got published last night.  Thanks for helping me with this process and learning about it.

**Pull request merged**
