### PR TITLE
Added tutorial on web part localization

### PR DESCRIPTION
**Pull request by waldekmastykarz**
| Q                   | A
| ---------------     | ---
| content fix?        | no
| New article?        | yes
| Related issues?     | n/a

#### What's in this Pull Request?

Added tutorial on web part localization

### CODE REVIEW

**Comment by davidchesnut** [comment]
@waldekmastykarz images/localization-multilingual-properties.png has a user name in it. Can you recapture the image without a user name? Otherwise we need to use pre-approved names and photos if you must have a user name there. Thanks!

**Comment by davidchesnut** [comment]
@waldekmastykarz nice job on the blur effect on images/localization-english-greeting-dutch-workbench.png! Again we should also blur the user name such as userDisplayName field.

**Comment by waldekmastykarz** [comment]
thank you for your feedback @davidchesnut. For screenshots I'm using a sample site from demos.microsoft.com which is cleared for use (double checked it with @VesaJuvonen).

**Comment by VesaJuvonen** [comment]
thx Waldek - getting now added to TOCs etc.

**Pull request merged**
