### PR TITLE
Corrected "Formatter Tool helper" hyperlink

### LINKED ISSUE #7087: incorrect hyperlink in the tip
The "Formatter Tool helper" hyperlink in the second tip under [creating custom json](https://pnp.github.io/List-Formatting/tools/) is incorrect and is showing page not found error. Please update it from https://pnp.github.io/sp-dev-list-formatting/tools/ to https://pnp.github.io/List-Formatting/tools/

Thanks,
Adi.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f60068c3-4534-a400-350b-fdbcefd684b6
* Version Independent ID: 228accdb-a7de-0671-34ad-60a37866c380
* Content: [Use column formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting#creating-custom-json)
* Content Source: [docs/declarative-customization/column-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/column-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

### PR DESCRIPTION
**Pull request by SmitaNachan**
## Category

- [x] Content fix

## Related issues

- fixes #7087

## What's in this Pull Request?
Corrected "Formatter Tool helper" hyperlink

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[868f5c1](https://github.com/SmitaNachan/sp-dev-docs/commits/868f5c19c33a9aff05a3f09e57e8852dada4d328)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/SmitaNachan/sp-dev-docs/blob/patch-23/docs/declarative-customization/column-formatting.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-7088) | [Details](#user-content-4e9e029b322ad5aa2b8b99ca25b69724-0ab3fd9a)

<a id="4e9e029b322ad5aa2b8b99ca25b69724-0ab3fd9a"></a>
### [docs/declarative-customization/column-formatting.md](https://github.com/SmitaNachan/sp-dev-docs/blob/patch-23/docs/declarative-customization/column-formatting.md)
 - **Line 25, Column 28**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 534, Column 163**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#button-elements' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 1039, Column 159**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#create-a-button-to-launch-a-flow' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106140607192074-7088%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jdhtSenygoy%2FHwiOX7IHM0lj8rhoaZ9XwclT3PNmaR8%3D&st=2021-06-14T06%3A03%3A31Z&se=2021-07-15T06%3A08%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[4a16cff](https://github.com/SmitaNachan/sp-dev-docs/commits/4a16cfff338b628b0072bcaf2685a5fafb725672)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/SmitaNachan/sp-dev-docs/blob/patch-23/docs/declarative-customization/column-formatting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-7088) | [Details](#user-content-4e9e029b322ad5aa2b8b99ca25b69724-53a025cc)

<a id="4e9e029b322ad5aa2b8b99ca25b69724-53a025cc"></a>
### [docs/declarative-customization/column-formatting.md](https://github.com/SmitaNachan/sp-dev-docs/blob/patch-23/docs/declarative-customization/column-formatting.md)
 - **Line 534, Column 163**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'column-formatting'.`````
 - **Line 1039, Column 159**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'column-formatting'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106141041543945-7088%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2PGqFgdoxTiF1tEVe7KU8IU%2FKMT8frOEMbr8%2BFmyYGc%3D&st=2021-06-14T10%3A37%3A59Z&se=2021-07-15T10%3A42%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Thanks for the submission, but it appears the links you edited are now broken. Can you please address the warnings in the build report before we can proceed with this PR?

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a8b97a8](https://github.com/SmitaNachan/sp-dev-docs/commits/a8b97a8dc802a0422e89092b5a1b0c098f39d98d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/SmitaNachan/sp-dev-docs/blob/patch-23/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-7088) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106161518535285-7088%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qU3PQlSih7TX1dIlhiQlf8pZZh%2Bi%2FdLwbbv5jCNiJuk%3D&st=2021-06-16T15%3A15%3A13Z&se=2021-07-17T15%3A20%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
