### PR TITLE
Fixing video link  Debugging SharePoint Framework solutions in Visual Studio Code

### LINKED ISSUE #2248: [LOC] Invalid video in an article
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?view=sp-typescript-latest
2. See the first youtube video
3. Try to play the video

**Actual results**
Video does not play
**Expected results**
Video should play

**GH Article**
https://github.com/SharePoint/sp-dev-docs/blob/live/docs/spfx/debug-in-vscode.md

image

### PR DESCRIPTION
**Pull request by cakriwut**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #2248

#### What's in this Pull Request?

> Fixing video link to Pnp - Debugging SharePoint Framework solutions in Visual Studio Code

#### Guidance

> Fixing video link to Pnp - Debugging SharePoint Framework solutions in Visual Studio Code

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[01b62f3](https://github.com/cakriwut/sp-dev-docs/pull/3252/commits/01b62f3d576f8c1a5bc02ad7b2cfdebf62a1f44f)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[01b62f3](https://github.com/cakriwut/sp-dev-docs/pull/3252/commits/01b62f3d576f8c1a5bc02ad7b2cfdebf62a1f44f)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[01b62f3](https://github.com/cakriwut/sp-dev-docs/pull/3252/commits/01b62f3d576f8c1a5bc02ad7b2cfdebf62a1f44f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/debug-in-vscode.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2248/docs/spfx/debug-in-vscode.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-3252) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C12%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901121506386853-3252%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=HT0V1RbeoimCoULqFI%2FTVXNYObfUTZJVMXRtehlGtvg%3D&st=2019-01-12T15%3A03%3A26Z&se=2019-02-12T15%3A08%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @cakriwut, appreciated.

**Pull request merged**
