### PR TITLE
Update supporting-and-in-file-and-folder-with-the-resourcepath-api.md

### PR DESCRIPTION
**Pull request by expiscornovus**
Tested the Get Folders code snippet and it did not work without the library name.

## Category

- [x] Content fix
- [ ] New article

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e0abc5b](https://github.com/expiscornovus/sp-dev-docs/commits/e0abc5ba5638d05aed8a6e0db9fb60277b089619)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md](https://github.com/expiscornovus/sp-dev-docs/blob/patch-1/docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api?branch=pr-en-us-8457) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202209261524595962-8457/BuildReport?accessString=462d2299b8c73803dfe84a0cd023b09d320738f5c57a03ebc5fa21d5fbdf1a11).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change. I took care of it in this PR, but please make sure to include this in the future.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6e5ea0c](https://github.com/expiscornovus/sp-dev-docs/commits/6e5ea0cf26bfd837777d14e87be566206c51d3d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md](https://github.com/expiscornovus/sp-dev-docs/blob/patch-1/docs/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/supporting-and-in-file-and-folder-with-the-resourcepath-api?branch=pr-en-us-8457) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202209271948231929-8457/BuildReport?accessString=bf08049d7f4bf493cae1d65d054d0d14238bf1512b3a28e87f69dcccf1a8c393).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by expiscornovus** [comment]
> When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change. I took care of it in this PR, but please make sure to include this in the future.

@andrewconnell sorry I missed that part. I will make sure I will include that in the future :)

**Pull request merged**
