### PR TITLE
Update migration-api-overview.md

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
## Category

- [X ] Content fix/update

## What's in this Pull Request?

Added paragraph to the ExportSettings section to detail the new requirement of SourceType, also added example.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Learn Build status updates of commit _[bb1207d](https://github.com/JoanneHendrickson/sp-dev-docs/commits/bb1207dfe8ed2fbab1470bb950e9c2b6abe8cad3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-70/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8620) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202211291642220492-8620/BuildReport?accessString=c9a6336da3111dc57e3941f27aab393dbc0a12ea2c7f91d93181e07a35bf8aef).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Learn Build status updates of commit _[c741975](https://github.com/JoanneHendrickson/sp-dev-docs/commits/c74197579e5db6311a47f773a2fa4db84e44caf2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fb6fd7ee)

<a id="fb6fd7ee"></a>
###
 - **[Error: RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202212051751553492-8620/BuildReport?accessString=abe45e2dc75f6f00ff7d1fb90f5b7674df0c24432692376ede4f1f0bf2bc382d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by andrewconnell** [comment]
Closing/opening to trigger rebuild

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Learn Build status updates of commit _[c741975](https://github.com/JoanneHendrickson/sp-dev-docs/commits/c74197579e5db6311a47f773a2fa4db84e44caf2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-70/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8620) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202212051756010578-8620/BuildReport?accessString=85cdc510ba5777484ccdadf2d5f12eb22024718967e1bcceee01c15be81faa9b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Learn Build status updates of commit _[a407751](https://github.com/JoanneHendrickson/sp-dev-docs/commits/a407751e469bc4a8c49ab7d8dd790b3e1a8c9f4d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-70/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8620) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202212051756578405-8620/BuildReport?accessString=b814b7abdf25aec7f716d53fa7f719c0cb6afeda536bf0a531193b0d846fa58a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by andrewconnell** [comment]
This came in between the scheduled times I review PRs hence the delay. I've fixed issues in the doc and defer to @VesaJuvonen to push the changes to live as I don't have permission to do that.

**Comment by JoanneHendrickson** [comment]
Thanks @andrewconnell  -- Appreciate it.  Knowing the review and publishing cadence and how long to file PRs would help me communicate to the product team and set their expectations.

**Comment by JoanneHendrickson** [comment]
@andrewconnell  @VesaJuvonen   - This is a high priority item for our ISVs and it still isn't published live. What can we do to escalate this?

**Comment by VesaJuvonen** [comment]
@JoanneHendrickson whenever there are any high priority items, please do ping me in the Teams so that we know about the timelines and can plan accordingly. We do not know about this urgency or your timelines otherwise. Thx.

**Comment by JoanneHendrickson** [comment]
Thanks, Vesa.  I will do so in the future.

**Pull request merged**
