### PR TITLE
Update toc.yml

### LINKED ISSUE #6179: Add 'Configuring the PnP Provisioning Engine' to the left nav
This doc should show up in the left nav, IMO. I always have trouble finding it, and I expect others may not ever see it.

There's a link to this doc in the [Introducing the PnP provisioning engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine#using-powershell-cmdlets) doc, but it's not totally obvious, if only because it's on a purple background in a note!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8604e955-4a77-7abe-0138-e554fdef0b41
* Version Independent ID: b03bc3e7-88ec-b808-190c-32e69f0b968e
* Content: [Configurating the PnP Provisioning Engine](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configuring-the-pnp-provisioning-engine)
* Content Source: [docs/solution-guidance/configuring-the-pnp-provisioning-engine.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/configuring-the-pnp-provisioning-engine.md)
* Product: **sharepoint**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

### PR DESCRIPTION
**Pull request by sympmarc**
Added Configuring the PnP Provisioning Engine to the PnP Remote Provisioning section

## Category

- [X] Content fix
- [ ] New article

## Related issues

- fixes #6179 

## What's in this Pull Request?

Addition to the left nav: Configuring the PnP Provisioning Engine

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @sympmarc, appreciated.

**Comment by sympmarc** [comment]
Just curious - does the publication take a while? I don't see the result yet when I go to [the site](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-provisioning).

**Comment by sympmarc** [comment]
Never mind. I see you've got a master and a live here as well. It'll get there when it gets there!

**Comment by VesaJuvonen** [comment]
Thanks for following up - that's actually my bad. I should have got it released right away. Just completed the steps.

**Pull request merged**
