### PR TITLE
Feature/azure devops spfx182

### PR DESCRIPTION
**Pull request by baywet**
#### Category
- [x] Content fix
- [ ] New article
#### What's in this Pull Request?
- switches azure devops recommended node version to 10 as spfx 1.8.2 supports it and it represents significant performance gains.
- minor screenshots improvements

### CODE REVIEW

**Comment by baywet** [comment]
@andrewconnell any chance you could help with this one as well since Vesa is on vacations?

**Comment by andrewconnell** [comment]
I review all PR's on a schedule... no need to @mention me ;) I can only merge those PR's that are just typos / minor fixes... anything that needs to be looked at by engineering, I need to let an @microsoft.com employee own their own docs :)

At any rate, I'll review when I have some time...

**Comment by baywet** [comment]
thanks for the precisions! I wasn't aware that microsoftees needed to review subsequent changes even on content originally created by the community.

**Comment by andrewconnell** [comment]
What's on the public docs.microsoft.com site = MSFT content so they need to own it. Even if the community wrote the initial draft, MSFT published it so someone on the MSFT side is responsible.

**Comment by VesaJuvonen** [comment]
thx @baywet, appreciated. Like @andrewconnell noted... even though document might be provided by the community, it's published by Microsoft who owns the document as this is the official SharePoint developer documentation at docs.microsoft.com... that's why all bigger changes will need to be approved by MSFT to ensure that there's clear track of ownership and approval of the content in here.

**Pull request merged**
