### PR TITLE
Fix formatting doc for executeFlow and embed actions

### PR DESCRIPTION
**Pull request by arkogupta**
## Category

- [X] Content fix

## What's in this Pull Request?

Fixes the content added in #9615. There was some misalignment and missing information for `executeFlow` and `embed` actions which is now fixed in this PR.

### CODE REVIEW

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Please review the edits to verify they are correct before we can merge.

**Review by arkogupta — COMMENTED** [review]
> [!NOTE]
    > The `embed` action is only available in the newer version of the Microsoft Lists App.
    
    This line seems to be repeated.
    Also, could you check the preview once please? I can see the "!Note" show up in the preview.
    
image

**Review by arkogupta — COMMENTED** [review]
Also could you kindly change "For more information about the allowing domains" to "For more information about how to allow list domains" ? 
Thanks!

**Comment by andrewconnell** [comment]
@arkogupta I'm not clear on either of your last two messages. There aren't two `embed` listings... there's only a single one & the second note is rendering correctly. Your screenshot is from the GH preview rendering... that's not what gets rendered by MSDocs. You can see the preview from the MSFT internally accessible link in the automated [build check comment](https://github.com/SharePoint/sp-dev-docs/pull/9649#issuecomment-2069188206).

Also, your request to change the text for the link isn't grammatically correct... can you please review the text and make the changes as you deem necessary?

If you need to make edits to the content, please feel free to edit the PR.

FYI - my role is to review the PR submissions... Not to rewrite what you've submitted. In [my commit](https://github.com/SharePoint/sp-dev-docs/pull/9649/commits/f659dd2841145594c37046ec39748b49bea3b94b), I only made corrections to the way you had created a *note* to conform to the correct MSDocs style... I am not an expert on declarative formatting so I'll defer to you to correct the content if it needs correcting.

**Comment by arkogupta** [comment]
@andrewconnell Thanks for the clarification. I made the edits in my latest iteration. Could you please check. Thanks!

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
