### PR TITLE
Fix: broken link to viva connections readme

### PR DESCRIPTION
**Pull request by OmarStewey**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

Fix reference to Viva Documentation Link

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e38e2d9](https://github.com/OmarStewey/sp-dev-docs/commits/e38e2d9bd6e7f664585642198cf09106d9bc55f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/features/embed-pages-to-teams.md](https://github.com/OmarStewey/sp-dev-docs/blob/patch-1/docs/features/embed-pages-to-teams.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/features/embed-pages-to-teams?branch=pr-en-us-7289) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109010308028736-7289%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=PeEVQ776mBU4NKttJZDh53AginxpQUGWv2Zu3iTXeX4%3D&st=2021-09-01T03%3A04%3A21Z&se=2021-10-02T03%3A09%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
This link is not broken and is pointing to the correct location. The link you changed it to is the source for the content published on the site. The docs shouldn't link to that.

**Comment by OmarStewey** [comment]
The current link is a 404.

**Comment by andrewconnell** [comment]
It's working just fine for me... what's your locale?

**Comment by OmarStewey** [comment]
United States: en-US. 
That's weird, the link I see in the docs point to "https://github.com/SharePoint/sp-dev-docs/blob/master/SharePoint/viva-connections" which is 404ing.

**Comment by andrewconnell** [comment]
Where are you seeing that? Can you provide the URL?

This page is deployed here:
https://docs.microsoft.com/sharepoint/dev/features/embed-pages-to-teams

**Comment by OmarStewey** [comment]
Ah, accessing from there works fine, thanks! Somehow I clicked around and ended up on the GitHub readme.

**Comment by andrewconnell** [comment]
Links in the docs must always be relative to the file within the repo. The MSDOCS build engine figures out the correct links... think of anything related to docs in the GH repos as "source code" for the published docs. IOW, we never link to GH files as we want people staying on docs.m.com. This way, locale's are automatically determined & people are rerouted based on their browser settings, the request, and if the docs have been localized.

**Comment by OmarStewey** [comment]
Copy! That's a nice way of doing it, thanks for explaining.

**Pull request closed without merging**
