### PR TITLE
Corrected split operator syntax

### PR DESCRIPTION
**Pull request by ganesh-sanap**
## Category

- [x] Content fix

## What's in this Pull Request?

Corrected split operator syntax and expression in examples

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Learn Build status updates of commit _[b3e82d9](https://github.com/ganesh-sanap/sp-dev-docs/commits/b3e82d9424e17b8b9c9ffa13bbe896b639b96d34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-4/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8476) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202210030745397171-8476/BuildReport?accessString=8e6b168f02c1a57e62f341a29030defb4d90870343fb44cbf873c88b432751a7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

**Comment by ganesh-sanap** [comment]
@andrewconnell I have updated the date in mentioned format, thank you!

**Comment by VesaJuvonen** [comment]
Learn Build status updates of commit _[184b5b8](https://github.com/ganesh-sanap/sp-dev-docs/commits/184b5b8b1462437f119f041cf576e69500cd08e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-4/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8476) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202210041426236313-8476/BuildReport?accessString=01d9b225705f169f71f2e1b77dd06689c923198282034fe7a28d0c7dc5b6f47c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
