### PR TITLE
Update search-content.md to include search by contaienr custom property scenario

### PR DESCRIPTION
**Pull request by tonchan-msft**
## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes BUG 2160957

## What's in this Pull Request?
Update search-content.md to include search by contaienr custom property scenario

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `main` branch of this repo.
> - When changing a page, ensure you update the `ms.date` front matter wih the current date in the format `MM/DD/YYYY`.
> - Review all build checks and address the automated errors, warnings, and suggestions.
> - *NOTE: The live site is based on the `live` branch. Site owners periodically refresh `live` branch from the `main` branch so merged PRs won't immediately appear on the live site. Please be patient to see your changes appear on the live site.*
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

### CODE REVIEW

**Review by ReidCarlberg — CHANGES_REQUESTED** [review]
This works regardless of whether it's opted out of M365 discoverability, right?  This is generally how to search drives using container properties.  And ContainerTypeId is optional as well, right?  I would simplify like 434.

Also note that this does not yet work on my tenant due to propagation timelines.

**Comment by tonchan-msft** [comment]
I am keeping reference to M365Discoverability and ContainerType in the example as best practices. Both are explained in the article on when/if they are applicable.

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
@tonchan-msft @ReidCarlberg is this ready to merge? I see an outstanding change requested that's not been resolved... can't tell from the discussion if it has been addressed.

**Comment by andrewconnell** [comment]
Bump... is this ready to merge @tonchan-msft / @ReidCarlberg ?

**Review by ReidCarlberg — COMMENTED** [review]
@tonchan-msft Can you also create an example 6 that shows people how to query by metadata (and file fields)?

To search for a file using metadata, use "exact" and enter FieldNameOWSTEXT:"fieldvalue" (note the double quotes around fieldvalue)

Likewise, we need an example that shows people how to return the fields as part of their search results -- it should be a different request body 

{
  "requests": [
    {
      "entityTypes": [
        "driveItem"
      ],
      "query": {
        "queryString": "'part time jobs' AND ContainerTypeId:262757d3-bace-0033-3045-65f907f42d63"
      },
      "sharePointOneDriveOptions": {
        "includeHiddenContent": true
      },
      "fields": [
        "SampleOWSText",
        "id",
        "name",
        "parentReference",
        "file",
        "folder",
        "webUrl",
        "createdDateTime",
        "lastModifiedDateTime",
        "size",
        "fileSystemInfo",
        "createdBy",
        "lastModifiedBy",
        "fileSystemInfo",
        "fileSystemInfo"
      ]
    }
  ]
}

Also does this approach work for drives like it does for drive items?

**Comment by ReidCarlberg** [comment]
> Bump... is this ready to merge @tonchan-msft / @ReidCarlberg ?

No we need to add some more detail to search on container properties and metadata.

**Comment by andrewconnell** [comment]
@ReidCarlberg ok... I'm going to change this PR to being in DRAFT (as the current state implies it's ready for review & publication). When you're ready for it to get merged, just switch it back out of draft mode.

**Comment by tonchan-msft** [comment]
@andrewconnell i dont know how to get this out of draft. but can we publish?

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
