### PR TITLE
Validation: fix multiple issues on multiple files

### PR DESCRIPTION
**Pull request by LSchaufMS**
## Category

- [x] Content fix
- [ ] New article

## Related issues

- no issue numbers; changes are part of the Validation cleanup efforts

## What's in this Pull Request?

This PR fixes 29 issues in 10 files.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6ee94be](https://github.com/LSchaufMS/sp-dev-docs/commits/6ee94becd4e87fb4de3033d18b301fcd52bb59a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest?branch=pr-en-us-8151) | [Details](#user-content-85b0ca314207cde9a8a9438f20e35268-c824e4a2)

<a id="85b0ca314207cde9a8a9438f20e35268-c824e4a2"></a>
### [docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 26, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206102151349109-8151/BuildReport?accessString=8e61fd2a72f980a123ab803a348951c8b12b1a52295ab141bcc751ede82f25b0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e6b527a](https://github.com/LSchaufMS/sp-dev-docs/commits/e6b527af6c152ffd70e598fd920e3c920283807c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest?branch=pr-en-us-8151) | [Details](#user-content-85b0ca314207cde9a8a9438f20e35268-6a332c19)
[docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in?branch=pr-en-us-8151) | [Details](#user-content-2385758f8d0d70881d463545c3ec559f-6a332c19)
[docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8151) | [Details](#user-content-e0667899ad2bdac8242280a6c330c928-6a332c19)
[docs/schema/removefieldref-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removefieldref-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/removefieldref-element-contenttype?branch=pr-en-us-8151) | [Details](#user-content-695502b6f31c07051e6acdace0c61aa7-6a332c19)
[docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrule-complextype-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-300985721e9402e1883464fe39bf0e64-6a332c19)
[docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-126455447ef40ee3749a9b7be150d17b-6a332c19)
[docs/schema/reorderingrule-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrule-element-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-295bed2812ec1e1d66a70b398ef41296-6a332c19)
[docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrulematchtype-element-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-29a2d1b552d8da9e240bf93060ea9f7b-6a332c19)
[docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-470ab12faae809a150bf62df33549cc0-6a332c19)

<a id="85b0ca314207cde9a8a9438f20e35268-6a332c19"></a>
### [docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2385758f8d0d70881d463545c3ec559f-6a332c19"></a>
### [docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e0667899ad2bdac8242280a6c330c928-6a332c19"></a>
### [docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="695502b6f31c07051e6acdace0c61aa7-6a332c19"></a>
### [docs/schema/removefieldref-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removefieldref-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="300985721e9402e1883464fe39bf0e64-6a332c19"></a>
### [docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="126455447ef40ee3749a9b7be150d17b-6a332c19"></a>
### [docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="295bed2812ec1e1d66a70b398ef41296-6a332c19"></a>
### [docs/schema/reorderingrule-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="29a2d1b552d8da9e240bf93060ea9f7b-6a332c19"></a>
### [docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="470ab12faae809a150bf62df33549cc0-6a332c19"></a>
### [docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206102234498753-8151/BuildReport?accessString=5a10c8d753a06aea899b4dfa2c1de6715999213f6dee0927cf4777ff05336457).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e3f7b54](https://github.com/LSchaufMS/sp-dev-docs/commits/e3f7b54d801691d5c2cd6f9b5ad0537a90575e39)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest?branch=pr-en-us-8151) | [Details](#user-content-85b0ca314207cde9a8a9438f20e35268-c0af65ee)
[docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in?branch=pr-en-us-8151) | [Details](#user-content-2385758f8d0d70881d463545c3ec559f-c0af65ee)
[docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8151) | [Details](#user-content-e0667899ad2bdac8242280a6c330c928-c0af65ee)
[docs/schema/removefieldref-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removefieldref-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/removefieldref-element-contenttype?branch=pr-en-us-8151) | [Details](#user-content-695502b6f31c07051e6acdace0c61aa7-c0af65ee)
[docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrule-complextype-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-300985721e9402e1883464fe39bf0e64-c0af65ee)
[docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-126455447ef40ee3749a9b7be150d17b-c0af65ee)
[docs/schema/reorderingrule-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrule-element-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-295bed2812ec1e1d66a70b398ef41296-c0af65ee)
[docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrulematchtype-element-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-29a2d1b552d8da9e240bf93060ea9f7b-c0af65ee)
[docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5?branch=pr-en-us-8151) | [Details](#user-content-470ab12faae809a150bf62df33549cc0-c0af65ee)
[docs/schema/representation-element-propertyruleoperator-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/representation-element-propertyruleoperator-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/representation-element-propertyruleoperator-complextypesps15xsdsearchset2?branch=pr-en-us-8151) | [Details](#user-content-9c4773064cdcb5ff2f2a012f4bf29135-c0af65ee)

<a id="85b0ca314207cde9a8a9438f20e35268-c0af65ee"></a>
### [docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remoteendpoints-element-appdefinition-complextypesharepoint-add-in-manifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2385758f8d0d70881d463545c3ec559f-c0af65ee"></a>
### [docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/remotewebapplication-element-appprincipaldefinition-complextypesharepoint-add-in.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e0667899ad2bdac8242280a6c330c928-c0af65ee"></a>
### [docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removeduplicates-element-managedpropertyinfo-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="695502b6f31c07051e6acdace0c61aa7-c0af65ee"></a>
### [docs/schema/removefieldref-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/removefieldref-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="300985721e9402e1883464fe39bf0e64-c0af65ee"></a>
### [docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-complextype-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="126455447ef40ee3749a9b7be150d17b-c0af65ee"></a>
### [docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-arrayofreorderingrule-complextypesps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="295bed2812ec1e1d66a70b398ef41296-c0af65ee"></a>
### [docs/schema/reorderingrule-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrule-element-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="29a2d1b552d8da9e240bf93060ea9f7b-c0af65ee"></a>
### [docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-element-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="470ab12faae809a150bf62df33549cc0-c0af65ee"></a>
### [docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/reorderingrulematchtype-simpletype-sps15xsdsearchset5.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9c4773064cdcb5ff2f2a012f4bf29135-c0af65ee"></a>
### [docs/schema/representation-element-propertyruleoperator-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/representation-element-propertyruleoperator-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206102236081397-8151/BuildReport?accessString=fb48c1f8ff9c1db1472e534aef7b2e58afef9e743cf5a3a11491f8abbc22f7ef).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by LSchaufMS** [comment]
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
