### PR TITLE
Validation: fix multiple errors

### PR DESCRIPTION
**Pull request by LSchaufMS**
VALIDATION

## Category

- [x] Content fix
- [ ] New article

## Related issues

 - no issue number - part of the Validation cleanup efforts.

## What's in this Pull Request?

This PR fixes 29 issues in 12 files.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[04b685f](https://github.com/LSchaufMS/sp-dev-docs/commits/04b685f4cf0b23c99eb7a99073851ba851164e20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/community/social-media.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/social-media.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/social-media?branch=pr-en-us-8013) | [Details](#user-content-7ca4c4ec7d598713a5dabc69bbcd74e3-0d7e0a5a)
[docs/apis/migrate-webparts-with-migrationapi.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migrate-webparts-with-migrationapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migrate-webparts-with-migrationapi?branch=pr-en-us-8013) |
[docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/manage-list-item-file-permissions?branch=pr-en-us-8013) |
[docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/working-with-send-sp-http-request?branch=pr-en-us-8013) |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning?branch=pr-en-us-8013) |
[docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-csom?branch=pr-en-us-8013) |

<a id="7ca4c4ec7d598713a5dabc69bbcd74e3-0d7e0a5a"></a>
### [docs/community/social-media.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/social-media.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206031618497798-8013/BuildReport?accessString=6d76883f70cf96314181f6aae139306d65d13b695ba5be2b04b15736bff4d368).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6377f3e](https://github.com/LSchaufMS/sp-dev-docs/commits/6377f3e7610d9c4f819616b50f7e5eb3ea171676)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/community/social-media.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/social-media.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/social-media?branch=pr-en-us-8013) | [Details](#user-content-7ca4c4ec7d598713a5dabc69bbcd74e3-540f7727)
[docs/general-development/accessing-a-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/accessing-a-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/accessing-a-schema?branch=pr-en-us-8013) | [Details](#user-content-eeedf5826163bc56bf56c98b35f459bd-540f7727)
[docs/general-development/accessing-the-soap-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/accessing-the-soap-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/accessing-the-soap-api?branch=pr-en-us-8013) | [Details](#user-content-39a244b8fc80d459dd5c1527c198938c-540f7727)
[docs/apis/migrate-webparts-with-migrationapi.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migrate-webparts-with-migrationapi.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migrate-webparts-with-migrationapi?branch=pr-en-us-8013) |
[docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/manage-list-item-file-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/manage-list-item-file-permissions?branch=pr-en-us-8013) |
[docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/working-with-send-sp-http-request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/working-with-send-sp-http-request?branch=pr-en-us-8013) |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning?branch=pr-en-us-8013) |
[docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-theming/sharepoint-site-theming-csom.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-csom?branch=pr-en-us-8013) |
[docs/design/ui-text-for-web-parts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/design/ui-text-for-web-parts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/ui-text-for-web-parts?branch=pr-en-us-8013) |
[docs/design/web-part-commanding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/design/web-part-commanding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/web-part-commanding?branch=pr-en-us-8013) |
[docs/features/hub-site/REST-sphubsite-type.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/features/hub-site/REST-sphubsite-type.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/rest-sphubsite-type?branch=pr-en-us-8013) |
[docs/features/hub-site/REST-sphubsitedata-type.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/features/hub-site/REST-sphubsitedata-type.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/features/hub-site/rest-sphubsitedata-type?branch=pr-en-us-8013) |

<a id="7ca4c4ec7d598713a5dabc69bbcd74e3-540f7727"></a>
### [docs/community/social-media.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/social-media.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="eeedf5826163bc56bf56c98b35f459bd-540f7727"></a>
### [docs/general-development/accessing-a-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/accessing-a-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="39a244b8fc80d459dd5c1527c198938c-540f7727"></a>
### [docs/general-development/accessing-the-soap-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/accessing-the-soap-api.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206031637114828-8013/BuildReport?accessString=4b3218d5dbedcc577ff33b2b1b908b8bd07973aba706de2d95bf6dccc50fb90b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by LSchaufMS** [comment]
**Global effort to fix build validation errors**

@VesaJuvonen

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Comment by andrewconnell** [comment]
When updating docs, please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

**Comment by LSchaufMS** [comment]
@andrewconnell ms.date attributes updated.

**Review by andrewconnell — APPROVED** [review]

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
