### PR TITLE
Update migration-api-overview.md

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
Important update regarding the new requirement of QuickXorHash over MD5Hash for files over 15 GB.

## Category

- [x] Content fix
- [ ] New article
- [ ] Example checked item (*delete this line*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.*

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this PR. Sample description or details around bugs which are being fixed.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `master` branch of this repo. Released documents are in `live` branch.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[4228f85](https://github.com/JoanneHendrickson/sp-dev-docs/commits/4228f85e3cbba9ebf7d4e36fddbeed627f072325)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6593) | [Details](#user-content-dd0fe65f-cec4839c)

<a id="dd0fe65f-cec4839c"></a>
### [docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-and-service](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101062202018510-6593%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6z1b6rj2upU6pUWVtbQjlC3LU7qJol%2BLDQcfSeyJTeo%3D&st=2021-01-06T21%3A57%3A51Z&se=2021-02-06T22%3A02%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[30445b1](https://github.com/JoanneHendrickson/sp-dev-docs/commits/30445b1bcf7ea974f9596083fa3d87c3e619f960)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6593) | [Details](#user-content-dd0fe65f-bd618184)

<a id="dd0fe65f-bd618184"></a>
### [docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-and-service](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101062208299889-6593%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nCYKKJBwyS9u%2BvunVPUVjeGVL9e8HKmJ%2BpTBjnrgFnw%3D&st=2021-01-06T22%3A04%3A37Z&se=2021-02-06T22%3A09%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[10c00db](https://github.com/JoanneHendrickson/sp-dev-docs/commits/10c00db82d92d8639b8c961e8c823fadbea137ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6593) | [Details](#user-content-dd0fe65f-ee73ccf9)

<a id="dd0fe65f-ee73ccf9"></a>
### [docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101062219208316-6593%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NXabHcg5mQ2R4%2FCkYR7DeC7%2BkNqOqutEDlhmA1RPJNI%3D&st=2021-01-06T22%3A15%3A26Z&se=2021-02-06T22%3A20%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JoanneHendrickson** [comment]
@VesaJuvonen @andrewconnell    Can I get this pushed out live soon?

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[7a496b4](https://github.com/JoanneHendrickson/sp-dev-docs/commits/7a496b4cb61c8144ab4b516b7b06e92f8e3eef45)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6593) | [Details](#user-content-dd0fe65f-eb4005cd)

<a id="dd0fe65f-eb4005cd"></a>
### [docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-53/docs/apis/migration-api-overview.md)
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101181109162874-6593%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zrGHQGF0p04QQ7v7IFjKgEqojEsApiVrviouLtwO%2Bto%3D&st=2021-01-18T11%3A04%3A55Z&se=2021-02-18T11%3A09%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
@JoanneHendrickson in the future, please use the PR template that is provided when creating a new PR. It contains sections to explain if this is a new/updated doc, and what the changes are. This makes it easier for us to triage and merge PRs in a timely manner.

**Pull request merged**
