### PR TITLE
Update using-web-part-as-ms-teams-tab.md

### PR DESCRIPTION
**Pull request by mrackley**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?
changed the install instructions from "npm install -g @microsoft/sharepoint"   to npm "install -g @microsoft/generator-sharepoint"

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/mrackley/sp-dev-docs/blob/patch-1/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab?branch=pr-en-us-2910) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C11%5C9%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201811091427596459-2910%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=kx3xuJGfjTQLWJd%2BRDYdz%2FXm0zt3EFHK7nsP72Hblro%3D&st=2018-11-09T14%3A25%3A01Z&se=2018-12-10T14%3A30%3A01Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thanks Marc, my typo as was rushing... thanks for correcting this one.

**Comment by mrackley** [comment]
glad to help :)

**Comment by himanshuchuriwala** [comment]
SPFx webpart for MS Teams

[Cannot find module '@microsoft/sp-build-web' error ] Question
While developing spfx solution for ms teams, I am receiving error related to sp-build-web module. I followed the msdn article but still the issue is bothering.

I tried to install the dependencies but still no luck.

**Pull request merged**
