### PR TITLE
Added new article.

### PR DESCRIPTION
**Pull request by Lauragra**
#### Category
- [ ] Content fix
- [X ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
>

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\3mup-s, target branch: master, target branch commit: 76fe0b269811a5c1ed52ca6994a026b61ea0c6ce, source branch: lauragra-shortURLs, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C17%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201803171532052871-1487%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cjV2wuB1ZKc1Hr7vWLrS%2FqcQZOyAyutWVHW9PiOgeqs%3D&st=2018-03-17T15%3A27%3A20Z&se=2018-04-17T15%3A32%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-shortURLs/docs/toc.yml) | :warning:Warning | | [Details](#user-content-docs%2Ftoc.yml)
[docs/spfx/shorter-share-link-format.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-shortURLs/docs/spfx/shorter-share-link-format.md) | :white_check_mark:Succeeded | |

<a name="docs%2Ftoc.yml"></a>
### [docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-shortURLs/docs/toc.yml)
 - **[Warning]** Invalid file link:(~/docs/spfx/shorter-share-link-format.md).

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C17%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201803171533190532-1487%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ftjklp1Vfnfy3IjjRFLc7NIQaAq7qQOY2ydtr92Gqyg%3D&st=2018-03-17T15%3A29%3A39Z&se=2018-04-17T15%3A34%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/shorter-share-link-format.md](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-shortURLs/docs/spfx/shorter-share-link-format.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/lauragra-shortURLs/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C3%5C19%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201803191626433732-1487%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=SbD5Axd54Mw8S%2FwONmkDWsh4yyh%2FxAfw9HMaOroPjpY%3D&st=2018-03-19T16%3A23%3A10Z&se=2018-04-19T16%3A28%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Let's get this merged as is for now and then do nesting if needed in future.

**Pull request merged**
