### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Fixing the link path line 67

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e36beda](https://github.com/DhurataJ/sp-dev-docs/commits/e36beda70261da5d1d7d21371f0cb57721cf2821)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/semantic_slots.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-4/docs/design/semantic_slots.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-7856) | [Details](#user-content-9b4c957a02678e16dcd221c8c130d087-89af80fd)

<a id="9b4c957a02678e16dcd221c8c130d087-89af80fd"></a>
### [docs/design/semantic_slots.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-4/docs/design/semantic_slots.md)
 - **Line 46, Column 5**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'style' on tag 'td' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204041415076288-7856%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T14%3A16%3A36Z&sr=b&sp=r&sig=qTK4tiPZW7x3FI2BxH5CigsW4An61VYLyj4QhAvG%2FX4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by DhurataJ** [comment]
@tfosmark - Please can you review and merge this PR!

**Review by andrewconnell — APPROVED** [review]

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[f57dc39](https://github.com/DhurataJ/sp-dev-docs/commits/f57dc391fe26926f2753187f491713414a734ff5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/semantic_slots.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-4/docs/design/semantic_slots.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-7856) | [Details](#user-content-9b4c957a02678e16dcd221c8c130d087-cf95d689)

<a id="9b4c957a02678e16dcd221c8c130d087-cf95d689"></a>
### [docs/design/semantic_slots.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-4/docs/design/semantic_slots.md)
 - **Line 46, Column 5**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'style' on tag 'td' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204061756150857-7856%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T17%3A57%3A46Z&sr=b&sp=r&sig=RDQE%2BJeTOrsEBl%2FuMH5GIgJDAP1RE%2FogFYxBludfXzw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6eac586](https://github.com/DhurataJ/sp-dev-docs/commits/6eac5869483d4ec41f8cef9178907db7dc68d69a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/semantic_slots.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-4/docs/design/semantic_slots.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-7856) | [Details](#user-content-9b4c957a02678e16dcd221c8c130d087-7f0607df)

<a id="9b4c957a02678e16dcd221c8c130d087-7f0607df"></a>
### [docs/design/semantic_slots.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-4/docs/design/semantic_slots.md)
 - **Line 46, Column 5**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'style' on tag 'td' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204061802226080-7856%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T18%3A03%3A52Z&sr=b&sp=r&sig=ThNqjToHPWDvkqtXjZIhrY0vvgAch6SeCgLC8e6mIp4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
