### PR TITLE
OneDrive Multi-Geo is currently available https://aka.ms/Multi-Geo

### PR DESCRIPTION
**Pull request by Sameer-MSFT**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/multigeo-sites-provisioning.md](https://github.com/Sameer-MSFT/sp-dev-docs/blob/patch-1/docs/solution-guidance/multigeo-sites-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites-provisioning?branch=pr-en-us-2373) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808162048424300-2373%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=X6RmkSTWM7Y2Z7Yhbh2u%2FNUggCf9QzmZusC9XpisNkg%3D&st=2018-08-16T20%3A45%3A59Z&se=2018-09-16T20%3A50%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @Sameer-MSFT, appreciated.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/multigeo-sites-provisioning.md](https://github.com/Sameer-MSFT/sp-dev-docs/blob/patch-1/docs/solution-guidance/multigeo-sites-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites-provisioning?branch=pr-en-us-2373) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201809102003164128-2373%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5OhWKYK2hsWjg7jl5pZFktiDvO9nlcrsw0yG1WuExiI%3D&st=2018-09-10T20%3A00%3A22Z&se=2018-10-11T20%3A05%3A22Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/multigeo-sites-provisioning.md](https://github.com/Sameer-MSFT/sp-dev-docs/blob/patch-1/docs/solution-guidance/multigeo-sites-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/multigeo-sites-provisioning?branch=pr-en-us-2373) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201809102003323454-2373%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Tfjxpl%2BNOUVvGwcuG2POlimukS6%2FQvJ%2BotNnJb34wSc%3D&st=2018-09-10T20%3A02%3A20Z&se=2018-10-11T20%3A07%3A20Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
