### PR TITLE
Fix grammatical error in community.md

### PR DESCRIPTION
**Pull request by clearab**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[59f137f](https://github.com/clearab/sp-dev-docs/pull/3140/commits/59f137f80f150621c2a517be800b91151b1c20a9)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[59f137f](https://github.com/clearab/sp-dev-docs/pull/3140/commits/59f137f80f150621c2a517be800b91151b1c20a9)_: 

:clock10: **Full build**: average full build time is _2 min(s) 5 sec(s)_ [calculated from last _2_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[59f137f](https://github.com/clearab/sp-dev-docs/pull/3140/commits/59f137f80f150621c2a517be800b91151b1c20a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/community/community.md](https://github.com/clearab/sp-dev-docs/blob/patch-1/docs/community/community.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/community?branch=pr-en-us-3140) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812181753327875-3140%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=n8buTrcATp2G4nrPduzfa8uVbiLsJDfgURWKIgqeZHg%3D&st=2018-12-18T17%3A51%3A45Z&se=2019-01-18T17%3A56%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @clearab, appreciated.

**Pull request merged**
