### PR TITLE
Update event-receiver-and-list-event-receiver-sharepoint-add-in.md

### LINKED ISSUE #7180: Broken Links found - need to remove them
Carry over from Issue #6443 where it was discovered that there were two obsolete links in the document: 

Using Azure storage queues and WebJobs for async actions in Office 365 (MSDN Blog Post)
https://blogs.msdn.com/b/vesku/archive/2015/03/02/using-azure-storage-queues-and-webjobs-for-async-actions-in-office-365.aspx

Attaching Remote Event Receivers to Lists in the Host Web (MSDN Blog Post)
https://blogs.msdn.com/b/kaevans/archive/2014/02/26/attaching-remote-event-receivers-to-lists-in-the-host-web.aspx

There is not update or new reference for them and as they are just references, may be removed (discussed with @andrewconnell  on the closed ticket)   Thank you! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f8a983b-ae73-33c9-fd11-ac064e1eea9e
* Version Independent ID: 6baa41f1-4d40-b7ad-0f84-670d2700a16b
* Content: [Event receivers and list event receivers in the SharePoint Add-in model](https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in?source=docs)
* Content Source: [docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

### PR DESCRIPTION
**Pull request by bigpix2000**
Removed the bad links per discussion in issue #6443

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #7180 

## What's in this Pull Request?

More like what is not: the bad links are removed

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[4cc7e55](https://github.com/bigpix2000/sp-dev-docs/commits/4cc7e55090b874c1b454035e73ae5033da3ead2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/bigpix2000/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in?branch=pr-en-us-7181) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202107161418232045-7181%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-16T08%3A08%3A34Z&ske=2021-07-23T08%3A13%3A34Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-16T14%3A14%3A38Z&se=2021-08-16T14%3A19%3A38Z&sr=b&sp=r&sig=BcoUU20UjB0Z68Smd4sb7FN%2FRlQsioR7CcADK2hp7IM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by bigpix2000** [comment]
@andrewconnell - I followed my process for my licensing doc but it looks like this area is a bit more locked down.  Let me know if I need to pick a different branch thanks!

**Comment by bigpix2000** [comment]
@andrewconnell - uhm  Maybe never mind because the report I got back did not have the error I expected related to this and looks like the @VesaJuvonen bot is on it ;-)  thanks!  I imagine someone will ding/ping me if there is anything else missed

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[eef03fc](https://github.com/bigpix2000/sp-dev-docs/commits/eef03fc43c5cda1de424077de57b129e1e00c856)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/bigpix2000/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in?branch=pr-en-us-7181) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C20%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202107201134388217-7181%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-20T06%3A53%3A00Z&ske=2021-07-27T06%3A58%3A00Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-20T11%3A30%3A52Z&se=2021-08-20T11%3A35%3A52Z&sr=b&sp=r&sig=CZsBBSEOFDmJ97%2FLUYH0GdRVM4Y24RZiWHP7w6swtQM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
