### PR TITLE
Update overview.md

### PR DESCRIPTION
**Pull request by Tiptioka**
I'd like to post a survey on the learn page to capture the response from users that are not directly in touch with us.  The survey is not about the content directly, but will help us to understand how can we improve the SPE onboarding

## Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.*

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this PR. Sample description or details around bugs which are being fixed.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `main` branch of this repo.
> - When changing a page, ensure you update the `ms.date` front matter wih the current date in the format `MM/DD/YYYY`.
> - Review all build checks and address the automated errors, warnings, and suggestions.
> - *NOTE: The live site is based on the `live` branch. Site owners periodically refresh `live` branch from the `main` branch so merged PRs won't immediately appear on the live site. Please be patient to see your changes appear on the live site.*
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

### CODE REVIEW

**Comment by Tiptioka** [comment]
@andrewconnell @cindylay hey, can ew please push this one?

**Comment by andrewconnell** [comment]
@cindylay can you comment on this?

Respectfully, I can't tell who @Tiptioka is from the GH profile & with no history, not sure if the PG is ok adding a survey to the SPE homepage in the dev docs.

Just making sure before I merge this...

**Review by andrewconnell — APPROVED** [review]

**Comment by cindylay** [comment]
This is from Olesea @Tiptioka  on our design team. I'm good with these changes!

**Comment by cindylay** [comment]
> @cindylay can you comment on this?
> 
> Respectfully, I can't tell who @Tiptioka is from the GH profile & with virtually no history on GH, I'm not sure if the PG is ok adding a survey to the SPE homepage in the dev docs.
> 
> Just making sure before I merge this...

This looks good to me! @Tiptioka I believe is Olesea from our design team since she was trying to make this change

**Comment by Tiptioka** [comment]
Hey @cindylay @andrewconnell  Thanks. When will we see the change on the learn pages?

**Comment by andrewconnell** [comment]
Microsoft periodically does pushes to live... I'll ping the team responsible just to make sure they're aware.

**Comment by Tiptioka** [comment]
Thanks

**Pull request merged**
