### PR TITLE
Update migrate-from-classic-workflows-to-power-automate-flows.md

### PR DESCRIPTION
**Pull request by omarelanis**
For the section "Workflow administration" item "Create a workflow with elevated permissions" it is possible to elevate a workflow in PowerAutomate by calling a child workflow, this allows the child workflow to run under the elevated permissions of the flow publisher instead of the user running the flow granting the elevated permissions of the publisher account.

It would be useful to have this mentioned for when people come across this section so they are aware there is a possible work around

## Category

- [X] Content fix

## What's in this Pull Request?

Change to the section "Workflow administration" item "Create a workflow with elevated permissions"

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e1f46e9](https://github.com/omarelanis/sp-dev-docs/commits/e1f46e927c419293e940142a812a005d92ed041a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-6848) | [Details](#user-content-8965aabb3532f9fc60e1442019667041-fcaf6964)

<a id="8965aabb3532f9fc60e1442019667041-fcaf6964"></a>
### [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202103231022236466-6848%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vga%2FGOf9Kh%2FGahwDoHZ%2BYyWuGxec5mI%2FunDaXqJ221M%3D&st=2021-03-23T10%3A18%3A26Z&se=2021-04-23T10%3A23%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[f717076](https://github.com/omarelanis/sp-dev-docs/commits/f71707636c33034af24a827adc70ab966767c57a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-6848) | [Details](#user-content-8965aabb3532f9fc60e1442019667041-01f39a73)

<a id="8965aabb3532f9fc60e1442019667041-01f39a73"></a>
### [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
 - **Line 41, Column 1**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/power-automate/getting-started' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 51, Column 342**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/power-automate/mobile-create-flow' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 53, Column 123**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/introduction-to-sharepoint-business-process-integration' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 71, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/power-automate/modern-approvals' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 73, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/power-automate/sequential-modern-approvals' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 75, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/power-automate/parallel-modern-approvals' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 77, Column 30**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/power-automate/guidance/customize-page-approvals' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 77, Column 154**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/power-automate/guidance/require-doc-approval' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 89, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/power-automate/sharepoint-connector-actions-triggers' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 91, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/learn/browse/?products=power-automate&term=Power%20Automate&terms=Power%20Automate' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 93, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/power-automate/?utm_source=flow-sidebar&utm_medium=web' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106221126358776-6848%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HvvpoBAHoromHFiQGbjZN6602VPsI4IdjWR%2F4Qip1Bs%3D&st=2021-06-22T11%3A22%3A46Z&se=2021-07-23T11%3A27%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
@omarelanis - can you please sign the CLA as indicated in the comments above? We can't merge your changes or process this PR further without this. Thanks

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[4f8f81f](https://github.com/omarelanis/sp-dev-docs/commits/4f8f81f0ccd76ae859a0cb7fe7b7d8ab08a007a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-6848) | [Details](#user-content-8965aabb3532f9fc60e1442019667041-58f5ae67)

<a id="8965aabb3532f9fc60e1442019667041-58f5ae67"></a>
### [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
 - **Line 53, Column 123**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/introduction-to-sharepoint-business-process-integration' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 77, Column 30**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/power-automate/guidance/customize-page-approvals' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 77, Column 154**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/power-automate/guidance/require-doc-approval' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 89, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/business-apps/power-automate/sharepoint-connector-actions-triggers' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 91, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/learn/browse/?products=power-automate&term=Power%20Automate&terms=Power%20Automate' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106221136062122-6848%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H0M1PreruYGNg5ppFkjq1fxjDIIELAI5itd6%2F4wGXFY%3D&st=2021-06-22T11%3A32%3A44Z&se=2021-07-23T11%3A37%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[1a5f4fc](https://github.com/omarelanis/sp-dev-docs/commits/1a5f4fc7d2d0acbd0263866d2564e2177e7bbc37)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-6848) | [Details](#user-content-8965aabb3532f9fc60e1442019667041-488020dc)

<a id="8965aabb3532f9fc60e1442019667041-488020dc"></a>
### [docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md)
 - **Line 51, Column 123**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../introduction-to-sharepoint-business-process-integration'.`````
 - **Line 74, Column 30**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../power-automate/guidance/customize-page-approvals'.`````
 - **Line 74, Column 104**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../power-automate/guidance/require-doc-approval'.`````
 - **Line 86, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../power-automate/sharepoint-connector-actions-triggers'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106221143513234-6848%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZJH34f3poyhUQS9lMrHFfpCSKNcusr8ymA6PHXLPUiQ%3D&st=2021-06-22T11%3A40%3A03Z&se=2021-07-23T11%3A45%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by omarelanis** [comment]
@andrewconnell done! Thanks

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[fb24839](https://github.com/omarelanis/sp-dev-docs/commits/fb24839e02001247f79f86c95dd784558f2ee7ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/omarelanis/sp-dev-docs/blob/patch-1/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-6848) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106221148070225-6848%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aaXIX1lZJID1ASsGSkr682DlftmDon5nyFDU1ZntyHU%3D&st=2021-06-22T11%3A44%3A21Z&se=2021-07-23T11%3A49%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request closed without merging**
