### PR TITLE
Update require-doc-approval.md

### PR DESCRIPTION
**Pull request by noideajase**
Information Note that documentation is out of date

Introduction

- Single line added to advise readers of the documentation that this article is no longer current for O365 SharePoint. 

## Related issues

- fixes N/A
- partially N/A
- mentioned in N/A

> No fixes.

## What's in this Pull Request?

Addition of a single line noting that the procedures within this document are no longer compatible with the  SharePoint Office 365 environment.

### CODE REVIEW

**Comment by andrewconnell** [comment]
Thanks for your contribution, but instead of negating the value of the doc, can you explain what's wrong and suggest how to fix it, ideally submitting a PR with the changes to make it current?

**Comment by andrewconnell** [comment]
@noideajase bump... please see last comment https://github.com/SharePoint/sp-dev-docs/pull/9352#issuecomment-1826754732

**Comment by noideajase** [comment]
> Thanks for your contribution, but instead of negating the value of the doc, can you explain what's wrong and suggest how to fix it, ideally submitting a PR with the changes to make it current?

Apologies, maybe this was the wrong place (or way) to raise the issue, I have abandoned trying to implement my required Flows (time poor, many other tasks to attend to) and was originally looking at these docs as they are within the official MS Docs. My only contribution at his stage is does not work please remove or mark up as legacy instructions for a deprecated version of SharePoint 365. I am from the school of SharePoint on premise and have not had a lot to do with any of the advanced Admin features since, if possible feel free to delete this pull request.

**Comment by andrewconnell** [comment]
Hi @noideajase... you posted the question to the correct repo... if this was more of a "hey, the docs are incorrect", you should post that as an issue. 

The way you submitted it was to edit the published docs to say "this doc is wrong" without providing any corrections or updates. If the docs are incorrect, please submit an issue and we'll look into it to get this fixed. But the first step isn't to edit the doc to broadcast it's broken, rather its to file an issue. 

If I'm correct in understanding what you were intending to do, please:

1. Close this PR
1. Comment on the doc - at the bottom of all pages in the SharePoint dev docs, there's a FEEDBACK option where you can COMMENT on the page. That will create an issue for someone to investigate.

**Comment by noideajase** [comment]
My apologies @andrewconnell - first time using Git outside of  syncing my own private Visual Studio projects.
Have closed this pull request, certainly won't be making this mistake again and appreciate your patience in explaining the correct method. 
My original thought process was to make it clear to other potential users prior to reading this section of the docs that it is no longer up to date with O365 and is legacy information only, but reflecting on this now I can see if the change request was accepted there would be no issue flagged and the article would remain in its deprecated state.
I will do some further research so I can be clear within my comments as to where the docs start to digress from the current O365 architecture. 
I also appreciate that this support is likely all through volunteer hours so do appreciate that you have taken time to provide this feedback.
Once again thanks for clarifying and wishing you all the best for the upcoming festive season.

**Pull request closed without merging**
