### PR TITLE
Added information about the Remove-SPOStorageEntity cmdlet

### PR DESCRIPTION
**Pull request by waldekmastykarz**
| Q                   | A
| ---------------     | ---
| content fix?        | yes
| New article?        | no
| Related issues?     | n/a

#### What's in this Pull Request?

Fixed typos and added information about the Remove-SPOStorageEntity cmdlet

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/tenant-properties.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/tenant-properties-fix/docs/spfx/tenant-properties.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C18%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710181243586637-959%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8B6XQc7cpqtGxfNX0YNns0ZK6mdIWPXkbiNkr6jhX%2FQ%3D&st=2017-10-18T12%3A39%3A55Z&se=2017-11-18T12%3A44%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thx Waldek, appreciated.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 356**: **[Error]** Error happened in build.entrypoint.ps1. Please build your target branch first and then reopen this pull request to do another round of verification. If the issue still happens, open a ticket in http://SiteHelp and include the following error message for our team to troubleshoot: The process cannot access the file &#39;tmp_pack_Z4tf2a&#39; because it is being used by another process.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710261052594253-959%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=z8pdbiIQNqKHg47Vxy%2FCw6AjQde14Q2JCTEnaK0qvpk%3D&st=2017-10-26T11%3A08%3A54Z&se=2017-11-26T11%3A13%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/tenant-properties.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/tenant-properties-fix/docs/spfx/tenant-properties.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C26%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710261054073348-959%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5bernvLVWyJ8S1sd2ZVssMxmPd7cW6cym35jFW03X10%3D&st=2017-10-26T11%3A09%3A53Z&se=2017-11-26T11%3A14%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
