### PR TITLE
Updated to reflect change in PowerShell cmdlets

### PR DESCRIPTION
**Pull request by lafe**
## Category

- [X] Content fix
- [ ] New article

## What's in this Pull Request?

As of version [0.3.*-nightly](https://github.com/pnp/powershell/blob/master/CHANGELOG.md) of the PnP PowerShell Cmdlets, the `PnPClientSidePage` Cmdlets have been replaced with matching `PnPPage` Cmdelts. This PR changes the old cmdlet to the new one.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[4e1da1d](https://github.com/lafe/sp-dev-docs/commits/4e1da1d90d18476c72cab20918052bc2a97f7b1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/lafe/sp-dev-docs/blob/patch-2/docs/general-development/sharepoint-search-rest-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview?branch=pr-en-us-7553) | [Details](#user-content-c36ed23e96d0ceb0ab0fe77a97ebbefb-12d6a70c)
[docs/spfx/web-parts/single-part-app-pages.md](https://github.com/lafe/sp-dev-docs/blob/patch-2/docs/spfx/web-parts/single-part-app-pages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages?branch=pr-en-us-7553) |

<a id="c36ed23e96d0ceb0ab0fe77a97ebbefb-12d6a70c"></a>
### [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/lafe/sp-dev-docs/blob/patch-2/docs/general-development/sharepoint-search-rest-api-overview.md)
 - **Line 1186, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      <WhiteList xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays">'`````
 - **Line 1199, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      </WhiteList>'`````
 - **Line 1215, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '- **WhiteList** element'`````
 - **Line 1219, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: 'hat's specified in the **QueryProperties** element. Then, all the properties that are listed in the whitelist are copied from the incoming query to the newly constructed query object.'`````
 - **Line 17, Column 94**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/hybrid/learn-about-cloud-hybrid-search-for-sharepoint' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C2%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202112020759190946-7553%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-02T08%3A00%3A42Z&sr=b&sp=r&sig=tFi%2BDDeimXdhdBirww6qqvp3WnVLORwanK0%2Bjeu3MWE%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
@erwinvanhunen OP indicates this change is introduced in a nightly build from long ago. Is it correct to state that `PnPClientSidePage` is no longer used & instead should be replaced with `PnPPage`?

If so, think this PR should be expanded to first check all docs to find instances of related outdated cmdlets.

**Comment by s-KaiNet** [comment]
@andrewconnell FYI when trying to execute the below script with `PnP-Powershell@1.8` 
```bash
Set-PnPClientSidePage -Identity Home1 -LayoutType Article
```
I see the message: 

> WARNING: Please use 'Set-PnPPage'. The alias 'Set-PnPClientSidePage' will be removed in the 1.5.0 release

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[11da1e7](https://github.com/lafe/sp-dev-docs/commits/11da1e72e322cf596ac636601b543f11dc775894)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/web-parts/single-part-app-pages.md](https://github.com/lafe/sp-dev-docs/blob/patch-2/docs/spfx/web-parts/single-part-app-pages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/single-part-app-pages?branch=pr-en-us-7553) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C12%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202112131700381077-7553%5Cworkflow_report.html?sv=2020-08-04&se=2022-01-13T17%3A01%3A46Z&sr=b&sp=r&sig=px3xFWtBWAMm3NIjA1xnKLg1OA9BwfX%2BgUNRYrVgTdw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
