### PR TITLE
Update site-design-scoping.md to clarify admin rights

### PR DESCRIPTION
**Pull request by sparkitect**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

Note added about SharePoint Admin permissions. Testing indicates that SharePoint Admins will see all Site Templates defines, regardless of any scoping that is done.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[787bce3](https://github.com/sparkitect/sp-dev-docs/commits/787bce3e16e4b879009b568e5eca1b0b9f75a017)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-scoping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-scoping?branch=pr-en-us-8168) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206132144065701-8168/BuildReport?accessString=264bb5711ef4c2260316f04262cf1217c01fff3c66d6c3ae1cc8ce23b76d79b1).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[181810d](https://github.com/sparkitect/sp-dev-docs/commits/181810d490cc98f4d2973833d209948cb70e3c95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-scoping.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-scoping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-scoping?branch=pr-en-us-8168) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201519445117-8168/BuildReport?accessString=122dfbdb3fa52c480ea17dc9dfb9ea0101f7275657245776a548d3cc8511a7af).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by sparkitect** [comment]
@andrewconnell I'm assuming you meant I should update the ms.date, though I previously assumed you were leaving a note for the person doing final approval/merge. I will remember update the ms.date in future PRs for this repo...

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
