### PR TITLE
Re-update article "Use an Office 365 SharePoint site to authorize provider-hosted add-ins on an on-premises SharePoint site"

### PR DESCRIPTION
**Pull request by Yvand**
#### Category
- [X] Content fix
- [ ] New article

#### Related issues:

- https://github.com/SharePoint/sp-dev-docs/pull/4199

#### What's in this Pull Request?

This is the follow-up of PR https://github.com/SharePoint/sp-dev-docs/pull/4199, to re-apply some of the changes on [this article](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on) that were lost when PR was merged.

The specific changes I re-submit in this PR are:

- Remove unnecessary prerequisites
- Remove the replacement of the SharePoint STS certificate, unnecessary

I tested and validated all my changes on 2 separate environments, both provisioned using [this template](https://azure.microsoft.com/en-us/resources/templates/sharepoint-adfs/):

- a SharePoint 2013 farm (Windows Server 2012 R2)
- a SharePoint 2019 farm (Windows Server 2016)

### CODE REVIEW

**Comment by Yvand** [comment]
@VesaJuvonen Can you please check this PR? Currently the article https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on is in a pretty bad shape as it contains only half of the changes in my previous PR. It makes it very inconsistent.
This PR resolves this.

**Comment by Yvand** [comment]
@VesaJuvonen this PR really needs your attention, article https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on needs to be updated to fix the inconsistencies introduced with the previous PR

**Comment by Yvand** [comment]
@Meenal9936 can you please help get this PR merged as soon as possible?
It is a shame we leave [this article](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on) in such a bad state for so long, it was updated with some of the changes from previous PR #4199, but not all, which makes it very inconsistent.

**Comment by andrewconnell** [comment]
@Yvand Sorry for the delay... can you please update the PR to address conflicts? Once that's done, we can review for merge.

**Comment by Yvand** [comment]
@andrewconnell thank you for jumping in, I just fixed the conflict

**Pull request merged**
