### PR TITLE
Update modern-experience-customizations-provisioning-sites.md

### PR DESCRIPTION
**Pull request by expiscornovus**
| Q                   | A
| ---------------     | ---
| content fix?        |  yes
| New article?        | no
| Related issues?     | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

In the latest versions of PnP PowerShell you have the New-PnPSite cmdlet to create Modern Team sites or Communication sites. So Powershell script can be a lot shorter. I have test it with PnP PowerShell online module version 2.21.1712.2.

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'master' branch. Released documents are in live branch.*

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/expiscornovus/sp-dev-docs/blob/patch-1/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C12%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201712141226393562-1148%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=dXJVc%2BqIKUBj559sQ1Ua1POPGY4JARAYJvUK00sEz1w%3D&st=2017-12-14T12%3A22%3A38Z&se=2018-01-14T12%3A27%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/expiscornovus/sp-dev-docs/blob/patch-1/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C5%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801051433201122-1148%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=5FrscRGlKmJgaBCuGvD2XBG5zELo%2FVZCS9Navaxphu4%3D&st=2018-01-05T14%3A29%3A15Z&se=2018-02-05T14%3A34%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx Dennis, appreciated.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/expiscornovus/sp-dev-docs/blob/patch-1/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C1%5C5%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201801051433540537-1148%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nwrxTrWA7uKSzm2eXwZX0Zj77B3xf8aJNBni18jlAWo%3D&st=2018-01-05T14%3A30%3A58Z&se=2018-02-05T14%3A35%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
