### PR TITLE
Validation: fix table spacing

### PR DESCRIPTION
**Pull request by LSchaufMS**
## Category

- [x] Content fix

## Related issues

- no issue numbers; changes are part of the Validation cleanup efforts. 

## What's in this Pull Request?

This PR fixes 1 issue in 1 file.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[d51f1b5](https://github.com/LSchaufMS/sp-dev-docs/commits/d51f1b5c46ec05bf84f504d6a75794108eaf8b92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/semantic_slots.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/design/semantic_slots.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-8208) | [Details](#user-content-9b4c957a02678e16dcd221c8c130d087-af490a2e)

<a id="9b4c957a02678e16dcd221c8c130d087-af490a2e"></a>
### [docs/design/semantic_slots.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/design/semantic_slots.md)
 - **Line 32, Column 3**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206171419182832-8208/BuildReport?accessString=f16aa00ac8efc1c9fa51c3ba9452c532231a4f16c67a41e6c54c2d9ab3f74c48).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[ff6c87b](https://github.com/LSchaufMS/sp-dev-docs/commits/ff6c87b8865d241b26b1150d923899cb21c95854)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/semantic_slots.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/design/semantic_slots.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-8208) | [Details](#user-content-9b4c957a02678e16dcd221c8c130d087-2caab6ee)

<a id="9b4c957a02678e16dcd221c8c130d087-2caab6ee"></a>
### [docs/design/semantic_slots.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/design/semantic_slots.md)
 - **Line 32, Column 3**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206171421264289-8208/BuildReport?accessString=5526af423c2bb94717a5ab24bc9ee92f557ae4f406028503ad8c7c8c62e3c3b8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by LSchaufMS** [comment]
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

**Comment by andrewconnell** [comment]
This change doesn't have any impact on the content, but makes the source content header to read. IOW, this isn't necessary.

**Pull request closed without merging**
