### PR TITLE
Add steps to get flow ID for solution-aware flows

### PR DESCRIPTION
**Pull request by Steven-Jia**
## Category

- [X] Content fix
- [ ] New article

## What's in this Pull Request?

Added steps for makers to grab the ID of solution-aware flows so that these types of instant flows can also be run from a column-formatted button in lists.

### CODE REVIEW

**Comment by Steven-Jia** [comment]
@andrewconnell this doc change will help address an urgent customer ask. If reviewing and merging this could be prioritized, I'd appreciate it. Thanks!

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
Please see the edits I made for future doc updates @Steven-Jia ... thanks!

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[49be9e1](https://github.com/Steven-Jia/sp-dev-docs-edits/commits/49be9e100efb6285652ad6d1032c41cb4555d182)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/Steven-Jia/sp-dev-docs-edits/blob/patch-5/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7511) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111161113144041-7511%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T11%3A14%3A21Z&sr=b&sp=r&sig=0%2F7ZVtDwqJUnYE9rtTBM%2FvuzGZSmzHMw4fYLpEMzsFs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Steven-Jia** [comment]
@andrewconnell thank you!

**Pull request merged**
