### PR TITLE
Content fixup for garbled rendering (fixes 3099)

### LINKED ISSUE #3099: Garbled code snippet in documentation on replacing client secrets
#### Category
- [ ] Question
- [X] Typo
- [ ] Bug
- [ ] Additional article idea

#### Observed Behavior

The [Replace an expiring client secret in a SharePoint Add-in](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in) page contains a garbled code snippet in item 3 of the second section. There are two lines that are shown as unformatted text, outside of any code box, the code is split across multiple code boxes, and the last code box extends beyond the end of the code, consuming the next bullet and header.

Screenshot:
image

I would try submitting a change to fix this, but given that this appears to be due to an issue in the way docs.microsoft.com renders the markdown, I'm not sure whether the issue is occuring due to the lack of leading indentation (other code on the page is indented by 4 spaces while this snippet has no indent), or whether it is due to the empty lines in the code. Since I don't have any way of verifying that any change I made would fix the formatting issue, I am submitting this as an Issue instead.

### PR DESCRIPTION
**Pull request by andrewconnell**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #3099

#### What's in this Pull Request?

Fixup code formatting to address garbled rendering.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b3af25](https://github.com/andrewconnell/sp-dev-docs/pull/3133/commits/0b3af2596f2a368ca700a4420127a345d99291f4)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b3af25](https://github.com/andrewconnell/sp-dev-docs/pull/3133/commits/0b3af2596f2a368ca700a4420127a345d99291f4)_: 

:clock10: **Full build**: average full build time is not available, there is no data for this repository.

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b3af25](https://github.com/andrewconnell/sp-dev-docs/pull/3133/commits/0b3af2596f2a368ca700a4420127a345d99291f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/andrewconnell/sp-dev-docs/blob/contentfixup-issue3099/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-3133) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C18%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812181111200744-3133%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ekW%2FXTEjZQDaJStuROip2QnGClYhhXW3ay4w19d0iTI%3D&st=2018-12-18T11%3A09%3A32Z&se=2019-01-18T11%3A14%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx AC, appreciated.

**Pull request merged**
