### PR TITLE
Create migration-isv-guidance

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
New article providing SP migration guidance targeted at ISVs.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx @JoanneHendrickson, getting these live now.

**Comment by JoanneHendrickson** [comment]
Hi @VesaJuvonen -- this still isn't live -- 

https://docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance

**Comment by VesaJuvonen** [comment]
There is no such file at https://github.com/SharePoint/sp-dev-docs/tree/master/docs/apis, so it's definitely not live. Seems that in your own fork, you had created it to the root, which is not the right location - https://github.com/JoanneHendrickson/sp-dev-docs/blob/1ae4fab37d63acad7a756a602bbd2b4cf6a4d1f7/migration-isv-guidance

That's why the URL is not working.

**Comment by JoanneHendrickson** [comment]
ok,  I have created it in the correct location and submitted a PR. Will delete the one in the root.

**Pull request merged**
