### PR TITLE
Support setValue and inlineEditField 

### PR DESCRIPTION
**Pull request by shagra-ms**
## Category

- [x] Content fix
- [ ] New article

## Related issues
New feature

## What's in this Pull Request?
This pull request documents 2 new actions in formatters - 
1. `setValue` `customRowAction` 
2. inlineEditField property

This also covers new operators and styles -
1. `--inline-editor-border-width`
2. `--inline-editor-border-style`
3. `--inline-editor-border-radius`
4. `--inline-editor-border-color`
5. `addDays`
6. `addMinutes`
7. `appendTo`
8. `removeFrom`

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[55a222c](https://github.com/shagra-ms/sp-dev-docs/commits/55a222c71a662ece76e4a1c96581373ff4468a29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-advanced.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) | [Details](#user-content-3cf248c58afb55a55ea832080f4a6eb3-ad2d4756)
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7495) |
[docs/images/sp-columnformatting-inline-editing.gif](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/images/sp-columnformatting-inline-editing.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |

<a id="3cf248c58afb55a55ea832080f4a6eb3-ad2d4756"></a>
### [docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-advanced.md)
 - **Line 324, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './formatting-syntax-reference'.`````
 - **Line 331, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './formatting-syntax-reference'.`````
 - **Line 335, Column 7**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './formatting-syntax-reference'.`````
 - **Line 336, Column 64**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './formatting-syntax-reference'.`````
 - **Line 343, Column 10**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './formatting-syntax-reference'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111111857101044-7495%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T18%3A58%3A29Z&sr=b&sp=r&sig=Lr3F55ZF14CkJm0AJRKrqp5xSDBCSmJXYY9bZ2TDBzs%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[362d3c8](https://github.com/shagra-ms/sp-dev-docs/commits/362d3c831fab2ce48361f3c92527e6aa7f2c0db1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7495) |
[docs/images/sp-columnformatting-inline-editing.gif](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/images/sp-columnformatting-inline-editing.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111111901459560-7495%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T19%3A03%3A05Z&sr=b&sp=r&sig=5Ht7oUn2gEEjG%2Bicqy2jRxqKx%2FS2JOhmsXMUHJw%2FeL8%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a2d1e41](https://github.com/shagra-ms/sp-dev-docs/commits/a2d1e411b263fe8336427247353de4bf957cce71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7495) |
[docs/images/sp-columnformatting-inline-editing.gif](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/images/sp-columnformatting-inline-editing.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111111904011282-7495%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T19%3A05%3A08Z&sr=b&sp=r&sig=bFn4hh0tqtpcOX4UjkJINB3x4P%2BUsblSgJ%2F1f6FESqc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[5174219](https://github.com/shagra-ms/sp-dev-docs/commits/517421904c84e1faa1a92ca13109a3c6f87dd35d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-80a232a9)

<a id="80a232a9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111161338163799-7495%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T13%3A38%3A46Z&sr=b&sp=r&sig=Rm8sx3C8S%2F%2BybDhxXhq6kqnBFSAKYUqdCIjnI73YaSU%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[c8f2da3](https://github.com/shagra-ms/sp-dev-docs/commits/c8f2da3d1a6ba89e5cec5a043083fd2d55359b7a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7495) |
[docs/images/sp-columnformatting-inline-editing.gif](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-edit-actions/docs/images/sp-columnformatting-inline-editing.gif) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7495) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111161406018613-7495%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T14%3A07%3A34Z&sr=b&sp=r&sig=WSrAkEv0wY9SJdpIQzPRSbo8GwUhq4A50JbtHkvCkj4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by shagra-ms** [comment]
@andrewconnell Thanks!

**Pull request merged**
