### PR TITLE
Correct the package content folder path.

### PR DESCRIPTION
**Pull request by lijunle**
#### Category
- [x] Content fix
- [ ] New article
- [ ] Related issues: fixes #X, partially #Y, mentioned in #Z

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[8eacd46](https://github.com/lijunle/sp-dev-docs/pull/3209/commits/8eacd46aadd3d7f6c8c07e943c4020c431c5eb35)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[8eacd46](https://github.com/lijunle/sp-dev-docs/pull/3209/commits/8eacd46aadd3d7f6c8c07e943c4020c431c5eb35)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[8eacd46](https://github.com/lijunle/sp-dev-docs/pull/3209/commits/8eacd46aadd3d7f6c8c07e943c4020c431c5eb35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md](https://github.com/lijunle/sp-dev-docs/blob/patch-1/docs/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/serve-your-web-part-in-a-sharepoint-page?branch=pr-en-us-3209) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C5%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901050845360138-3209%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=7428XyxaN1tpWUteXNcx8zlZpmPPq9KycmxVxFZTgcs%3D&st=2019-01-05T08%3A42%3A28Z&se=2019-02-05T08%3A47%3A28Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thx @lijunle, appreciated.

**Pull request merged**
