### PR TITLE
Fix the Typo - Update modernize-userinterface-site-pages-dotnet.md

### PR DESCRIPTION
**Pull request by PrasadKasireddy**
## Category

- [X] Content fix

## What's in this Pull Request?

> Fix the Typo error (turned off)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[bbebf3c](https://github.com/PrasadKasireddy/sp-dev-docs/commits/bbebf3c09c0929b3dc28f2a0c0c0bb9adb1cc79b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/transform/modernize-userinterface-site-pages-dotnet.md](https://github.com/PrasadKasireddy/sp-dev-docs/blob/PrasadKasireddy-patch-1/docs/transform/modernize-userinterface-site-pages-dotnet.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-dotnet?branch=pr-en-us-7157) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C7%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202107071604098417-7157%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-06T07%3A59%3A36Z&ske=2021-07-13T08%3A04%3A36Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-07T16%3A00%3A18Z&se=2021-08-07T16%3A05%3A18Z&sr=b&sp=r&sig=5BiOXKladnUGmKugGvZZi8Lt3EK218ESegpX6JubOWA%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
dupe... already fixed in another pr

**Comment by PrasadKasireddy** [comment]
@andrewconnell - Both PR are fixing same typo but different pages.
https://github.com/SharePoint/sp-dev-docs/pull/7156 - has fixed - docs/transform/modernize-userinterface-site-pages-powershell.md

image


My PR https://github.com/SharePoint/sp-dev-docs/pull/7157 has fixed  page docs/transform/modernize-userinterface-site-pages-dotnet.md

image

**Comment by PrasadKasireddy** [comment]
> @andrewconnell - Both PR are fixing same typo but different pages.
> #7156 - has fixed - docs/transform/modernize-userinterface-site-pages-powershell.md
> 
> image
> 
> My PR #7157 has fixed page docs/transform/modernize-userinterface-site-pages-dotnet.md
> 
> image

@andrewconnell , please confirm on this

**Pull request closed without merging**
