### PR TITLE
Fixed link to Throttling code sample on GitHub

### PR DESCRIPTION
**Pull request by ganesh-sanap**
## Category

- [x] Content fix

## What's in this Pull Request?

Fixed link to "GitHub: SharePoint Online Throttling code sample" in "See also" section.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[f19d972](https://github.com/ganesh-sanap/sp-dev-docs/commits/f19d97266992ef2745cfea198c286a05f40f861b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-5/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online?branch=pr-en-us-6582) | [Details](#user-content-014dcfe0-20687671)

<a id="014dcfe0-20687671"></a>
### [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-5/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202012280834290932-6582%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zL86utguRNHpukruE1KuNdZzTpyARX4uMW27Sf%2FqabU%3D&st=2020-12-28T08%3A30%3A47Z&se=2021-01-28T08%3A35%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
While the link is fixed, this should remove the link, not point to a now-removed sample. Can you please update this to remove the link to the sample as it's no longer there?

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[81e3633](https://github.com/ganesh-sanap/sp-dev-docs/commits/81e36335dea5c4ee0a3836083159fa1aa2778e66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-5/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online?branch=pr-en-us-6582) | [Details](#user-content-014dcfe0-e1f36694)

<a id="014dcfe0-e1f36694"></a>
### [docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-5/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C29%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202012291324003650-6582%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xsm1PENScanpUn63NBLEYLHvA9CK41aGBrnaYINOUFw%3D&st=2020-12-29T13%3A20%3A04Z&se=2021-01-29T13%3A25%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ganesh-sanap** [comment]
@andrewconnell Removed link to GitHub code sample, please review.

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[eaed4e0](https://github.com/ganesh-sanap/sp-dev-docs/commits/eaed4e074d952366e26a9a040b469a6ff569aaf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-5/docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online?branch=pr-en-us-6582) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C29%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202012291358186076-6582%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nWs%2FafQVezDOsTSPsMxT36z4skoIGET6zBnxEGsdTWs%3D&st=2020-12-29T13%3A54%3A14Z&se=2021-01-29T13%3A59%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
