### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Removing these lines 35 - 40:

- Create Office Add-Ins using SPFx web parts (dev preview)
  - [Docs: Create Outlook add-ins using SharePoint Framework](office-addins-create.md)
  - [Tutorial: Create Outlook Web Access extension using SharePoint Framework](web-parts/get-started/office-addins-tutorial.md)

    > [!NOTE]
    > The Outlook Web Access support is being currently rolled out and can take until end of the release week (10th of January), before it's fully functional in your tenant

Note: The redirects aren't working, and the target content is hard to find. Asking the author for additional information

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[eff109a](https://github.com/DhurataJ/sp-dev-docs/commits/eff109a78580e3a7eb6919fdb3f8c9e24d538734)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/release-1.10.0.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-6/docs/spfx/release-1.10.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.10.0?branch=pr-en-us-7858) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204042235105158-7858%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T22%3A36%3A58Z&sr=b&sp=r&sig=77XvVceQi41I3FJfR7IFO0hhqD6RT%2BOMzal%2FR3ultTw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by DhurataJ** [comment]
**Global effort to fix broken links**

Hi @VesaJuvonen,

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. In this case of PR, I deleted lines from 35 - 40, the redirects aren't working, and the target content is hard to find. 

Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Comment by andrewconnell** [comment]
@DhurataJ - thanks, but you don't have to @mention me for future PR's. I review all PRs on this repo on a scheduled basis.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a40e166](https://github.com/DhurataJ/sp-dev-docs/commits/a40e166b4c036060684b54fe5c5a3478d0fa8897)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/release-1.10.0.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-6/docs/spfx/release-1.10.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.10.0?branch=pr-en-us-7858) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204061759100790-7858%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T18%3A00%3A40Z&sr=b&sp=r&sig=NNk35VvtDfG3Hm0NSHbm%2BpVMKVqg17u9rN%2BrzorGhdo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
