### PR TITLE
Adding Accessibility topic.

### PR DESCRIPTION
**Pull request by Lauragra**
| Q                   | A
| ---------------     | ---
| content fix?        | no - yes?
| New article?        | no - yes?
| Related issues?     | fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?

Please describe the changes in this PR. Sample description or details around bugs which are being fixed.

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'master' branch. Released documents are in live branch.*

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\vfri-s, target branch: master, target branch commit: 07fbc37901391567161094178c80891bf32f0656, source branch: 75f7f6630b6d10654d80f3ef2c76ecbe/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711142343019329-1051%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=D9t7H8IUDEmjp%2BFtL7lgvqLcGAHC%2Br%2BzGx%2FfVtMjHcE%3D&st=2017-11-14T23%3A38%3A38Z&se=2017-12-15T23%3A43%3A38Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\outk-s, target branch: master, target branch commit: 07fbc37901391567161094178c80891bf32f0656, source branch: 75f7f6630b6d10654d80f3ef2c76ecbe/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711150026071485-1051%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=umkZqDyskZMBxYxVUtSACwKc8YqA8G58RT3%2BvBR3ZyU%3D&st=2017-11-15T00%3A22%3A41Z&se=2017-12-16T00%3A27%3A41Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/accessibility.md](https://github.com/Lauragra/sp-dev-docs/blob/master/docs/design/accessibility.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/Lauragra/sp-dev-docs/blob/master/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711150041250159-1051%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=zi92CRSFa5jZIUGpm8cb8stowrU%2FT7LB3%2Fil72MxrAU%3D&st=2017-11-15T00%3A38%3A44Z&se=2017-12-16T00%3A43%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\t2at-s, target branch: master, target branch commit: 07fbc37901391567161094178c80891bf32f0656, source branch: 75f7f6630b6d10654d80f3ef2c76ecbe/master, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711150044501049-1051%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vxDNzBBuXMz2Q2mmPUKAk2jZE%2BY2xv7p%2BnVpidEBk1M%3D&st=2017-11-15T00%3A40%3A50Z&se=2017-12-16T00%3A45%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit 16bb47901b5126c234ed68d02110597c35bfb497 in branch master of repository https://github.com/Lauragra/sp-dev-docs into branch master (commit 07fbc37901391567161094178c80891bf32f0656)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711150109380928-1051%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=t8Jr17Rd3ng8wsojC6XzUInSPQQlCmvdHrPd19Vl4i0%3D&st=2017-11-15T01%3A05%3A30Z&se=2017-12-16T01%3A10%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/accessibility.md](https://github.com/Lauragra/sp-dev-docs/blob/master/docs/design/accessibility.md) | :white_check_mark:Succeeded | |
[docs/toc.yml](https://github.com/Lauragra/sp-dev-docs/blob/master/docs/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C15%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711150112261711-1051%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PROZfdVeZLWcUmIidQ4jTnqVz%2FPnaAtVpQtXLX2Q7Bo%3D&st=2017-11-15T01%3A09%3A32Z&se=2017-12-16T01%3A14%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by davidchesnut** [comment]
Looks good!

**Pull request merged**
