### PR TITLE
Formatting docs update - April 2024

### PR DESCRIPTION
**Pull request by arkogupta**
## Category

- [X] Content fix

## What's in this Pull Request?

Update custom formatter doc to add details about the new embed action.

You can embed maps - 
image

Even youtube videos - 

image

And much more...! 😄

### CODE REVIEW

**Review by andrewconnell — APPROVED** [review]
This doc is in bad need of a content review... tons of spelling & grammar errors.

**Comment by arkogupta** [comment]
@VesaJuvonen Could you please take a look?

**Comment by arkogupta** [comment]
@andrewconnell Thanks for reviewing and merging. What's the process/timeline for these changes to reflect in [](https://learn.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference) ?

**Comment by andrewconnell** [comment]
Refreshes to the live site usually happen on a weekly basis... that's handled by @VesaJuvonen (I can't publish directly to live being an external)... if you need it to get pushed sooner, I'd suggest contacting him via Teams.

**Comment by arkogupta** [comment]
Got it. Thanks  Andrew!

**Pull request merged**
