### PR TITLE
Continued edit pass on Solutions guidance docs

### PR DESCRIPTION
**Pull request by Linda-Editor**

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/community/open-source-projects.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-1835) |
[docs/declarative-customization/site-design-pnp-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/declarative-customization/site-design-pnp-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnp-provisioning?branch=pr-en-us-1835) |
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-1835) |
[docs/general-development/how-to-work-with-user-profiles-and-organization-profiles-by-using-the-server-obj.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/how-to-work-with-user-profiles-and-organization-profiles-by-using-the-server-obj.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-work-with-user-profiles-and-organization-profiles-by-using-the-server-obj?branch=pr-en-us-1835) |
[docs/general-development/incoming-claims-signing-into-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/incoming-claims-signing-into-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/incoming-claims-signing-into-sharepoint?branch=pr-en-us-1835) |
[docs/general-development/overview-of-the-sharepoint-mobile-client-authentication-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/overview-of-the-sharepoint-mobile-client-authentication-object-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/overview-of-the-sharepoint-mobile-client-authentication-object-model?branch=pr-en-us-1835) |
[docs/general-development/set-up-a-general-development-environment-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/set-up-a-general-development-environment-for-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/set-up-a-general-development-environment-for-sharepoint?branch=pr-en-us-1835) |
[docs/general-development/use-feature-upgrade-to-apply-new-sharepoint-master-pages-when-upgrading-fro.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/use-feature-upgrade-to-apply-new-sharepoint-master-pages-when-upgrading-fro.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/use-feature-upgrade-to-apply-new-sharepoint-master-pages-when-upgrading-fro?branch=pr-en-us-1835) |
[docs/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint?branch=pr-en-us-1835) |
[docs/scenario-guidance/Long-running-scheduled-operations.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/scenario-guidance/Long-running-scheduled-operations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/long-running-scheduled-operations?branch=pr-en-us-1835) |
[docs/scenario-guidance/Transformation.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/scenario-guidance/Transformation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/transformation?branch=pr-en-us-1835) |
[docs/schema/client-web-part-definition-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/schema/client-web-part-definition-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/client-web-part-definition-schema?branch=pr-en-us-1835) |
[docs/solution-guidance/Autotagging-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Autotagging-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/autotagging-sample-app-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Branding-and-site-provisioning-solutions-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/branding-and-site-provisioning-solutions-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/bulk-user-profile-update-api-for-sharepoint-online?branch=pr-en-us-1835) |
[docs/solution-guidance/Configure-O365Api-Project-For-Distribution.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Configure-O365Api-Project-For-Distribution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configure-o365api-project-for-distribution?branch=pr-en-us-1835) |
[docs/solution-guidance/Configure-SP-Provider-Hosted-Apps-For-Distribution.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Configure-SP-Provider-Hosted-Apps-For-Distribution.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configure-sp-provider-hosted-apps-for-distribution?branch=pr-en-us-1835) |
[docs/solution-guidance/Data-storage-options-in-SharePoint-Online.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Data-storage-options-in-SharePoint-Online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/data-storage-options-in-sharepoint-online?branch=pr-en-us-1835) |
[docs/solution-guidance/Getting-Started-with-building-Azure-WebJobs-for-your-Office365-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Getting-Started-with-building-Azure-WebJobs-for-your-Office365-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/getting-started-with-building-azure-webjobs-for-your-office365-sites?branch=pr-en-us-1835) |
[docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/introducing-the-pnp-provisioning-engine?branch=pr-en-us-1835) |
[docs/solution-guidance/Migrate-user-profile-properties-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Migrate-user-profile-properties-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/migrate-user-profile-properties-sample-app-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/Move-O365Api-Project-from-Dev-To-Prod.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Move-O365Api-Project-from-Dev-To-Prod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/move-o365api-project-from-dev-to-prod?branch=pr-en-us-1835) |
[docs/solution-guidance/Personalize-search-results-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Personalize-search-results-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/personalize-search-results-sample-app-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/Read-or-update-user-profile-properties-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Read-or-update-user-profile-properties-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/read-or-update-user-profile-properties-sample-app-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-Event-Receivers.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-Event-Receivers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance-event-receivers?branch=pr-en-us-1835) |
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-Feature-Receivers.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-Feature-Receivers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance-feature-receivers?branch=pr-en-us-1835) |
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-InfoPath.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-InfoPath.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance-infopath?branch=pr-en-us-1835) |
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-WebParts.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-WebParts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance-webparts?branch=pr-en-us-1835) |
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-1835) |
[docs/solution-guidance/Transform-farm-solutions-to-the-SharePoint-app-model.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Transform-farm-solutions-to-the-SharePoint-app-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/transform-farm-solutions-to-the-sharepoint-app-model?branch=pr-en-us-1835) |
[docs/solution-guidance/Upload-user-profile-pictures-sample-app-for-SharePoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Upload-user-profile-pictures-sample-app-for-SharePoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-user-profile-pictures-sample-app-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/Use-Microsoft-Azure-WebJobs-with-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/Use-Microsoft-Azure-WebJobs-with-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-microsoft-azure-webjobs-with-office-365?branch=pr-en-us-1835) |
[docs/solution-guidance/app-only-elevated-privileges-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/app-only-elevated-privileges-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/app-only-elevated-privileges-sharepoint-add-in?branch=pr-en-us-1835) |
[docs/solution-guidance/create-remote-timer-jobs-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/create-remote-timer-jobs-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/create-remote-timer-jobs-in-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/deploying-your-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/deploying-your-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/deploying-your-sharepoint-add-ins?branch=pr-en-us-1835) |
[docs/solution-guidance/enterprise-content-management-solutions-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/enterprise-content-management-solutions-for-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/enterprise-content-management-solutions-for-sharepoint?branch=pr-en-us-1835) |
[docs/solution-guidance/javascript-patterns-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/javascript-patterns-and-performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/javascript-patterns-and-performance?branch=pr-en-us-1835) |
[docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-lists-and-libraries?branch=pr-en-us-1835) |
[docs/solution-guidance/modern-experience-customizations-customize-pages.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/modern-experience-customizations-customize-pages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-pages?branch=pr-en-us-1835) |
[docs/solution-guidance/modern-experience-customizations-customize-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/modern-experience-customizations-customize-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-customize-sites?branch=pr-en-us-1835) |
[docs/solution-guidance/modern-experience-customizations-provisioning-sites.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/modern-experience-customizations-provisioning-sites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations-provisioning-sites?branch=pr-en-us-1835) |
[docs/solution-guidance/modern-experience-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/modern-experience-customizations.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-customizations?branch=pr-en-us-1835) |
[docs/solution-guidance/modern-experience-site-classification.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/modern-experience-site-classification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/modern-experience-site-classification?branch=pr-en-us-1835) |
[docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-engine-and-the-core-library?branch=pr-en-us-1835) |
[docs/solution-guidance/pnp-provisioning-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/pnp-provisioning-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-framework?branch=pr-en-us-1835) |
[docs/solution-guidance/pnp-provisioning-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/pnp-provisioning-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-provisioning-schema?branch=pr-en-us-1835) |
[docs/solution-guidance/pnp-remote-provisioning.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/pnp-remote-provisioning.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-provisioning?branch=pr-en-us-1835) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-1835) |
[docs/solution-guidance/provisioning-console-application-sample.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/provisioning-console-application-sample.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/provisioning-console-application-sample?branch=pr-en-us-1835) |
[docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md](https://github.com/SharePoint/sp-dev-docs/blob/linda-solutions-4/docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/query-sharepoint-change-log-with-changequery-and-changetoken?branch=pr-en-us-1835) |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C11%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201805110103276638-1835%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0LDFpmduq1all%2Beg%2Fc5ni0AaiV5yBp0249sK08ZJxKg%3D&st=2018-05-11T01%3A00%3A39Z&se=2018-06-11T01%3A05%3A39Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
@VesaJuvonen  Please push these to live when you have time. Thanks!

**Comment by VesaJuvonen** [comment]
Thx @Linda-Editor merged now.

**Comment by Linda-Editor** [comment]
Thanks!! 😊

Sent from my Windows Phone
________________________________

**Pull request merged**
