### PR TITLE
Update debug-modern-pages.md

### PR DESCRIPTION
**Pull request by russgove**
documented debugging webparts by comiling without the --ship parameter

#### Category
- [ ] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/debug-modern-pages.md](https://github.com/russgove/sp-dev-docs/blob/patch-3/docs/spfx/debug-modern-pages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages?branch=pr-en-us-1720) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C4%5C20%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201804202314032049-1720%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CoCiCjnFUZ7fiCSVAgSg5OKnfJWvytDokLNFytlZC1o%3D&st=2018-04-20T23%3A11%3A56Z&se=2018-05-21T23%3A16%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[53682dd](https://github.com/russgove/sp-dev-docs/pull/1720/commits/53682ddfec3b2f17550eb31724a16d23a6a40aa0)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by VesaJuvonen** [comment]
Small adjustments... but in general good to go. Thx @russgove and sorry for the massive delay for processing this one.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[53682dd](https://github.com/russgove/sp-dev-docs/pull/1720/commits/53682ddfec3b2f17550eb31724a16d23a6a40aa0)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[53682dd](https://github.com/russgove/sp-dev-docs/pull/1720/commits/53682ddfec3b2f17550eb31724a16d23a6a40aa0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/debug-modern-pages.md](https://github.com/russgove/sp-dev-docs/blob/patch-3/docs/spfx/debug-modern-pages.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-modern-pages?branch=pr-en-us-1720) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812281634041633-1720%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=QySQ8tj50DPnJLhSM%2BtPKtLb8XOVhvbIXTAjVOlDJ3I%3D&st=2018-12-28T16%3A30%3A55Z&se=2019-01-28T16%3A35%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
