### PR TITLE
Update site-design-pnppowershell.md

### PR DESCRIPTION
**Pull request by KoenZomers**
## Category

- [X] Content fix
- [ ] New article

## Related issues
N/A

## What's in this Pull Request?

Updating sample to use the new PnP PowerShell instead of the old one

### CODE REVIEW

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[d61467c](https://github.com/KoenZomers/sp-dev-docs/commits/d61467c78a34aac9a51ef35b381ae43fe27e69ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/KoenZomers/sp-dev-docs/blob/patch-35/docs/declarative-customization/site-design-pnppowershell.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-6784) | [Details](#user-content-c53649a4-a53f8997)

<a id="c53649a4-a53f8997"></a>
### [docs/declarative-customization/site-design-pnppowershell.md](https://github.com/KoenZomers/sp-dev-docs/blob/patch-35/docs/declarative-customization/site-design-pnppowershell.md)
 - **Line 36, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Add-PnPSiteDesign?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 37, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Add-PnPSiteDesignTask?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 38, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Add-PnPSiteScript?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 39, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Add-PnPSiteScriptPackage?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 40, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteDesign?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 41, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteDesignRights?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 42, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteDesignRun?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 43, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteDesignRunStatus?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 44, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteDesignTask?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 45, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteScript?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 46, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteScriptFromList?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 47, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Get-PnPSiteScriptFromWeb?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 48, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Grant-PnPSiteDesignRights?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 49, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Invoke-PnPSiteDesign?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 50, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Remove-PnPSiteDesign?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 51, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Remove-PnPSiteDesignTask?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 52, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Remove-PnPSiteScript?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 53, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Revoke-PnPSiteDesignRights?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 54, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Set-PnPSiteDesign?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 55, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Set-PnPSiteScript?view=sharepoint-ps. Otherwise, remove the view parameter.`````
 - **Line 56, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/Set-PnPSiteScriptPackage?view=sharepoint-ps. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202103092227588402-6784%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l1EFYYAFNW61wX%2Biu2HtZ3R6THMIuFuXp75xMRTms28%3D&st=2021-03-09T22%3A24%3A17Z&se=2021-04-09T22%3A29%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Any chance you can edit the links in this doc to not point to a specific view of the page per the suggestion in the build report? That should have been triggered and generated when you initially submitted the PR, but something seems to have. broken down in the automation process.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[eaabc75](https://github.com/KoenZomers/sp-dev-docs/commits/eaabc755fe459e442653cf0730b3daabbc16bb24)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/KoenZomers/sp-dev-docs/blob/patch-35/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-6784) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202103110836537085-6784%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kwkS2crjeVjH6%2FzW8sPK0hGgeOpQc4nIxTkNXh%2FDm%2BY%3D&st=2021-03-11T08%3A33%3A22Z&se=2021-04-11T08%3A38%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by KoenZomers — COMMENTED** [review]
Applied changes as requested

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
