### PR TITLE
Updated export of ServicePrincipalCredentials

### PR DESCRIPTION
**Pull request by arjancornelissen**
Updated the PowerShell script for exporting ServicePrincipalCredentials more readable so it is clear to the reader what it is doing.
Also used an object and exported it to CSV instead of a text file

## Category

- [X] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[cb94f8e](https://github.com/arjancornelissen/sp-dev-docs/commits/cb94f8e183f4165098e41038bcd8a88aa21a54cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/arjancornelissen/sp-dev-docs/blob/patch-1/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-7875) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204081210338056-7875%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-09T12%3A11%3A50Z&sr=b&sp=r&sig=Z9cq5Ow%2BOwU1drD32WwhUGiTyBYmHqphX1qy3cV%2BGsI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]
Thanks... in the future please update the doc's frontmatter timestamp (`MM/DD/YYYY`) to indicate went the doc was last updated.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[21e0c64](https://github.com/arjancornelissen/sp-dev-docs/commits/21e0c643071ef2833ba8eb02d10f78f4511f77fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/arjancornelissen/sp-dev-docs/blob/patch-1/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-7875) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C12%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204121110377754-7875%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-13T11%3A11%3A59Z&sr=b&sp=r&sig=lDsOsdV51g4uFJ6hXv2c%2BlDvy1pOCAlbII%2FYUkU6MnQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by arjancornelissen** [comment]
> Thanks... in the future please update the doc's frontmatter timestamp (`MM/DD/YYYY`) to indicate went the doc was last updated.

Will do that next time

**Pull request merged**
