### PR TITLE
Formatting documentation fixes

### PR DESCRIPTION
**Pull request by shagra-ms**
## Category

- [x] Content fix
- [ ] New article

## Related issues

- Minor updates to documentation that covers the recent fixes in formatter

## What's in this Pull Request?

The pull request covers the following -
1. Support replace operator for multi choice and multi user fields
2. Approval Status fields now support numeric as well as text comparisons
3. Allow setting empty value for user and date fields

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[75bbbb6](https://github.com/shagra-ms/sp-dev-docs/commits/75bbbb64b2e054110d97af2fbe8d696f029c2df3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7627) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7627) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202201041441583789-7627%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T14%3A43%3A44Z&sr=b&sp=r&sig=QJbDucV9e9KsTTyfb1oZ6rlqsPQ%2F6hc6ZdMncuyzPis%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[88bebb6](https://github.com/shagra-ms/sp-dev-docs/commits/88bebb6b4e47594133d38c6f0f075ab3a29de80d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7627) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7627) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202201041444437836-7627%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-04T14%3A46%3A51Z&sr=b&sp=r&sig=Ry6LNLhPcwdE%2FjQ3Zi3ksg%2F1FrQ3WMBb1I8pdELUZMY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a977022](https://github.com/shagra-ms/sp-dev-docs/commits/a97702246cb9df74769d6212020c473b9442d526)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7627) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7627) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202201062036358635-7627%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T20%3A37%3A59Z&sr=b&sp=r&sig=3He14TXAUqIeF0c9rZo8NgVlLbh9xDASk72MSGr6M5g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[0d68074](https://github.com/shagra-ms/sp-dev-docs/commits/0d680748de05cb798bd54b5677b356e0ac0e4643)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/formatting-advanced.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-advanced.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-advanced?branch=pr-en-us-7627) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagra/docs-update-01-2021/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-7627) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202201062037360099-7627%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-06T20%3A39%3A25Z&sr=b&sp=r&sig=PJUL%2FHXOeC%2BDmfRHUApVDyH6krOSBFHb8s%2Fx0%2BjY73w%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by shagra-ms** [comment]
Thanks @andrewconnell !

**Pull request merged**
