### PR TITLE
Update onenote-migration-service.md

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
content update/fix:

updated text, added back in section with diagram.  uploaded diagram separately. update TOC separately.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Diagram is still missing and should be located in the images folder at the root of the the document set. Obviously the best option is to submit PRs which are full edits containing all the referenced assets. This does require using GitHub tooling and forks as that's how the images work. More than happy to help with the guidance and tooling, if needed, but we cannot merge this until image is also submitted.

**Comment by JoanneHendrickson** [comment]
Thank you. Will correct and resubmit.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by JoanneHendrickson** [comment]
Uploaded .png file to image folder.  Will need to edit TOC to have the topic listed directly below the entry "Migrate web parts using the Migration API".

**Comment by VesaJuvonen** [comment]
I do not see a commit or PR which would add the png on the image folder, so it's not there.

**Pull request merged**
