### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Removing line 26:

- [Tutorial for creating Outlook Web App extension using SharePoint Framework - Preview](https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/office-addins-tutorial) | [video](https://www.youtube.com/watch?v=QtGjTAjbIKU&list=PLR9nK3mnD-OXvSWvS2zglCzz4iplhVrKq&index=9)

Note: The redirect isn't working, and the target content is hard to find. Asking the author for additional information.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[092b0ea](https://github.com/DhurataJ/sp-dev-docs/commits/092b0eaa27140229a046784888f938c99752b9cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/training/training.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-9/docs/training/training.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/training/training?branch=pr-en-us-7860) | [Details](#user-content-b0a7dd6ffafa4cfc24da8ff94bc26b1a-4e4616dd)

<a id="b0a7dd6ffafa4cfc24da8ff94bc26b1a-4e4616dd"></a>
### [docs/training/training.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-9/docs/training/training.md)
 - **Line 16, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/set-up-your-developer-tenant' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 17, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/set-up-your-development-environment' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 21, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 22, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/using-microsoft-graph-apis' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 23, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 24, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 25, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/use-fabric-react-components' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 30, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 31, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 32, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 36, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/provision-sp-assets-from-package' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 37, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/web-parts/get-started/deploy-web-part-to-cdn' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 38, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/use-aad-tutorial' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 39, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 40, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/use-aadhttpclient-enterpriseapi-multitenant' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 44, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 45, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 46, Column 3**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204042300589841-7860%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T23%3A02%3A22Z&sr=b&sp=r&sig=1aJHOmdIiMd%2BQrT0e3%2F4h9cXm%2FRCIhwjGNJTE0ST58A%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[aa7b84e](https://github.com/DhurataJ/sp-dev-docs/commits/aa7b84ebbc150c820c3a686ce2963a2b617df441)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/training/training.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-9/docs/training/training.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/training/training?branch=pr-en-us-7860) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204042308050812-7860%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T23%3A08%3A59Z&sr=b&sp=r&sig=EETYsoEz1rIjESGL2%2Bqc%2BoC7pXEDSzUyivCIpjh1h8g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by DhurataJ** [comment]
**Global effort to fix broken links**

Hi @andrewconnell,

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. In this case of PR, I deleted line 26, the redirect isn't working, and the target content is hard to find.

Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[70c07cc](https://github.com/DhurataJ/sp-dev-docs/commits/70c07cc4677f1ce776f72257651e690c87337921)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/training/training.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-9/docs/training/training.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/training/training?branch=pr-en-us-7860) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204061806445047-7860%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T18%3A07%3A38Z&sr=b&sp=r&sig=qLEMfhimsamGicDEfP5S9DBHle9QbPZho6s4MoARJ60%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
