### PR TITLE
Fixed typo from "useing" to "using"

### PR DESCRIPTION
**Pull request by vijayysisodia**
Fixed typo from "useing" to "using"

## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?
Fixed typo from "useing" to "using"

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a6df4bb](https://github.com/vijayysisodia/sp-dev-docs/commits/a6df4bbfefa59a1b19eaa7541e9d95f68f5d593c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-overview.md](https://github.com/vijayysisodia/sp-dev-docs/blob/patch-1/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview?branch=pr-en-us-7349) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109240425463669-7349%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T04%3A27%3A00Z&sr=b&sp=r&sig=vvBhTJLtLsh9SXqQASBgga1xpz4a6SMUVnu6HAwI%2Fv0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[1bbe583](https://github.com/vijayysisodia/sp-dev-docs/commits/1bbe5830178f23c2a246cb9cbb5686bb39dbdad3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3da37ab9)

<a id="3da37ab9"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281009514309-7349%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A10%3A23Z&sr=b&sp=r&sig=7%2Bvcgz%2BDoj%2FSDGcWXpb3Z8Dwh1UwA93f9puV7CKscpM%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
closing/opening to trigger build checks

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[1bbe583](https://github.com/vijayysisodia/sp-dev-docs/commits/1bbe5830178f23c2a246cb9cbb5686bb39dbdad3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8ea3c8e1)

<a id="8ea3c8e1"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281013187504-7349%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A13%3A49Z&sr=b&sp=r&sig=LgBfK7%2FDI7sFwl8hd%2BRbfBiLmkjl%2FEAZrtMmBXPJKR0%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
@vijayysisodia - please sign the CLA https://github.com/SharePoint/sp-dev-docs/pull/7349/#issuecomment-929056292

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[8e0b065](https://github.com/vijayysisodia/sp-dev-docs/commits/8e0b06545e682c252c49458ad2a0f5c5f69387dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-overview.md](https://github.com/vijayysisodia/sp-dev-docs/blob/patch-1/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview?branch=pr-en-us-7349) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281020394199-7349%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A21%3A58Z&sr=b&sp=r&sig=6ZMvotTsOWR006SuZGPfEbvf4fxzZtmHJuHKN8kiu%2B4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by vijayysisodia** [comment]
> @vijayysisodia - please sign the CLA #7349

The needful has been done @andrewconnell. Thanks much!

**Pull request merged**
