### PR TITLE
Fixing ref links #2017

### LINKED ISSUE #2017: [LOC] Multiple broken links in an article
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

There are multiple non functional links in a table.

**Repro steps:**
1. Go to [https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference)
2. Search for "Table 2. Valid property operators for property restrictions"
3. See links in the table below all of them are nonfunctional 

**GH article:**
https://github.com/SharePoint/sp-dev-docs/blob/live/docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md

**Actual results:**
Links are broken
**Expected results:**
Link should work normally

**Affected links:**
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Text.aspx
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Integer.aspx
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.DateTime.aspx
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Decimal.aspx
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Double.aspx
https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.YesNo.aspx

image

### PR DESCRIPTION
**Pull request by cakriwut**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #2017 

#### What's in this Pull Request?

> Fixing broken links.

#### Guidance

> Fixing broken links.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[961d89c](https://github.com/cakriwut/sp-dev-docs/pull/3254/commits/961d89cc33c3001434f8fb48536129672c53ade7)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[961d89c](https://github.com/cakriwut/sp-dev-docs/pull/3254/commits/961d89cc33c3001434f8fb48536129672c53ade7)_: 

:clock10: **Incremental building**: average incremental building time is _44 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[961d89c](https://github.com/cakriwut/sp-dev-docs/pull/3254/commits/961d89cc33c3001434f8fb48536129672c53ade7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2017/docs/general-development/keyword-query-language-kql-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference?branch=pr-en-us-3254) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901130702000238-3254%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=AFk39q2DNOsYyle0XJokr4lsi6VNfgpeQpuxX2aI8y0%3D&st=2019-01-13T06%3A58%3A49Z&se=2019-02-13T07%3A03%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @cakriwut, appreciated... let's try to keep things in sync to avoid others commits in the same PR.

**Pull request merged**
