### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Fixing the broken link line 96

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6c73a91](https://github.com/DhurataJ/sp-dev-docs/commits/6c73a91a08225478bc8509b67e690279bac1a6c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenario-guidance/Branding.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-5/docs/scenario-guidance/Branding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/branding?branch=pr-en-us-7857) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204041948367821-7857%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-05T19%3A49%3A58Z&sr=b&sp=r&sig=FOaBHXAalC%2F0dbhqExHR1xDrJ74kE7o4qV%2B96pZ2epQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by DhurataJ** [comment]
@tfosmark - Please can you review and merge this PR!

**Comment by tfosmark** [comment]
**Global effort to fix broken links**

@andrewconnell

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[995a6de](https://github.com/DhurataJ/sp-dev-docs/commits/995a6de23ec441f64b8b07a72d786ebf47c02b44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenario-guidance/Branding.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-5/docs/scenario-guidance/Branding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/branding?branch=pr-en-us-7857) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204061757525584-7857%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T17%3A59%3A00Z&sr=b&sp=r&sig=%2B4WIDkD9srxm81t6Xrds9aUQplTcvzgUnyDOgL9B514%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[d417dae](https://github.com/DhurataJ/sp-dev-docs/commits/d417daefdd789b0ded6a06f1341f83badc03dc4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/scenario-guidance/Branding.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-5/docs/scenario-guidance/Branding.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/scenario-guidance/branding?branch=pr-en-us-7857) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204061802550558-7857%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T18%3A04%3A35Z&sr=b&sp=r&sig=npcDcNMtevcJiXlQy5lPKzhIMlSUmFpX78kZqDqdcQ4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
