### PR TITLE
Grammar correction for dynamic-loading.md

### PR DESCRIPTION
**Pull request by PopWarner**
Removed duplicate "it" words in the documentation.

#### Category
- [X ] Content fix

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbd9cb4](https://github.com/PopWarner/sp-dev-docs/pull/3211/commits/cbd9cb499fe083a6325b2562e715ce4234e04578)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbd9cb4](https://github.com/PopWarner/sp-dev-docs/pull/3211/commits/cbd9cb499fe083a6325b2562e715ce4234e04578)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbd9cb4](https://github.com/PopWarner/sp-dev-docs/pull/3211/commits/cbd9cb499fe083a6325b2562e715ce4234e04578)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/dynamic-loading.md](https://github.com/PopWarner/sp-dev-docs/blob/patch-3/docs/spfx/dynamic-loading.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-loading?branch=pr-en-us-3211) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901060236073956-3211%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=XV0R9qr4fzM2%2FTZFDAwuivr930%2FXdfKcBPKNMCPI%2Bh0%3D&st=2019-01-06T02%3A33%3A06Z&se=2019-02-06T02%3A38%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbd9cb4](https://github.com/PopWarner/sp-dev-docs/pull/3211/commits/cbd9cb499fe083a6325b2562e715ce4234e04578)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbd9cb4](https://github.com/PopWarner/sp-dev-docs/pull/3211/commits/cbd9cb499fe083a6325b2562e715ce4234e04578)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[cbd9cb4](https://github.com/PopWarner/sp-dev-docs/pull/3211/commits/cbd9cb499fe083a6325b2562e715ce4234e04578)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/dynamic-loading.md](https://github.com/PopWarner/sp-dev-docs/blob/patch-3/docs/spfx/dynamic-loading.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/dynamic-loading?branch=pr-en-us-3211) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901060240040421-3211%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wsjLCmz1TMPBAqZDlznfOP74v2G2zg5WvakXpB9w%2FZI%3D&st=2019-01-06T02%3A36%3A49Z&se=2019-02-06T02%3A41%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thanks @PopWarner, also great video helping others to do similar contributions... great to have a video to reference for the guidance. Thanks for that.

**Pull request merged**
