### PR TITLE
Fixed typo and indentation

### PR DESCRIPTION
**Pull request by vijayysisodia**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

a) Fixed typo from "WebTemplate1" to "WebTemplate"
b) Removed extra space

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[ba56cb3](https://github.com/vijayysisodia/sp-dev-docs/commits/ba56cb37d0c2913023dc22c5426d569fa1381350)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/get-started-create-site-design.md](https://github.com/vijayysisodia/sp-dev-docs/blob/patch-2/docs/declarative-customization/get-started-create-site-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design?branch=pr-en-us-7350) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C24%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109240508370151-7350%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-25T05%3A09%3A52Z&sr=b&sp=r&sig=%2BD2TU8nyCpk71%2BjlMinZnirUFiz7gPXjB1yd9AtXveo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[bb7086e](https://github.com/vijayysisodia/sp-dev-docs/commits/bb7086eed337fb22f938d80919a9ad02afcb58db)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-de6c9212)

<a id="de6c9212"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281010407504-7350%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A10%3A57Z&sr=b&sp=r&sig=WQot0hsRAcL0H06cY0QzMQtlaNR0N6J28Tvx3KzdYHk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
update doc frontmatter to reflect update date

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[bb7086e](https://github.com/vijayysisodia/sp-dev-docs/commits/bb7086eed337fb22f938d80919a9ad02afcb58db)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-15e57f02)

<a id="15e57f02"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281014422720-7350%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A15%3A13Z&sr=b&sp=r&sig=xyqdzregMqOD3OysSleCTIKk8CM6h1%2FJ6fSRpGKBU3M%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
@vijayysisodia - please sign CLA before we can merge this: https://github.com/SharePoint/sp-dev-docs/pull/7350/#issuecomment-929055322

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[20905e5](https://github.com/vijayysisodia/sp-dev-docs/commits/20905e5968e612e572fb321d272ba8795baa39fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/get-started-create-site-design.md](https://github.com/vijayysisodia/sp-dev-docs/blob/patch-2/docs/declarative-customization/get-started-create-site-design.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/get-started-create-site-design?branch=pr-en-us-7350) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109281019200741-7350%5Cworkflow_report.html?sv=2020-08-04&se=2021-10-29T10%3A20%3A20Z&sr=b&sp=r&sig=ndPwmrcHi%2Fm8t9UwEhw2mfd3dSxV%2FfA1DTq06E0tll0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by vijayysisodia** [comment]
> @vijayysisodia - please sign CLA before we can merge this: #7350

Thanks @andrewconnell. The needful has been done. Wish you a great day ahead!

**Pull request merged**
