### PR TITLE
Updated Generator 'Info' For "SharePoint site theming: JSON schema"

### PR DESCRIPTION
**Pull request by influential-eliot**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

The info tag previously only listed that the generator does not present the "error" and "accent" key/value pairs for color slots in a SharePoint site theme palette.

This update provides the full list of key/value pairs of color slots, so that users are better equipped to create their palettes.

### CODE REVIEW

**Comment by influential-eliot** [comment]
Hiya, sorry, have I oopsied on this somehow?

**Comment by influential-eliot** [comment]
I should also have added that the theme generator also changes the values for "black" and "white" when you alter the Text color and Background color accordingly.

The Text color being aligned to the neutralPrimary slot ... instead of primaryText, or bodyText.

**Review by andrewconnell — APPROVED** [review]

**Comment by influential-eliot** [comment]
Sorry to @ you @andrewconnell ... I am still getting used to the github methodology ... the above seems to indicate that my changes went through ... but they do not appear on the site itself ... is that normal? ie ... is it just waiting for some more merges and stuff?

Sorry to sound so dumb in public!! 😅

**Comment by andrewconnell** [comment]
Changes are accepted and merged to the `main` branch. Periodically Microsoft refreshes the live site... it's not instant when a PR is merged... that's done by someone at MSFT who merges `main` into `live`. The `live` branch reflects what's on the public site.

So, just be patient as it can take a week or two to refresh the live site.

**Comment by influential-eliot** [comment]
[heart]         Eliot Cole reacted to your message:
________________________________

**Pull request merged**
