### PR TITLE
Update build-first-sharepoint-adaptive-card-extension.md

### PR DESCRIPTION
**Pull request by ganesh-sanap**
## Category

- [x] Content fix

## What's in this Pull Request?

Updated "Build your first SharePoint Adaptive Card Extension" article with few headings & content fixes

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[babee31](https://github.com/ganesh-sanap/sp-dev-docs/commits/babee3183ecc9c9265adf18e747e0200391d5068)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-7/docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension?branch=pr-en-us-7210) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C7%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202107271347040716-7210%5Cworkflow_report.html?skoid=5f458e1a-fa67-4ae6-a972-54ea42ec670e&sktid=975f013f-7f24-47e8-a7d3-abc4752bf346&skt=2021-07-26T02%3A29%3A52Z&ske=2021-08-02T02%3A34%3A52Z&sks=b&skv=2020-04-08&sv=2020-04-08&st=2021-07-27T13%3A42%3A59Z&se=2021-08-27T13%3A47%3A59Z&sr=b&sp=r&sig=D15zuI9DeJVftodq8xUmsz%2FXrIKWvIFOhzME5Vt3rLY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
The casing of some words (workbench & view) was set by the product group... this is how they wanted them in the article. Please revert the changes in your PR to how those were originally cased before we can review this. Also, please leave the heading "ACE Quick Views" (don't remove ACE). TY

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[7e884d0](https://github.com/ganesh-sanap/sp-dev-docs/commits/7e884d089fbdf1fc8fd75865f3134d43da8cea1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-7/docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension?branch=pr-en-us-7210) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C5%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202108051118048220-7210%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=bVOG1FLHE4PxYB5qnyDDcvoc4uBq9HLXIVjI6ZKx6VQ%3D&st=2021-08-05T11%3A14%3A14Z&se=2021-09-05T11%3A19%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by ganesh-sanap** [comment]
Thank you @andrewconnell for the comment. I have made the requested changes & updated the article.

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
