### PR TITLE
Formatting docs update - August

### PR DESCRIPTION
**Pull request by shagra-ms**
## Category

- [x] Content fix
- [ ] New article

## Related issues

New functionalities

## What's in this Pull Request?

1. New field support - Attachments
2. New command key support in Command Bar Customization - `exitGridView`
3. New style support - `-webkit-line-clamp`, `object-fit`, `transform`
4. `foreach` now works with all arrays
5. Support fields marked as `Explicit` in ViewFields.
6. New operators - `replaceAll` and `split`
7. New tokens - `@isSelected`, `@lcid` and `@UIlcid`

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[791da99](https://github.com/shagra-ms/sp-dev-docs/commits/791da99bfb94d1d03e88fbfecacaf99a1d1c5e14)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/general-development/sharepoint-search-rest-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview?branch=pr-en-us-8365) | [Details](#user-content-c36ed23e96d0ceb0ab0fe77a97ebbefb-636145f1)
[docs/declarative-customization/column-formatting.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-8365) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8365) |
[docs/declarative-customization/view-commandbar-formatting.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/declarative-customization/view-commandbar-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting?branch=pr-en-us-8365) |

<a id="c36ed23e96d0ceb0ab0fe77a97ebbefb-636145f1"></a>
### [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/general-development/sharepoint-search-rest-api-overview.md)
 - **Line 1147, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      <WhiteList xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays">'`````
 - **Line 1160, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      </WhiteList>'`````
 - **Line 1176, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '- **WhiteList** element'`````
 - **Line 1180, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: 'hat's specified in the **QueryProperties** element. Then, all the properties that are listed in the whitelist are copied from the incoming query to the newly constructed query object.'`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202208112053219118-8365/BuildReport?accessString=1d2326db7b3a01907d5f859e964b546054bec32842788947854e764818c00340).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[bf57fd4](https://github.com/shagra-ms/sp-dev-docs/commits/bf57fd4572bbb393bf2b3198b0509b13ee8c74ba)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-91aced0b)

<a id="91aced0b"></a>
###
 - **[Error: CannotMergeCommit]** `````Cannot merge commit bf57fd4572bbb393bf2b3198b0509b13ee8c74ba in branch shagar/docs-update-august of repository https://github.com/shagra-ms/sp-dev-docs into branch main (commit 9d3a041d2615280989d26af4857dfa08061f0836). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202208112100330514-8365/BuildReport?accessString=c5079d860353c95b07a41119e4f703f26c70f60f596852f6197dab0e5d9b0376).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[ebdec63](https://github.com/shagra-ms/sp-dev-docs/commits/ebdec631070be3d08a5007ec321642a2ea83f850)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/general-development/sharepoint-search-rest-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview?branch=pr-en-us-8365) | [Details](#user-content-c36ed23e96d0ceb0ab0fe77a97ebbefb-d61aac04)
[docs/declarative-customization/column-formatting.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting?branch=pr-en-us-8365) |
[docs/declarative-customization/formatting-syntax-reference.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/declarative-customization/formatting-syntax-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/formatting-syntax-reference?branch=pr-en-us-8365) |
[docs/declarative-customization/view-commandbar-formatting.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/declarative-customization/view-commandbar-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-commandbar-formatting?branch=pr-en-us-8365) |

<a id="c36ed23e96d0ceb0ab0fe77a97ebbefb-d61aac04"></a>
### [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/shagra-ms/sp-dev-docs/blob/shagar/docs-update-august/docs/general-development/sharepoint-search-rest-api-overview.md)
 - **Line 1147, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      <WhiteList xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays">'`````
 - **Line 1160, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      </WhiteList>'`````
 - **Line 1176, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '- **WhiteList** element'`````
 - **Line 1180, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: 'hat's specified in the **QueryProperties** element. Then, all the properties that are listed in the whitelist are copied from the incoming query to the newly constructed query object.'`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202208112103479058-8365/BuildReport?accessString=299121959dff14ee211b797e1099a1b184650acb02dd55080cdd6b9e63e868f3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Fedes365** [comment]
Fireworks are expected thanks to the new **_transform_** style support 🤩

**Comment by aaclage** [comment]
@shagra-ms Thanks was not aware.

**Pull request merged**
