### PR TITLE
Update sorting-search-results-in-sharepoint.md

### LINKED ISSUE #2619: [LOC] Invalid links in an article (sorting-search-results-in-sharepoint.md)
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/general-development/sorting-search-results-in-sharepoint (or GH https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/sorting-search-results-in-sharepoint.md)
2. Search the link texts below e.g. "_Sortable()_"
3. Click the links --> 404 error pages

**Affected links:**

LinkText | Link URL
-- | --
Sortable() | https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.Sortable.aspx
Integer | https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Integer.aspx
Decimal | https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Decimal.aspx
DateTime | https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.DateTime.aspx
Datetime() | https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedDataType.Datetime.aspx

**Note:** some of broken links were also found in _keyword-query-language-kql-syntax-reference.md_ article (https://github.com/SharePoint/sp-dev-docs/blob/live/docs/general-development/keyword-query-language-kql-syntax-reference.md)

### PR DESCRIPTION
**Pull request by KingKangMSFT**
#### Category
- [ x ] Content fix
- [ ] New article
- Related issues: fixes #2619 

#### What's in this Pull Request?

Modify the link of Sortable() to `https://msdn.microsoft.com/library/Microsoft.Office.Server.Search.Administration.ManagedPropertyInfo.Sortable.aspx`

Modify the links of  `Integer`, `Decimal`, `DateTime`, `Datetime()` to `https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms500214(v%3Doffice.14)`

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/sorting-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/KingKangMSFT-patch-1-3/docs/general-development/sorting-search-results-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sorting-search-results-in-sharepoint?branch=pr-en-us-2623) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201809240918326161-2623%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=voDiebxlmt05A2ke68Lh5Ffj28NCx15r95QTdkFq%2B4s%3D&st=2018-09-24T09%3A15%3A34Z&se=2018-10-25T09%3A20%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Linda-Editor** [comment]
@KingKangMSFT Please sign the CLA

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/sorting-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/KingKangMSFT-patch-1-3/docs/general-development/sorting-search-results-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sorting-search-results-in-sharepoint?branch=pr-en-us-2623) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C24%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201809241557095472-2623%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=iRY64eeQDTswLxskHvDVo7xDUknbIcwG0FXgfUKhaTc%3D&st=2018-09-24T15%3A54%3A19Z&se=2018-10-25T15%3A59%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @KingKangMSFT, appreciated.

**Pull request merged**
