### PR TITLE
Update compatibility.md

### PR DESCRIPTION
**Pull request by hugoabernier**
## Category

- [x] Content fix
- [ ] New article

## Related issues

None

## What's in this Pull Request?

Added SPFx 1.19

### CODE REVIEW

**Review by andrewconnell — APPROVED** [review]
Haven't tested, but are you sure older versions of NPM work with versions this new of Node? I don't think so...

**Comment by andrewconnell** [comment]
@hugoabernier , can you please complete the CLA so we can merge this?

**Comment by andrewconnell** [comment]
@hugoabernier The more I think about it, NPM should not be listed in this page. It's not a SPFx dependency and there's no direct requirement. NPM is always installed aside Node. The version of NPM is dependent on Node, not on the version of SPFx or vice versa.

At a maximum, the SPFx docs (_ie: this doc_) should _only_ say to use the version of NPM that's supported with the version of Node that you're using. We don't need to have our docs someone else's docs (ie: NPM/Node).

**Comment by hugoabernier** [comment]
@microsoft-github-policy-service agree

**Comment by hugoabernier** [comment]
@andrewconnell I agree. I have removed it.

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
