### PR TITLE
Corrected Type for adding data

### PR DESCRIPTION
**Pull request by nanddeepn**
#### Category
- [x] Content fix

#### Related issues:
- fixes https://github.com/SharePoint/sp-dev-docs/issues/3012
- partially https://github.com/SharePoint/sp-dev-docs/pull/4138, https://github.com/SharePoint/sp-dev-docs/pull/4183

#### What's in this Pull Request?
Corrected Type for adding data in a code.
Implemented changes suggested in #4138

#### Guidance
On the page https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/get-to-know-the-sharepoint-rest-service
Corrected Type for adding data in a code that adds an item to a list sample data.

### CODE REVIEW

**Comment by nanddeepn** [comment]
The changes are yet to be reflected on the MSDN page.

**Comment by nanddeepn** [comment]
Hi @andrewconnell 
The merge pull request is blocked. Can you please help here. Thanks!

**Comment by andrewconnell** [comment]
Some PR's I can merge (typos, formatting, etc), most Microsoft needs to merge. Please be patient.

**Comment by VesaJuvonen** [comment]
thx @nanddeepn, appreciated.

**Pull request merged**
