### PR TITLE
Adding the newest trigger

### PR DESCRIPTION
**Pull request by tomresing**
Keeping up to date with https://docs.microsoft.com/en-us/connectors/sharepointonline/#triggers

## Category

- [X] Content fix
- [ ] New article

## What's in this Pull Request?

adding 3 lines to one markdown file

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6f9d3b0](https://github.com/tomresing/sp-dev-docs/commits/6f9d3b0f774613a7693d9af4293976c1c40ec2c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md](https://github.com/tomresing/sp-dev-docs/blob/patch-7/docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/sharepoint-connector-actions-triggers?branch=pr-en-us-7045) | [Details](#user-content-a3d81cf31008329dbe9295869ae3996f-37bdb4d2)

<a id="a3d81cf31008329dbe9295869ae3996f-37bdb4d2"></a>
### [docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md](https://github.com/tomresing/sp-dev-docs/blob/patch-7/docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````
 - **Line 45, Column 77**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoft-365/contentunderstanding' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C26%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202105262352285287-7045%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zyUvHs86sygxrWGubkMvJ256pa71Bjz7frwZPSnOlh0%3D&st=2021-05-26T23%3A48%3A35Z&se=2021-06-26T23%3A53%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[30a87a4](https://github.com/tomresing/sp-dev-docs/commits/30a87a4b9da50db9a5973965cc1abe1b9379edb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md](https://github.com/tomresing/sp-dev-docs/blob/patch-7/docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/sharepoint-connector-actions-triggers?branch=pr-en-us-7045) | [Details](#user-content-a3d81cf31008329dbe9295869ae3996f-8292cde8)

<a id="a3d81cf31008329dbe9295869ae3996f-8292cde8"></a>
### [docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md](https://github.com/tomresing/sp-dev-docs/blob/patch-7/docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202105270001323579-7045%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vXn7zE2%2BYOrFXBUWyyKBoDKWZHP7w6IkTuQP2JciKKQ%3D&st=2021-05-26T23%3A57%3A14Z&se=2021-06-27T00%3A02%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[c782fbf](https://github.com/tomresing/sp-dev-docs/commits/c782fbf5d4deb596bba42c2476e87ba4f2f90980)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md](https://github.com/tomresing/sp-dev-docs/blob/patch-7/docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/sharepoint-connector-actions-triggers?branch=pr-en-us-7045) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106011548106149-7045%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B767QMsvc3HqNFkOrj2JurYOiAIO7%2FbtfE0pMucbETI%3D&st=2021-06-01T15%3A44%3A22Z&se=2021-07-02T15%3A49%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by tomresing — COMMENTED** [review]
That description and date are ok with me.

**Comment by andrewconnell** [comment]
@tomresing Cool... but can you please fix the conflict as we can't merge it as is.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[f088c66](https://github.com/tomresing/sp-dev-docs/commits/f088c66b7276211ee11b0e0ebe8b2429f494aa94)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bc69a4a0)

<a id="bc69a4a0"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106012043194485-7045%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KNiIitp6odpKUENYGBMnrw57MIhDTWfmIxuObu9p%2Fnk%3D&st=2021-06-01T20%3A38%3A54Z&se=2021-07-02T20%3A43%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[d19828a](https://github.com/tomresing/sp-dev-docs/commits/d19828ac89db7d517fc3b9b27e83ece2d264789b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md](https://github.com/tomresing/sp-dev-docs/blob/patch-7/docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/sharepoint-connector-actions-triggers?branch=pr-en-us-7045) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106012044561051-7045%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TV%2BOKZ8k%2Baq2GQaHMit%2FCOE3t599pcT2QQOdaEmGSIw%3D&st=2021-06-01T20%3A40%3A53Z&se=2021-07-02T20%3A45%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by tomresing** [comment]
@andrewconnell sorry, not sure what was going on. For some reason, changing the date to June 10th seemed to resolve the conflict. This is a GitHub process mystery to me.

**Review by andrewconnell — APPROVED** [review]

**Comment by tomresing** [comment]
Thanks, @andrewconnell!

**Pull request merged**
