### PR TITLE
New design articles for SharePoint Ignite 2018 - Ajford76 patch 1

### PR DESCRIPTION
**Pull request by ajford76**
#### New and updated articles for  Design a web part
- [ ] Content fix - themes-colors.md 
- [ ] New article - web-part-levels.md
- [ ] New article - layout-patterns.md
- [ ] New article - designing-a-web-part-icon.md

#### What's in this Pull Request?
Updated theme colors to match colors for SharePoint themes.
Added new articles for understanding how to leverage web part layouts and interaction states.
Added a new article with design guidance for creating a web part icon.

### CODE REVIEW

**Comment by ajford76** [comment]
@Lauragra @lindalu-MSFT pull request for edits and additional articles for the Design section for SharePoint web parts. Sent an email as well, please let me know if you need any additional information.

**Comment by lindalu-MSFT** [comment]
@ajford76 Thanks for the contribution! Can you please fix the merge conflicts? Also, Linda C and I do not have permissions to merge your article to master. Please contact @VesaJuvonen for assistance. Cheers

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\3y3o-s, target branch: master, target branch commit: 0178b69cf56be8e4fa711432424f7927861d2ccc, source branch: 03e876325f57810180667b6531e15f18/ajford76-patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C7%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201809070232582643-2432%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=fTx2DxllG7OXMLq1jCCegiGy86Eqi%2B3jui8%2Fu0tVnLI%3D&st=2018-09-07T02%3A28%3A24Z&se=2018-10-08T02%3A33%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\vkut-s, target branch: master, target branch commit: 086cc135a36a8630d6a5b3e6916ae83bac773436, source branch: 03e876325f57810180667b6531e15f18/ajford76-patch-1, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C9%5C10%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201809101637170847-2432%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=I7Pm4Xv5NPj11Sla%2BxhP03mCo66lnL%2BSW0nW6xmiyDc%3D&st=2018-09-10T16%3A32%3A44Z&se=2018-10-11T16%3A37%3A44Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Git conflicts manually resolved and merged to master. Few nasty ones, but good to get this sorted for Ignite.

**Comment by VesaJuvonen** [comment]
Please also note that this contained articles which are not yet in TOC, so we need to get them added there when the review is completed.

**Pull request merged**
