### PR TITLE
Added Office 365 CLI documentation

### PR DESCRIPTION
**Pull request by appieschot**
Based on the PowerShell implementation a version that contains all O365 CLI commands to easily manage site designs and site scripts from any device.

#### Category
- [ ] Content fix
- [x] New article

### CODE REVIEW

**Comment by appieschot** [comment]
@andrewconnell yes there is such a page. I do not mind putting these changes in there as well, but that would require renaming the page to a broader term then is used now. I would suggest to rename site-design-powershell to site-design-management and merge both pages together. Please let me know if that approach sounds viable and if so decline this PR. I will do a new one with that change in it.

**Comment by andrewconnell** [comment]
Hmmm... wasn't aware of that page. Maybe keeping a sperate page then so not to screw up existing links, rather adding a callout in the other page pointing to this one and vice versa?

**Comment by appieschot** [comment]
@andrewconnell added a see also link on both pages,

**Comment by andrewconnell** [comment]
LGTM... because it's a new article, need to let MSFT merge this one in...

**Comment by appieschot** [comment]
Sorry for screw up, removed branch by accident.

**Comment by VesaJuvonen** [comment]
thx @appieschot, getting things finally merged.

**Pull request merged**
