### PR TITLE
[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute

### PR DESCRIPTION
**Pull request by alexbuckgit**
## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

**Global effort to fix build validation errors**

The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

### CODE REVIEW

**Comment by alexbuckgit** [comment]
#docutune-draft

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[fe90086](https://github.com/alexbuckgit/sp-dev-docs/commits/fe90086eeb7065638a2d598122a5ba81fbb0bc06)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/alexbuckgit/sp-dev-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220830-204429-5410812/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8407) |
[docs/general-development/sorting-search-results-in-sharepoint.md](https://github.com/alexbuckgit/sp-dev-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220830-204429-5410812/docs/general-development/sorting-search-results-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sorting-search-results-in-sharepoint?branch=pr-en-us-8407) |
[docs/index.yml](https://github.com/alexbuckgit/sp-dev-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220830-204429-5410812/docs/index.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/index?branch=pr-en-us-8407) |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/alexbuckgit/sp-dev-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220830-204429-5410812/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-8407) |
[docs/transform/modernize-scanner-reports-lists.md](https://github.com/alexbuckgit/sp-dev-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220830-204429-5410812/docs/transform/modernize-scanner-reports-lists.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-lists?branch=pr-en-us-8407) |
[README.md](https://github.com/alexbuckgit/sp-dev-docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220830-204429-5410812/README.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202208302044393171-8407/BuildReport?accessString=846af391c5307f15a94176cb21f46a854bbc066b58e46cbc992886b89ea2cb30).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by alexbuckgit** [comment]
#docutune-ready

**Comment by alexbuckgit** [comment]
@JoanneHendrickson @VesaJuvonen @chuckedmonson

Please merge the changes in this PR. For more information, see the description at the top of this PR.

Any pre-existing build validation issues or insufficient Acrolinx scores should be addressed in a separate PR.

#docutune-request-approval

**Pull request merged**
