### PR TITLE
Remove missing link. Can not find new references via Bing or Google

### LINKED ISSUE #3234: [LOC] Invalid link in an article (user-segmentation-in-sharepoint.md)
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/general-development/user-segmentation-in-sharepoint (or GH https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/user-segmentation-in-sharepoint.md)
2. Search "_Set up User Segmentation to drive adaptive experiences in a Product Catalog in SharePoint_" link text (http://blogs.msdn.com/b/adaptive_experiences_in_sharepoint_2013/archive/2012/11/14/set-up-user-segmentation-to-drive-adaptive-experiences-in-a-product-catalog-in-sharepoint.aspx)
3. Click the link --> 404 error page

**Expected:** link should be removed from the article or redirect to a valid page

image

### PR DESCRIPTION
**Pull request by cakriwut**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #3234 

#### What's in this Pull Request?

> Remove invalid link. I have searched the original link, text using Google, Bing - there is no new/replacement link for the reference.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[171f52c](https://github.com/cakriwut/sp-dev-docs/pull/3250/commits/171f52ccffe5491f08b74e4ed1fa91169b5e1109)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[171f52c](https://github.com/cakriwut/sp-dev-docs/pull/3250/commits/171f52ccffe5491f08b74e4ed1fa91169b5e1109)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[171f52c](https://github.com/cakriwut/sp-dev-docs/pull/3250/commits/171f52ccffe5491f08b74e4ed1fa91169b5e1109)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/user-segmentation-in-sharepoint.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-3234/docs/general-development/user-segmentation-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/user-segmentation-in-sharepoint?branch=pr-en-us-3250) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C12%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901121401086048-3250%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=KhXK6PiFT5QFT%2FxOHjkmZpxm5onfTo1pB76s4HXKUKo%3D&st=2019-01-12T13%3A57%3A55Z&se=2019-02-12T14%3A02%3A55Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @cakriwut, like noted by @andrewconnell, this was not quite in sync and contained changes to hundreds of files and not only with the commit which you had. These things do happen, but let's try to avoid them in the future.

**Comment by cakriwut** [comment]
Thanks @VesaJuvonen & @andrewconnell , noted for all feedback.

**Pull request merged**
