### PR TITLE
Update single-part-app-pages.md

### PR DESCRIPTION
**Pull request by ksdaniel**
Changed the CLI command to apppage add.

## Category

- [x] Content fix
- [ ] New article

## What's in this Pull Request?

On the single app part pages, changed the CLI command from "m365 spo listitem" set to "m365 spo apppage add".

This seems to be the new way of adding apppages - although to be fair, I have the impression that the CreateFullAppPage api that is used by the CLI is not rolled out to all tenants. 

On the other hand, the method described in the old version never worked for me.

### CODE REVIEW

**Comment by andrewconnell** [comment]
@waldekmastykarz @garrytrinder You care to comment on this suggestion before we update the doc?

**Comment by garrytrinder** [comment]
@ksdaniel we recently pushed a fix for the `spo listitem set` command https://github.com/pnp/cli-microsoft365/pull/1989 

This fix is in the latest beta release, are you able to test and see if this resolves your issue? 

You can install the beta using `npm i -g @pnp/cli-microsoft365@next`.

**Comment by andrewconnell** [comment]
@garrytrinder So... worst case the docs are correct, there was just a bug that will get fixed in the next release (but available now in beta), correct? If so, then this should be closed & not merged, correct?

**Comment by garrytrinder** [comment]
@andrewconnell yes, I feel that is a fair assessment.

**Comment by andrewconnell** [comment]
Closing as this is not an error in the docs

**Comment by ksdaniel** [comment]
Realized this is closed... but: 

- the good news, with @next I can change existing app pages again - so that is great. 

- the article says provisioning app pages - so this could mean either making a new page (the apppage add way) or transform an existing page into an app page (the listitem set way). 

- if the recommended way is to create a "normal' page and then transform it, what is the use of the apppage add command? Anything we should be aware about? 

This is low prio - its just me being curious.

**Comment by waldekmastykarz** [comment]
@ksdaniel it seems like the docs are based on an older version of the CLI where updating the layout was the only option. I think it would be a great addition to the docs to show that you can also directly create a new app page. Rather than changing existing sample, I'd suggest adding a new sample using the `spo apppage add` command.

**Pull request closed without merging**
