### PR TITLE
Update using-web-part-as-ms-teams-tab.md

### PR DESCRIPTION
**Pull request by panjkov**
typos

#### Category
- [x] Content fix
- [ ] New article
- Related issues: none

#### What's in this Pull Request?

typos in SPFx Teams tab web part tutorial

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[16a6f87](https://github.com/panjkov/sp-dev-docs/pull/3258/commits/16a6f872f0eb07f384a44d0c91ea5439691a047e)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[16a6f87](https://github.com/panjkov/sp-dev-docs/pull/3258/commits/16a6f872f0eb07f384a44d0c91ea5439691a047e)_: 

:clock10: **Incremental building**: average incremental building time is _44 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[16a6f87](https://github.com/panjkov/sp-dev-docs/pull/3258/commits/16a6f872f0eb07f384a44d0c91ea5439691a047e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md](https://github.com/panjkov/sp-dev-docs/blob/patch-7/docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab?branch=pr-en-us-3258) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901140758165465-3258%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YJd5mraSjEDwDEPueLULmSPs8bcB4fxRd%2FYt9AzPgx0%3D&st=2019-01-14T07%3A55%3A02Z&se=2019-02-14T08%3A00%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @panjkov, appreciated.

**Pull request merged**
