### PR TITLE
Update spod-copy-move-api.md

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
Updated line 143 to insert a link to SharePoint limits for copy move limits.

## Category

- [X] Content fix

## What's in this Pull Request?

An update to line 143 that corrects outdating file size limitation in copy and move.  Instead inserted a link to the Sharepoint Limits article to avoid it being out of date in the future.

### CODE REVIEW

**Comment by JoanneHendrickson** [comment]
@andrewconnell  This is pressing as team can't present to the customer without the change.  Thanks! joanne

**Review by andrewconnell — APPROVED** [review]

**Comment by JoanneHendrickson** [comment]
@andrewconnell  - When can we expect this to go live? This is a pressing issue for the product team and their customer.

**Comment by andrewconnell** [comment]
I'm not sure... that's a @VesaJuvonen question I think... not sure if there's a schedule when things are pushed to live or if it's always manual.

**Comment by VesaJuvonen** [comment]
@JoanneHendrickson - I'm finalizing other urgent changes and publishing docs today. Was not aware that these had a timeline, so we simply waited for other updates to trickle in. Will be updated within next 2 hours or so.

thx @andrewconnell for letting me know about this discussion.

**Comment by JoanneHendrickson** [comment]
For future reference, when it is pressing, what is the best way to indicate it? directly as a comment and @mentioning you? thanks in advance

**Comment by VesaJuvonen** [comment]
@JoanneHendrickson - please ping me directly at the Teams for anything which is high priority. I get hundreds/thousands of messages from GitHub on daily basis without any possibility to follow up on them. Anything which is high priority would be good to notify using Microsoft Teams. thx.

image

**Pull request merged**
