### PR TITLE
Update to Resolving Dependancies - using npm ci

### PR DESCRIPTION
**Pull request by markyroden**
The current documentation describes using npm install - using npm ci significantly improves the the speed of the build process. Seeing as this is the rate determining step for the overall build process doing everything we can to speed it up is important.

For reference
https://stackoverflow.com/a/53325242

### CODE REVIEW

**Comment by andrewconnell** [comment]
Sorry for the delay... but can you update the PR to address the conflicts before we eval to merge? Thanks!

**Comment by markyroden** [comment]
Andrew,

I didn't know there were conflicts sorry :(

I also noticed yesterday(literally) that it is now out of date as well.

There is now a CI option on devops in addition to install and custom. So
it's even easier on the user.

So is it better to update my PR with the new instructions of reject it and
do another one?

Thanks,

Mark

**Comment by andrewconnell** [comment]
could have easily been a case where something changed AFTER you submitted so it's just the result of us not merging it in sooner. Either way... not a problem.

It's up to you how you want to do it... there is another PR #4976 with a lot of changes to those docs if you want to wait until that's merged.

As for the process, it doesn't matter if you close & resubmit, or if you just put another commit on top of it.

**Comment by andrewconnell** [comment]
bump...

**Pull request closed without merging**
