### PR TITLE
Update migration-api-whats-new.md

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
## Category

- [X] Content fix/update

## What's in this Pull Request?

Added notation of new requirement, the mandatory use of SourceType when calling the Migration API. updated date.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e9352e6](https://github.com/JoanneHendrickson/sp-dev-docs/commits/e9352e6b4d36908d6a53b84cbe6d165320fcb0c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-whats-new.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-66/docs/apis/migration-api-whats-new.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/sharepoint/dev/apis/migration-api-whats-new?branch=pr-en-us-8455) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202209231701533427-8455/BuildReport?accessString=a55346a8e3935a2f2585e725df2fd528cd7a039fccfbdfe3a653381d46035b2c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JoanneHendrickson** [comment]
@andrewconnell  I need to add this article (which is an existing topic) to the TOC but cannot find the file to edit or that has the node for the Sharepoint migration api..  Can you point me to it? thanks joanne

**Comment by andrewconnell** [comment]
https://github.com/SharePoint/sp-dev-docs/blob/main/docs/toc.yml#L2076

**Review by andrewconnell — APPROVED** [review]

**Comment by JoanneHendrickson** [comment]
@andrewconnell   When can we expect this to go live?  thanks!

**Comment by andrewconnell** [comment]
¯\_(ツ)_/¯ ... I think that's a scheduled process, but it's managed by MS... @VesaJuvonen might have insight into the schedule for golive pushes...

**Comment by JoanneHendrickson** [comment]
@andrewconnell  -- thanks and good to know -- If we could know the managed schedule publishing days are  (weekly?)  I can set expectations with my PMs regarding timing.

**Comment by andrewconnell** [comment]
Unfortunately, I can't answer those questions... I just help in reviewing PR submissions and update the docs on a weekly basis. Only MS employees (IOW, not me) can push doc updates to prod.

**Comment by JoanneHendrickson** [comment]
@VesaJuvonen   @andrewconnell   Vesa:  Can you predict when this pr will go live?  If you could let me know the managed publishing schedule I can let the PMs know and set expectations.  A communication to our ISVs is on hold until this goes live. Thanks!

**Comment by JoanneHendrickson** [comment]
@VesaJuvonen   Yes -- and thank you!

**Comment by gittig23441** [comment]
Policy.edit group

**Pull request merged**
