### PR TITLE
Document some string related operators

### PR DESCRIPTION
**Pull request by holylander**
Document how to concatenate strings and how to find the length of a string ( workaround )

#### Category
- [x] Content fix
- [ ] New article

#### What's in this Pull Request?

Document and example of how to concatenate strings and how to find the length of a string ( workaround )

### CODE REVIEW

**Comment by holylander** [comment]
@thechriskent please take a look to the pr :) :)

**Comment by holylander** [comment]
> 
> 
> Looks good to me. I believe you were on the call, but if not, I used your tip as part of my presentation this morning. Great idea, thanks! And especially thanks for sharing it with everyone!
> 
> Didn't realize I needed to officially submit a review (sorry for the delay), but this looks good to merge! The docs repo is very restricted to who can merge (and I'm not one of them) but I'm sure they'll get it in soon.

Thanks Chris! yeah a I colleague told me you mentioned me in the community call :) I joined a little bit late on that one, but I was glad to hear such a thing :) I am always happy to help. Thanks @andrewconnell  for merging the changes ;) Have a great monday!

**Comment by holylander** [comment]
Hey @andrewconnell, qq, I dont see the update on the [column formatting ](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/column-formatting)page, did the merge went fine? thanks very much

**Comment by thechriskent** [comment]
The changes were merged into master. There will be a later merge from master into live and then you'll see the changes within the docs themselves. Shouldn't be too long. Thanks again!

**Pull request merged**
