### PR TITLE
[BrokenLinksH2] fixing broken link

### PR DESCRIPTION
**Pull request by StephenBrentPeters**
**Global effort to fix broken links**

@JarbasHorst 

The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. Please review within five business days and merge, or comment in the PR with any changes you'd like to see. Thanks!

Perhaps you're the right person to merge this?

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

Fixed broken link.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[bfa3a2e](https://github.com/StephenBrentPeters/sp-dev-docs/commits/bfa3a2ef398d17f62f784bec137d7c854a873476)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/team-based-development-on-sharepoint-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/team-based-development-on-sharepoint-framework.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/team-based-development-on-sharepoint-framework?branch=pr-en-us-7916) | [Details](#user-content-0da6029f42520998e15beb959f83f830-80aa0099)

<a id="0da6029f42520998e15beb959f83f830-80aa0099"></a>
### [docs/spfx/team-based-development-on-sharepoint-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/team-based-development-on-sharepoint-framework.md)
 - **Line 141, Column 82**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'package' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 141, Column 118**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'package' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 157, Column 97**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/vsts/package/overview' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 259, Column 348**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'package' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 259, Column 358**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'version' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C25%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204251935243876-7916%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-26T19%3A37%3A12Z&sr=b&sp=r&sig=Oj7GCnehjEKYs8fqUw63FkI2FfNoduzIbuNiZhzvuTk%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[038dfea](https://github.com/StephenBrentPeters/sp-dev-docs/commits/038dfeaeecc79e1b01a4bf04823fb755d32d40b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/team-based-development-on-sharepoint-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/team-based-development-on-sharepoint-framework.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/team-based-development-on-sharepoint-framework?branch=pr-en-us-7916) | [Details](#user-content-0da6029f42520998e15beb959f83f830-6ed6f025)

<a id="0da6029f42520998e15beb959f83f830-6ed6f025"></a>
### [docs/spfx/team-based-development-on-sharepoint-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/team-based-development-on-sharepoint-framework.md)
 - **Line 141, Column 82**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'package' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 141, Column 118**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'package' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 259, Column 348**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'package' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 259, Column 358**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'version' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204270036239048-7916%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-28T00%3A38%3A08Z&sr=b&sp=r&sig=q0u5o%2FmDB%2FW84KPOp8KtcDjqMC4q5E1EmzCa24yoIs4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by JarbasHorst** [comment]
Hi @StephenBrentPeters,

unfortunately, I don't have publishing rights for this repository. I assume that the corresponding person at Microsoft will address your PR at some point.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[65afc3f](https://github.com/StephenBrentPeters/sp-dev-docs/commits/65afc3fb9d1bbe690a6c9fc345cae86328f4222d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/team-based-development-on-sharepoint-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/team-based-development-on-sharepoint-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/team-based-development-on-sharepoint-framework?branch=pr-en-us-7916) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204281557475419-7916%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-29T15%3A59%3A40Z&sr=b&sp=r&sig=KFoAWGA209KB8L97HOVLA10cvyH4fDvOLjdPSL64h8g%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
