### PR TITLE
Fixed typos and improved formatting

### PR DESCRIPTION
**Pull request by ganesh-sanap**
## Category

- [x] Content fix

## What's in this Pull Request?

Fixed typos in article and improved formatting of conditional formulas

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[48d40ae](https://github.com/ganesh-sanap/sp-dev-docs/commits/48d40ae66dc4cd1f0dc750fe015280b0bfd2aa6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-8/docs/declarative-customization/list-form-conditional-show-hide.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide?branch=pr-en-us-6594) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C7%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101071731264740-6594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TsMISGCRNlfWuPd0I9sx9bW%2FOHVZ6jzdlCDs0SYhthc%3D&st=2021-01-07T17%3A27%3A08Z&se=2021-02-07T17%3A32%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
There are multiple changes that need to be reviewed to ensure they are correct, such as things that are/aren't supported.

**Comment by ganesh-sanap** [comment]
@VesaJuvonen Can you please review this PR?

**Comment by ganesh-sanap** [comment]
@VesaJuvonen

**Comment by ganesh-sanap** [comment]
@VesaJuvonen @andrewconnell, Any updated on this PR?

It also closes the issue: https://github.com/SharePoint/sp-dev-docs/issues/6633

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[209c6f5](https://github.com/ganesh-sanap/sp-dev-docs/commits/209c6f53f90483ad57af73afcc3445c2e74df717)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/list-form-conditional-show-hide.md](https://github.com/ganesh-sanap/sp-dev-docs/blob/patch-8/docs/declarative-customization/list-form-conditional-show-hide.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/list-form-conditional-show-hide?branch=pr-en-us-6594) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202104160755048540-6594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xNXTKr%2BX7BLSK%2Fqrldf8vTzOWYV8dbDmrigbxtU1I1A%3D&st=2021-04-16T07%3A51%3A19Z&se=2021-05-17T07%3A56%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
thx @ganesh-sanap, appreciated.

**Pull request merged**
