### PR TITLE
Fix malformed ```ts section

### PR DESCRIPTION
**Pull request by JLRishe**
| Q                   | A
| ---------------     | ---
| content fix?        | yes
| New article?        | no

#### What's in this Pull Request?

One of the code sections in this page had incorrect whitespace in the markup, causing the boundary backticks to show through in the rendered page and also for the non-code line of text after the code to be rendered as code. I have fixed the whitespace so the content should be rendered correctly.

This is also currently visible on the published document: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/using-page-placeholder-with-extensions

### CODE REVIEW

**Comment by davidchesnut** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/JLRishe/sp-dev-docs/blob/patch-2/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C3%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710030850541551-896%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=0QL7Zsz2ybCM7M8SjZ8VVhGITQDbetxYcPBq0cG%2BrKg%3D&st=2017-10-03T08%3A46%3A49Z&se=2017-10-04T08%3A56%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx Jimmy, appreciated. Notice that based on our contribution guidance, we only take submissions towards master branch to avoid immediately publishing to live pages, but will do an exception in this case - for the next time. We'll also double check the settings for that.

**Comment by davidchesnut** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md](https://github.com/JLRishe/sp-dev-docs/blob/patch-2/docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C3%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710031113442593-896%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2gUG0dyrMipQncu%2BD6cXtSAtTggmq7sTZm8hYJjlWMA%3D&st=2017-10-03T11%3A18%3A49Z&se=2017-10-04T11%3A28%3A49Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by JLRishe** [comment]
@VesaJuvonen Thank you for accepting my PR. When I clicked the Edit link on https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/connect-to-sharepoint it took me to the file on the live branch and that's how I ended up submitting a PR to that branch. I'll be careful in the future not to do that.

**Comment by VesaJuvonen** [comment]
Hi @JLRishe - sorry for the delay around this. I've configured systems now properly so that if you click Edit, you'll land on the master branch, which is the one which can be used for edits. Thanks for pointing this configuration issue out.

**Pull request merged**
