### PR TITLE
Corrected unreadable sentence

### PR DESCRIPTION
**Pull request by Pieter-Veenstra**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[53e346b](https://github.com/Pieter-Veenstra/sp-dev-docs/pull/3149/commits/53e346bd4c4d03ef2201e4d386eb2371af1520c3)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[53e346b](https://github.com/Pieter-Veenstra/sp-dev-docs/pull/3149/commits/53e346bd4c4d03ef2201e4d386eb2371af1520c3)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[53e346b](https://github.com/Pieter-Veenstra/sp-dev-docs/pull/3149/commits/53e346bd4c4d03ef2201e4d386eb2371af1520c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/site-design-overview.md](https://github.com/Pieter-Veenstra/sp-dev-docs/blob/master/docs/declarative-customization/site-design-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview?branch=pr-en-us-3149) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C19%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812191537249849-3149%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=MdyoIoDzxjVwhYAoDKxmvU0raErEVWSHqamSHspBm70%3D&st=2018-12-19T15%3A34%3A16Z&se=2019-01-19T15%3A39%3A16Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @Pieter-Veenstra, appreciated.

**Pull request merged**
