### PR TITLE
Update migration-api-overview.md

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
## Category

- [X] Content fix

## What's in this Pull Request?

References to **InitializationVector** as a new parameter was entered in error. It does not apply, and needs to be removed.
This is not stemmed from a posted issue, but from internal review.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[2a8b8ad](https://github.com/JoanneHendrickson/sp-dev-docs/commits/2a8b8adfa3360b9c272356c721805397d32d72c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-55/docs/apis/migration-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6714) | [Details](#user-content-dd0fe65f-0254d780)

<a id="dd0fe65f-0254d780"></a>
### [docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-55/docs/apis/migration-api-overview.md)
 - **Line 21, Column 91**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/code-snippets/quickxorhash?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102162057087685-6714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FE1fGp5JV%2B7cOieDRPi4G6TnWvGU8pSl6dCS5KZF9Nw%3D&st=2021-02-16T20%3A53%3A18Z&se=2021-03-19T20%3A58%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[f5cfb77](https://github.com/JoanneHendrickson/sp-dev-docs/commits/f5cfb779f4011a407bfa38ccc2f91df86202419a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-55/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6714) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102162100491431-6714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8nRDX4Jq9SKW58if642yYYxZJGpPgosiahMxi7AQosQ%3D&st=2021-02-16T20%3A57%3A00Z&se=2021-03-19T21%3A02%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[cb6eed3](https://github.com/JoanneHendrickson/sp-dev-docs/commits/cb6eed3b75f62733822ce940da3a3a1757351971)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-55/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6714) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102162101106962-6714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=itDbEr9YcdkKAW4Ads6PH%2Bg84MORXt4VBKlS6q92oy0%3D&st=2021-02-16T20%3A57%3A56Z&se=2021-03-19T21%3A02%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[3a867bc](https://github.com/JoanneHendrickson/sp-dev-docs/commits/3a867bc30be3599ab118562433673abb3c2c6df0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-55/docs/apis/migration-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-6714) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102171229510858-6714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z8ArTtIho8cWVtW%2Bw5IitRSzeWcD2KBFWBVNSqsjxM8%3D&st=2021-02-17T12%3A25%3A54Z&se=2021-03-20T12%3A30%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
