### PR TITLE
Update event-receiver-and-list-event-receiver-sharepoint-add-in.md

### PR DESCRIPTION
**Pull request by pstakuu**
Updated the link for [Overview of SharePoint Webhooks] to the correct link: https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks

Original link went to developer.microsoft.com instead of docs and didn't land on a page.

## Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.*

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this PR. Sample description or details around bugs which are being fixed.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `master` branch of this repo. Released documents are in `live` branch.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[ff4c54a](https://github.com/pstakuu/sp-dev-docs/commits/ff4c54aca14197cbbedf144a29ff63262b30a175)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/pstakuu/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in?branch=pr-en-us-6656) | [Details](#user-content-1fc0efec-80b57059)

<a id="1fc0efec-80b57059"></a>
### [docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/pstakuu/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md)
 - **Line 19, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/sharepoint/dev/apis/webhooks/overview-sharepoint-webhooks' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101291504209714-6656%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q53ii4GhkGgOLEs4DUmk7NedDa6Ttq5qc%2F3rn6syUVs%3D&st=2021-01-29T15%3A00%3A20Z&se=2021-03-01T15%3A05%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[591858e](https://github.com/pstakuu/sp-dev-docs/commits/591858e01de473ebb02617b30bf97a9bfb7607a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/pstakuu/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in?branch=pr-en-us-6656) | [Details](#user-content-1fc0efec-49082c67)

<a id="1fc0efec-49082c67"></a>
### [docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/pstakuu/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101291511547940-6656%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uK71W%2FpcuXX%2FoZKqhxjNf8sfuHDMDMS5O2jgwKcmPbU%3D&st=2021-01-29T15%3A07%3A57Z&se=2021-03-01T15%3A12%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[1646bae](https://github.com/pstakuu/sp-dev-docs/commits/1646bae9e74c6197126d62bce33d7643f7198e35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md](https://github.com/pstakuu/sp-dev-docs/blob/patch-1/docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in?branch=pr-en-us-6656) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101291529205377-6656%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tvN3ulBngIqi2oiNCo%2BNV4GLDC9FjgV2e8rz%2BurDXVk%3D&st=2021-01-29T15%3A25%3A25Z&se=2021-03-01T15%3A30%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
Closing - lots of markdown issues in this doc that needed to be fixed, the link should be relative within the repo, and submitter didn't use new PR template making it hard to process the PR. Doc fixed in other PR

**Pull request closed without merging**
