### PR TITLE
Added guidance on bundle sizes in SPFx

### PR DESCRIPTION
**Pull request by wobba**
#### Category
- [x] New article

#### What's in this Pull Request?

Added guidance on bundle sizes in SPFx

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/images/dynamic-bundling.png](https://github.com/wobba/sp-dev-docs/blob/wobba-optimize-bundle/docs/images/dynamic-bundling.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/images/dynamic-bundling.png?branch=pr-en-us-2425) |
[docs/spfx/bundle-size-guidance.md](https://github.com/wobba/sp-dev-docs/blob/wobba-optimize-bundle/docs/spfx/bundle-size-guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/bundle-size-guidance?branch=pr-en-us-2425) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808270804196171-2425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=wEkxiUrTEkfxvjiOM0DxtrelsPlVcKJPd7jw1VW09jA%3D&st=2018-08-27T08%3A01%3A36Z&se=2018-09-27T08%3A06%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\b4pc-s, target branch: master, target branch commit: 0a133b29968404a31160a70c639786efcbcdb78f, source branch: 5ea154fa1645ed19753b7b2f3f6a456d/wobba-optimize-bundle, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808270807229663-2425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=pP7lFfB2YoIH94%2BswJn8%2BM4aLgd65MbZCuoyrq4oOfA%3D&st=2018-08-27T08%3A02%3A47Z&se=2018-09-27T08%3A07%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\24vz-s, target branch: master, target branch commit: 0a133b29968404a31160a70c639786efcbcdb78f, source branch: 5ea154fa1645ed19753b7b2f3f6a456d/wobba-optimize-bundle, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808271930231485-2425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VdfYu5ySPcPR2u%2FjgPhiwf7hBkhw6diy4VNwJvewO6Q%3D&st=2018-08-27T19%3A28%3A53Z&se=2018-09-27T19%3A33%3A53Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\hacs-s, target branch: master, target branch commit: 0a133b29968404a31160a70c639786efcbcdb78f, source branch: 5ea154fa1645ed19753b7b2f3f6a456d/wobba-optimize-bundle, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808271935072206-2425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=nMRqJXCHT3Spig35%2B0O2xHBtDcMRoYQpW%2B6kSiSL6H4%3D&st=2018-08-27T19%3A30%3A34Z&se=2018-09-27T19%3A35%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\be5a-s, target branch: master, target branch commit: 0a133b29968404a31160a70c639786efcbcdb78f, source branch: 5ea154fa1645ed19753b7b2f3f6a456d/wobba-optimize-bundle, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808271941091493-2425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=8heWOAFb2m6OIchIwQjtRiSt%2BCPe%2FoZ3SAcd6qgUQrA%3D&st=2018-08-27T19%3A36%3A34Z&se=2018-09-27T19%3A41%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot sync git repo to specified state. Please make sure the pull request is mergeable. Details: Git merge results in conflict, repository remote url: https://github.com/SharePoint/sp-dev-docs, working directory: W:\p35v-s, target branch: master, target branch commit: 0a133b29968404a31160a70c639786efcbcdb78f, source branch: 5ea154fa1645ed19753b7b2f3f6a456d/wobba-optimize-bundle, source branch commit: .

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C8%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201808280625408064-2425%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=o8v0vIzbeWNLyv4e%2FSmA5oBoTed97uRXX15asOddDZs%3D&st=2018-08-28T06%3A21%3A04Z&se=2018-09-28T06%3A26%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thx Mikael, appreciated.

**Pull request merged**
