### PR TITLE
Patching issue #2939

### LINKED ISSUE #2939: [LOC] Multiple broken links
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

Due to VaaS validation we have found several articles with broken links, please find the attached Excel sheet with:
 - Article Name
 - Link to GH repo
 - _Broken link_
 - _Link Text_

**Current:** articles contains broken links
**Expected:** the links should redirect to correct page or be removed from the articles

**List of affected articles / links:**
[[LOC]_SP-Dev-Docs_BrokenLinks.xlsx](https://github.com/SharePoint/sp-dev-docs/files/2575703/LOC._SP-Dev-Docs_BrokenLinks.xlsx)

### PR DESCRIPTION
**Pull request by cakriwut**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #2939 

#### What's in this Pull Request?

> Refresh incorrect links to new location.

#### Guidance

> Fixing links in following articles:

- [Working with folders and files with rest](https://github.com/SharePoint/sp-dev-docs/blob/live/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
- [Publish SharePoint AddIns](https://github.com/SharePoint/sp-dev-docs/blob/live/docs/sp-add-ins/publish-sharepoint-add-ins.md)
- [Create a developer site on an existing Office365 Subscription](https://github.com/SharePoint/sp-dev-docs/blob/live/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md)
- [Supported and unsupported features](https://github.com/SharePoint/sp-dev-docs/blob/live/docs/general-development/supported-and-unsupported-features.md)

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[b126322](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/b1263220776430419055f505209c574ba16da0e8)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[b126322](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/b1263220776430419055f505209c574ba16da0e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/supported-and-unsupported-features.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/supported-and-unsupported-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/supported-and-unsupported-features?branch=pr-en-us-3253) |
[docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription?branch=pr-en-us-3253) |
[docs/sp-add-ins/publish-sharepoint-add-ins.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/publish-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/publish-sharepoint-add-ins?branch=pr-en-us-3253) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901130131244874-3253%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PQUk7M2iOblhyFg8AimJ5XX05zg396FXuHg3MtSeIsU%3D&st=2019-01-13T01%3A28%3A13Z&se=2019-02-13T01%3A33%3A13Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[f02f98e](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/f02f98ea3788ef7dc030c0432ac3a21d4bb10360)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[f02f98e](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/f02f98ea3788ef7dc030c0432ac3a21d4bb10360)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[f02f98e](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/f02f98ea3788ef7dc030c0432ac3a21d4bb10360)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.vs/slnx.sqlite](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/.vs/slnx.sqlite) | :white_check_mark:Succeeded | |
[.vs/sp-dev-docs/v15/.suo](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/.vs/sp-dev-docs/v15/.suo) | :white_check_mark:Succeeded | |
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-3253) |
[docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering?branch=pr-en-us-3253) |
[docs/general-development/supported-and-unsupported-features.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/supported-and-unsupported-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/supported-and-unsupported-features?branch=pr-en-us-3253) |
[docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription?branch=pr-en-us-3253) |
[docs/sp-add-ins/publish-sharepoint-add-ins.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/publish-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/publish-sharepoint-add-ins?branch=pr-en-us-3253) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901130242480638-3253%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ot51R3cgaJaWjo4IcdEwckgW19Qdnqo4G5qKxLETpao%3D&st=2019-01-13T02%3A39%3A34Z&se=2019-02-13T02%3A44%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[18a3294](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/18a3294ea0083976eb105fd42d7af3a579926020)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[18a3294](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/18a3294ea0083976eb105fd42d7af3a579926020)_: 

:clock10: **Incremental building**: average incremental building time is _44 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[18a3294](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/18a3294ea0083976eb105fd42d7af3a579926020)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.vs/slnx.sqlite](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/.vs/slnx.sqlite) | :white_check_mark:Succeeded | |
[.vs/sp-dev-docs/v15/.suo](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/.vs/sp-dev-docs/v15/.suo) | :white_check_mark:Succeeded | |
[docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-external-data-with-rest-in-sharepoint?branch=pr-en-us-3253) |
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-3253) |
[docs/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint?branch=pr-en-us-3253) |
[docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering?branch=pr-en-us-3253) |
[docs/general-development/sharepoint-online-suite-navigation-control.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/sharepoint-online-suite-navigation-control.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-online-suite-navigation-control?branch=pr-en-us-3253) |
[docs/general-development/supported-and-unsupported-features.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/supported-and-unsupported-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/supported-and-unsupported-features?branch=pr-en-us-3253) |
[docs/general-development/virtual-directories-in-sharepoint-solutions.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/virtual-directories-in-sharepoint-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/virtual-directories-in-sharepoint-solutions?branch=pr-en-us-3253) |
[docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription?branch=pr-en-us-3253) |
[docs/sp-add-ins/publish-sharepoint-add-ins.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/publish-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/publish-sharepoint-add-ins?branch=pr-en-us-3253) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901130439584209-3253%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PStx%2Fd6z4P4jjqf%2BEZKm9uqxsfejlqjo18PG%2BdulM5Q%3D&st=2019-01-13T04%3A36%3A47Z&se=2019-02-13T04%3A41%3A47Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[1fe87ce](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/1fe87ce8a4d561d21b61aacbd6c1ca78441216f6)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[1fe87ce](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/1fe87ce8a4d561d21b61aacbd6c1ca78441216f6)_: 

:clock10: **Incremental building**: average incremental building time is _44 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[1fe87ce](https://github.com/cakriwut/sp-dev-docs/pull/3253/commits/1fe87ce8a4d561d21b61aacbd6c1ca78441216f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.vs/slnx.sqlite](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/.vs/slnx.sqlite) | :white_check_mark:Succeeded | |
[.vs/sp-dev-docs/v15/.suo](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/.vs/sp-dev-docs/v15/.suo) | :white_check_mark:Succeeded | |
[docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-external-data-with-rest-in-sharepoint?branch=pr-en-us-3253) |
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-3253) |
[docs/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-an-add-in-scoped-external-content-type-in-sharepoint?branch=pr-en-us-3253) |
[docs/general-development/how-to-create-and-delete-posts-and-retrieve-the-social-feed-by-using-the-net-cli.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-create-and-delete-posts-and-retrieve-the-social-feed-by-using-the-net-cli.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-and-delete-posts-and-retrieve-the-social-feed-by-using-the-net-cli?branch=pr-en-us-3253) |
[docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering?branch=pr-en-us-3253) |
[docs/general-development/sharepoint-add-ins-compared-with-sharepoint-solutions.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/sharepoint-add-ins-compared-with-sharepoint-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-add-ins-compared-with-sharepoint-solutions?branch=pr-en-us-3253) |
[docs/general-development/sharepoint-online-suite-navigation-control.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/sharepoint-online-suite-navigation-control.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-online-suite-navigation-control?branch=pr-en-us-3253) |
[docs/general-development/supported-and-unsupported-features.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/supported-and-unsupported-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/supported-and-unsupported-features?branch=pr-en-us-3253) |
[docs/general-development/virtual-directories-in-sharepoint-solutions.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/virtual-directories-in-sharepoint-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/virtual-directories-in-sharepoint-solutions?branch=pr-en-us-3253) |
[docs/general-development/what-s-new-for-developers-in-social-and-collaboration-features-in-sharepoint-201.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/what-s-new-for-developers-in-social-and-collaboration-features-in-sharepoint-201.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-for-developers-in-social-and-collaboration-features-in-sharepoint-201?branch=pr-en-us-3253) |
[docs/general-development/workflow-initiation-and-configuration-properties.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/general-development/workflow-initiation-and-configuration-properties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/workflow-initiation-and-configuration-properties?branch=pr-en-us-3253) |
[docs/solution-guidance/yammer-integration-sharepoint-add-in.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/solution-guidance/yammer-integration-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/yammer-integration-sharepoint-add-in?branch=pr-en-us-3253) |
[docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-developer-site-on-an-existing-office-365-subscription?branch=pr-en-us-3253) |
[docs/sp-add-ins/publish-sharepoint-add-ins.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2939/docs/sp-add-ins/publish-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/publish-sharepoint-add-ins?branch=pr-en-us-3253) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901130553516607-3253%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=s7tAzWg1q9A8KNgtzbqeThoTSUdJ7GFGXzmfCngPIs8%3D&st=2019-01-13T05%3A50%3A54Z&se=2019-02-13T05%3A55%3A54Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @cakriwut, appreciated.

**Pull request merged**
