### PR TITLE
Adding link to modern Site Templates documentation

### LINKED ISSUE #7492: How to create templates for SharePoint Online Modern Sites
[Enter feedback here]
Hi.  This page says that creating templates is not supported in SharePoint Online (modern sites).  Given most people should now be working with SharePoint Online modern sites, this would be the most useful information!  Could you add a cross-reference to how to do the equivalent for SharePoint Online modern sites please.

Thanks, Oz

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 90e5f465-6d87-5a7d-9b0a-7807da51d30b
* Version Independent ID: bc4f4c42-d5ba-a36a-1578-70103e14cde8
* Content: [Save, download, and upload a SharePoint site as a template](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template)
* Content Source: [docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

### PR DESCRIPTION
**Pull request by bcameron1231**
Adding link for SPO to Site Templates and Site Scripts

Fixes #7492

## Category

- [x] Content fix

## Related issues

- fixes #7492 

## What's in this Pull Request?

Added new documentation link

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[ab214e0](https://github.com/bcameron1231/sp-dev-docs/commits/ab214e0dfc4dce260c3772a36bb96d4e0b4502d6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-16/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template?branch=pr-en-us-7496) | [Details](#user-content-64042bc916a6a82ec2c7521351f67c3d-48c2d425)

<a id="64042bc916a6a82ec2c7521351f67c3d-48c2d425"></a>
### [docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-16/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md)
 - **Line 14, Column 159**: **[Warning: hard-coded-locale - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 14, Column 159**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-overview' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C11%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111111940566499-7496%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-12T19%3A41%3A54Z&sr=b&sp=r&sig=D7Wo3cb8DXptJVtR4XGW0Idumt27%2FsHarmef1Tg59s8%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[201dcd6](https://github.com/bcameron1231/sp-dev-docs/commits/201dcd65696e53f799bcdef6996ee9ee37cd004c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-16/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template?branch=pr-en-us-7496) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C12%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111120215198649-7496%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-13T02%3A16%3A41Z&sr=b&sp=r&sig=uiN%2FwJezrO8TgV8r8PakC6a68iT1v%2FnBA%2BLzA4BH3IE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
TY... in the future, please update the doc's date in the frontmatter to reflect when the doc was updated.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[1a97d23](https://github.com/bcameron1231/sp-dev-docs/commits/1a97d2373ef7a05cf9cc0c64601911e47ee7ca71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-16/docs/general-development/save-download-and-upload-a-sharepoint-site-as-a-template.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/save-download-and-upload-a-sharepoint-site-as-a-template?branch=pr-en-us-7496) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C16%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202111161106527442-7496%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-17T11%3A07%3A59Z&sr=b&sp=r&sig=mKfqW3DB2x7mn5mf1GmpLXwTDibZLY5Wr%2BAWU6F76jQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
