### PR TITLE
Fix spelling/wording issues and broken URLs in understanding-aad-and-oauth-for-spo-modern.md

### PR DESCRIPTION
**Pull request by JLRishe**
## Category

- [X] Content fix
- [ ] New article

## What's in this Pull Request?

While reading the article at https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins-modernize/understanding-aad-and-oauth-for-spo-modern, I noticed a few spelling and wording issues, a broken image, and a broken documentation link. I am proposing improvements to those in this PR.

### CODE REVIEW

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Thanks for the submission, but some edits are required before we can merge this

**Comment by JLRishe** [comment]
@andrewconnell I've made the requested change. I also removed the quotes around "jwt.ms" in the link to that site. Hopefully that was the right thing to do.

**Comment by andrewconnell** [comment]
@JLRishe said:

> BTW, I can see that there are validation errors regarding locale codes and absolute documentation URLs in links that were present before my edits. I imagine the absolute URLs are intentional since they're from a different department, but should I remove the locale code portions of the URLs?

Yes, those should be fixed if you can fix those. Those rules were put in place after the content was published (or someone who predated me just ignored it). I'm involved in the PRs to ensure quality as I clean up old issues like this, so it would be preferred if you fix those.

We're NEVER supposed to include the locale UNLESS the page doesn't render without it. Also, we're never supposed to use absolute links for `learn.microsoft.com`. So if you can fix those 6 warnings, that would be great. Thanks!

**Comment by JLRishe** [comment]
@andrewconnell Ok, I have changed those URLs. I used server-relative URLs (i.e. starting with a slash), which is hopefully the right approach. I can see that the URLs within the SharePoint documentation are using `../`, etc.

I also noticed that doc URLs were going through some alias redirect on account of the Azure AD -> Entra ID renaming, so I have updated them to the newer versions of those URLs:

- BEFORE: `/azure/active-directory/develop/msal-overview`; AFTER: `/entra/identity-platform/msal-overview`
- BEFORE: `/azure/active-directory/develop/microsoft-identity-web`; AFTER: `/entra/msal/dotnet/microsoft-identity-web`

**Pull request merged**
