### PR TITLE
Grammatical updates and corrections

### PR DESCRIPTION
**Pull request by thechriskent**
| Q                   | A
| ---------------     | ---
| content fix?        | Yes
| New article?        | No
| Related issues?     | No

#### What's in this Pull Request?

- Minor Grammatical Updates
- Fixed instances where `@currentField.Title` was used
- Added additional operators
  - toLocaleString()
  - toLocaleDateString()
  - toLocaleTimeString()
- Removed jobTitle and department from people fields since these are NOT returned
- Added note about Person field's Show Field setting affecting `@currentField.title`
- Added an example of conditional formatting with the `@me` keyword

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/thechriskent/sp-dev-docs/blob/patch-17/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711212030295546-1072%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Qp7166p4AgnquOUaS4I9zB4GbkkxkMqJtyBizZkb3oY%3D&st=2017-11-21T20%3A26%3A29Z&se=2017-12-22T20%3A31%3A29Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Cannot merge commit 14d1b184c08f9910a76cceb954ac6eea1667bb5a in branch patch-17 of repository https://github.com/thechriskent/sp-dev-docs into branch master (commit b2f655b80661985bdd04c4a7e0106a972cf771aa)

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C21%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711212147263249-1072%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Sqvy86zwUBxeH%2BciZbU9RComfaWv1Om4YNUDBrKSO70%3D&st=2017-11-21T21%3A42%3A31Z&se=2017-12-22T21%3A47%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/thechriskent/sp-dev-docs/blob/patch-17/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C24%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711241234379165-1072%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=e20eBwDOmnZ7kFvXnTwUxweHcc26OX29ibtv%2FOQ9IWc%3D&st=2017-11-24T12%3A30%3A32Z&se=2017-12-25T12%3A35%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thx Chris, appreciated.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/column-formatting.md](https://github.com/thechriskent/sp-dev-docs/blob/patch-17/docs/declarative-customization/column-formatting.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C24%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711241235444643-1072%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=asOTegzme8iGZWMpFGcpcTgXPKinjOkGyskRxlonErA%3D&st=2017-11-24T12%3A31%3A40Z&se=2017-12-25T12%3A36%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
