### PR TITLE
Removing incorrect link

### LINKED ISSUE #2702: [LOC] Invalid links in an article (build-mobile-apps-for-other-platforms-using-sharepoint.md)
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Repro steps:**
1. Go to https://docs.microsoft.com/en-us/sharepoint/dev/general-development/build-mobile-apps-for-other-platforms-using-sharepoint (or GH https://github.com/SharePoint/sp-dev-docs/blob/master/docs/general-development/build-mobile-apps-for-other-platforms-using-sharepoint.md)
2. Search link text from table below
3. Click the links --> 404 error page

**Affected links:**

Link   Text | Link URL
-- | --
Making REST calls with C# and JavaScript   for SharePoint | http://www.microsoft.com/resources/msdn/en-us/office/media/video/videol?cid=sdc&from=mscomsdc&VideoID=4e4cc094-ff69-405b-852f-2ac7c41293c5
Making REST calls with C# and JavaScript   for SharePoint demo | http://www.microsoft.com/resources/msdn/en-us/office/media/video/videol?cid=sdc&from=mscomsdc&VideoID=b1e7c9c5-0f62-4a78-bb7b-8e283c86145c

image

### PR DESCRIPTION
**Pull request by cakriwut**
#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #2702 

#### What's in this Pull Request?

> Remove incorrect link in the _See also_ section. Other references already provide wide range of examples.

#### Guidance

> Remove incorrect link in the _See also_ section.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[04c8ede](https://github.com/cakriwut/sp-dev-docs/pull/3251/commits/04c8edec474e637ca9421df19bdb7639796e27b5)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[04c8ede](https://github.com/cakriwut/sp-dev-docs/pull/3251/commits/04c8edec474e637ca9421df19bdb7639796e27b5)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[04c8ede](https://github.com/cakriwut/sp-dev-docs/pull/3251/commits/04c8edec474e637ca9421df19bdb7639796e27b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/build-mobile-apps-for-other-platforms-using-sharepoint.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2702/docs/general-development/build-mobile-apps-for-other-platforms-using-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-mobile-apps-for-other-platforms-using-sharepoint?branch=pr-en-us-3251) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C12%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901121451585128-3251%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=VzF1wxosze44I8dI59b%2BKKdchqH7MHoPBCubbM621Nk%3D&st=2019-01-12T14%3A48%3A48Z&se=2019-02-12T14%3A53%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx @cakriwut, appreciated.

**Pull request merged**
