### PR TITLE
Update working-with-get-items-and-get-files.md

### PR DESCRIPTION
**Pull request by sunar91**
Added a known limitation  on the Get items action at the end to preempt user confusion.

## Category

- [x] Content fix
- [ ] New article
- [ ] Example checked item 

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?
Added a known limitation  on the Get items action at the end to preempt user confusion.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[a67d8ff](https://github.com/sunar91/sp-dev-docs/commits/a67d8ffbaf8ab4d0d72e4b2159915d2eec123532)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/working-with-get-items-and-get-files?branch=pr-en-us-8209) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206200026564653-8209/BuildReport?accessString=00653881f3354acb7102e058968809faa7e5d035986f94219d579aea957b0c1d).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — CHANGES_REQUESTED** [review]
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

**Comment by sunar91** [comment]
Updated the ms.date @andrewconnell Thanks!

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[e2a8ca4](https://github.com/sunar91/sp-dev-docs/commits/e2a8ca4201ccf092279b6f9c8e06d1113eaecbac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/business-apps/power-automate/guidance/working-with-get-items-and-get-files.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/working-with-get-items-and-get-files?branch=pr-en-us-8209) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201844209925-8209/BuildReport?accessString=aabe49aa53f7a51084c1bedd9558bf1cb2fe150787e5ecfd2cb63f3bc7587775).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
