### PR TITLE
Update building-simple-field-customizer.md

### PR DESCRIPTION
**Pull request by aurasa**
#### Category
- [X] Content fix
- [ ] New article

#### What's in this Pull Request?
Corrected Heading for [Deploy the field to SharePoint Online and host JavaScript from local host](/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-field-customizer.md#deploy-the-field-to-sharepoint-online-and-host-javascript-from-local-host): Other than the heading states, the assets are not hosted on localhost but on SharePoint online

#### Guidance
Missleading Heading on building-simple-field-customizer.md was corrected

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[866cc1a](https://github.com/aurasa/sp-dev-docs/pull/3213/commits/866cc1a9feb4fc711aa7a359ffe88fa855032d74)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[866cc1a](https://github.com/aurasa/sp-dev-docs/pull/3213/commits/866cc1a9feb4fc711aa7a359ffe88fa855032d74)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[866cc1a](https://github.com/aurasa/sp-dev-docs/pull/3213/commits/866cc1a9feb4fc711aa7a359ffe88fa855032d74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/aurasa/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer?branch=pr-en-us-3213) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C7%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901071545549276-3213%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=EnZzLVsm9PmsMWUImCazd1958P1AkscZwhK6D4ifXgI%3D&st=2019-01-07T15%3A42%3A42Z&se=2019-02-07T15%3A47%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thanks @aurasa, appreciated. Clearly leftovers from the previous versions of the tutorial, which should not be there anymore.

**Pull request merged**
