### PR TITLE
Ajford76 patch 1

### PR DESCRIPTION
**Pull request by ajford76**
#### Category
- [ ] Content fix
- [x ] New article
- Related issues: Semantic slot color

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[68b94c0](https://github.com/ajford76/sp-dev-docs/pull/3108/commits/68b94c0babbcf656ea2a604cda06646b7c5ad05e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/designing-a-web-part-icon.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/designing-a-web-part-icon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/designing-a-web-part-icon?branch=pr-en-us-3108) |
[docs/design/layout-patterns.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/layout-patterns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/layout-patterns?branch=pr-en-us-3108) |
[docs/design/semantic_slots.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/semantic_slots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/design/themes-colors.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/themes-colors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/themes-colors?branch=pr-en-us-3108) |
[docs/design/web-part-levels.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/web-part-levels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/web-part-levels?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-1.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-2.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812130902466298-3108%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=DnXdwk7ssr2GkHTh2kBlCVtZqxAr%2FHM06OavgQnxx6M%3D&st=2018-12-13T08%3A59%3A37Z&se=2019-01-13T09%3A04%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[3c11225](https://github.com/ajford76/sp-dev-docs/pull/3108/commits/3c11225feb2fcd2c7bd2f17f70bc2a784aa9efbd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/designing-a-web-part-icon.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/designing-a-web-part-icon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/designing-a-web-part-icon?branch=pr-en-us-3108) |
[docs/design/layout-patterns.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/layout-patterns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/layout-patterns?branch=pr-en-us-3108) |
[docs/design/semantic_slots.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/semantic_slots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/design/themes-colors.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/themes-colors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/themes-colors?branch=pr-en-us-3108) |
[docs/design/web-part-levels.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/web-part-levels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/web-part-levels?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-1.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-2.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-940px-table.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-940px-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/images/doc-semantic-slot-940px-table.png?branch=pr-en-us-3108) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812140316551697-3108%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Uw8O66tb1oEJxJFuw2kUN1w39WnWiQrekwGrXspF87M%3D&st=2018-12-14T03%3A13%3A52Z&se=2019-01-14T03%3A18%3A52Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b1fd2a](https://github.com/ajford76/sp-dev-docs/pull/3108/commits/0b1fd2a15eb3b7d3812b1eff1aff698259dc4beb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/designing-a-web-part-icon.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/designing-a-web-part-icon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/designing-a-web-part-icon?branch=pr-en-us-3108) |
[docs/design/layout-patterns.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/layout-patterns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/layout-patterns?branch=pr-en-us-3108) |
[docs/design/semantic_slots.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/semantic_slots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/design/themes-colors.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/themes-colors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/themes-colors?branch=pr-en-us-3108) |
[docs/design/web-part-levels.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/web-part-levels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/web-part-levels?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-1.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-2.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-940px-table.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-940px-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812140452368820-3108%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=PLEl2Pu3bMl2%2FYLDpmYfsmS0w%2BfOuRSeRV8VajJccdY%3D&st=2018-12-14T04%3A49%3A31Z&se=2019-01-14T04%3A54%3A31Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ajford76** [comment]
Added semantic slot article for review. @Lauragra @VesaJuvonen

**Comment by VesaJuvonen** [comment]
@ajford76 - was closing this intentional? As in - we should not care of this and there will be a new PR?

**Comment by VesaJuvonen** [comment]
Just follow up on this @ajford76 - was this intentionally closed? These changes were not merged even though you requested a review as you closed the PR... was that an accident?

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b1fd2a](https://github.com/ajford76/sp-dev-docs/pull/3108/commits/0b1fd2a15eb3b7d3812b1eff1aff698259dc4beb)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by ajford76** [comment]
Request to merge Semantic slot article with master.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b1fd2a](https://github.com/ajford76/sp-dev-docs/pull/3108/commits/0b1fd2a15eb3b7d3812b1eff1aff698259dc4beb)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[0b1fd2a](https://github.com/ajford76/sp-dev-docs/pull/3108/commits/0b1fd2a15eb3b7d3812b1eff1aff698259dc4beb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/design/designing-a-web-part-icon.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/designing-a-web-part-icon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/designing-a-web-part-icon?branch=pr-en-us-3108) |
[docs/design/layout-patterns.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/layout-patterns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/layout-patterns?branch=pr-en-us-3108) |
[docs/design/semantic_slots.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/semantic_slots.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/design/themes-colors.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/themes-colors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/themes-colors?branch=pr-en-us-3108) |
[docs/design/web-part-levels.md](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/design/web-part-levels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/web-part-levels?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-1.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-1.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-2.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |
[docs/images/doc-semantic-slot-940px-table.png](https://github.com/ajford76/sp-dev-docs/blob/ajford76-patch-1/docs/images/doc-semantic-slot-940px-table.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/design/semantic_slots?branch=pr-en-us-3108) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C20%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812201707307193-3108%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2BqqDp1svOl0X43D9qNTGhDjmDV2bdKcUsoSJ2xg%2Bg3g%3D&st=2018-12-20T17%3A04%3A25Z&se=2019-01-20T17%3A09%3A25Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
Thx Adam, I will also add the semantic slots to TOC so that it's truly live.

**Pull request merged**
