### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
Fixing the broken link in line 61 and line 68

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[972f77e](https://github.com/DhurataJ/sp-dev-docs/commits/972f77e9d97ddc0812a83d9e2142bbc292ac3ea0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/site-creation-rest.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-2/docs/apis/site-creation-rest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest?branch=pr-en-us-7870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204062102057789-7870%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T21%3A03%3A16Z&sr=b&sp=r&sig=0BY3SVNYk77hWDoubGkvAHbllKdAU7LwefoXFL%2BstLE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[8822f95](https://github.com/DhurataJ/sp-dev-docs/commits/8822f9513e52f76a1fdf78ad32ef5ae3726d6026)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/site-creation-rest.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-2/docs/apis/site-creation-rest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest?branch=pr-en-us-7870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204062102247338-7870%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T21%3A04%3A16Z&sr=b&sp=r&sig=KR2qZ2C9YdGybP%2FbqbvwX1V2aQwDXU5Ve%2BRbMa%2B%2FmiY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by DhurataJ** [comment]
Hi @andrewconnell,

Since changes happened upstream from the other closed PR, created a new PR by resubmit the changes, please can you review and merge.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[c49184b](https://github.com/DhurataJ/sp-dev-docs/commits/c49184bcfc81ee431961e7fab1380292b835f108)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/site-creation-rest.md](https://github.com/DhurataJ/sp-dev-docs/blob/patch-2/docs/apis/site-creation-rest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/site-creation-rest?branch=pr-en-us-7870) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C6%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202204062107366787-7870%5Cworkflow_report.html?sv=2020-08-04&se=2022-05-07T21%3A08%3A33Z&sr=b&sp=r&sig=0z5kJLuyUZfjF6epJ4FukneBe3CoZ25lB92kjDhISzI%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
