### PR TITLE
Added docs with Thumbnails, LoopIndex and Multivalue field operations in Custome Formatter

### PR DESCRIPTION
**Pull request by niketjain2020**
#### Category
- [ ] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

> For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### What's in this Pull Request?

> Please describe the changes in this PR. Sample description or details around bugs which are being fixed.
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

#### Guidance

> *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
> 
> *Please target your PR to 'master' branch. Released documents are in `live` branch.*
> 
> _(DELETE THIS PARAGRAPH AFTER READING)_

### CODE REVIEW

**Comment by niketjain2020** [comment]
@VesaJuvonen can you please review and Merge

**Comment by VesaJuvonen** [comment]
thx @niketjain2020, appreciated.

**Comment by niketjain2020** [comment]
Thanks @Vesa Juvonen<mailto:Vesa.Juvonen@microsoft.com> though the images didn’t come properly, have raised another PR<https://github.com/SharePoint/sp-dev-docs/pull/3569> for the same.

Thanks!

**Comment by niketjain2020** [comment]
Thx Niket,
PR processed. Few things to adjust for any future submissions:


  *   Ensure that your account has been linked with your MS account - by going to following location - https://opensource.microsoft.com/link
     *   Please see more details on this requirement for ALL MSFTs from our open-source guidance - https://docs.opensource.microsoft.com/github/linking.html
  *   Please update the PR template - as - we cannot skip this requirement for MSFTs if we demand that frohttps://docs.opensource.microsoft.com/github/linking.htmlm our MVPs and other contributors - we as Microsoft employees have to set an example... not use shortcuts. As we don't accept properly formatted PRs from non-MSFTs, we cannot accept them from MSFTs

Best regards,
Vesa Juvonen

Principal Program Manager
OneDrive - SharePoint Engineering
Microsoft Certified Solutions Master: SharePoint
Ready to use SharePoint and Office 365 development Patterns and Practices from http://aka.ms/sppnp

From: Niket Jain <Jain.Niket@microsoft.com>
Sent: maanantai 11. maaliskuuta 2019 8.54
To: SharePoint/sp-dev-docs <reply@reply.github.com>; SharePoint/sp-dev-docs <sp-dev-docs@noreply.github.com>; Vesa Juvonen <Vesa.Juvonen@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [SharePoint/sp-dev-docs] Added docs with Thumbnails, LoopIndex and Multivalue field operations in Custome Formatter (#3560)

Thanks @Vesa Juvonen<mailto:Vesa.Juvonen@microsoft.com> though the images didn't come properly, have raised another PR<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSharePoint%2Fsp-dev-docs%2Fpull%2F3569&data=02%7C01%7CVesa.Juvonen%40microsoft.com%7Ccfdd71adbddb41c3f32308d6a5ee5d2a%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636878840529510655&sdata=hgrXzVpoBAOp9ipDHETq9HycH4zoeqsGqHdvV8u%2Fw1E%3D&reserved=0> for the same.

Thanks!

**Comment by niketjain2020** [comment]
Thanks Vesa, have already linked my accounts.

Sure will fill up the PR form.

Thanks!

From: Vesa Juvonen <Vesa.Juvonen@microsoft.com>
Sent: Monday, March 11, 2019 12:55 PM
To: Niket Jain <Jain.Niket@microsoft.com>; SharePoint/sp-dev-docs <reply@reply.github.com>; SharePoint/sp-dev-docs <sp-dev-docs@noreply.github.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [SharePoint/sp-dev-docs] Added docs with Thumbnails, LoopIndex and Multivalue field operations in Custome Formatter (#3560)

Thx Niket,
PR processed. Few things to adjust for any future submissions:


  *   Ensure that your account has been linked with your MS account - by going to following location - https://opensource.microsoft.com/link<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopensource.microsoft.com%2Flink&data=02%7C01%7CJain.Niket%40microsoft.com%7Cd58a4a9bc2fd4e88152a08d6a5f2a942%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636878858993594433&sdata=kJzTTWtvyRee6ido44DNeQeTAOgPnjDjhtzju1pI2I0%3D&reserved=0>
     *   Please see more details on this requirement for ALL MSFTs from our open-source guidance - https://docs.opensource.microsoft.com/github/linking.html<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.opensource.microsoft.com%2Fgithub%2Flinking.html&data=02%7C01%7CJain.Niket%40microsoft.com%7Cd58a4a9bc2fd4e88152a08d6a5f2a942%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636878858993604428&sdata=fkTZGY6lf7giYDqtqBZBe2KRnR00xPHqlx8%2F3muYyzU%3D&reserved=0>
  *   Please update the PR template - as - we cannot skip this requirement for MSFTs if we demand that frohttps://docs.opensource.microsoft.com/github/linking.htmlm our MVPs and other contributors - we as Microsoft employees have to set an example... not use shortcuts. As we don't accept properly formatted PRs from non-MSFTs, we cannot accept them from MSFTs

Best regards,
Vesa Juvonen

Principal Program Manager
OneDrive - SharePoint Engineering
Microsoft Certified Solutions Master: SharePoint
Ready to use SharePoint and Office 365 development Patterns and Practices from http://aka.ms/sppnp

From: Niket Jain <Jain.Niket@microsoft.com<mailto:Jain.Niket@microsoft.com>>
Sent: maanantai 11. maaliskuuta 2019 8.54
To: SharePoint/sp-dev-docs <reply@reply.github.com<mailto:reply@reply.github.com>>; SharePoint/sp-dev-docs <sp-dev-docs@noreply.github.com<mailto:sp-dev-docs@noreply.github.com>>; Vesa Juvonen <Vesa.Juvonen@microsoft.com<mailto:Vesa.Juvonen@microsoft.com>>
Cc: Assign <assign@noreply.github.com<mailto:assign@noreply.github.com>>
Subject: RE: [SharePoint/sp-dev-docs] Added docs with Thumbnails, LoopIndex and Multivalue field operations in Custome Formatter (#3560)

Thanks @Vesa Juvonen<mailto:Vesa.Juvonen@microsoft.com> though the images didn't come properly, have raised another PR<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSharePoint%2Fsp-dev-docs%2Fpull%2F3569&data=02%7C01%7CJain.Niket%40microsoft.com%7Cd58a4a9bc2fd4e88152a08d6a5f2a942%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636878858993614425&sdata=e6X0cd14gIF%2BMU77zO0F0cQxbmT%2FCJsk2yo9Q6HFoe8%3D&reserved=0> for the same.

Thanks!

**Pull request merged**
