### PR TITLE
Customize SharePoint page approvals to meet your needs

### PR DESCRIPTION
**Pull request by jackwi-alt**
#### Category
[x] New article

#### What's in this Pull Request?
A new article that will go under the Guidance section for Power Automate. The article is about customizing SharePoint page approvals.

### CODE REVIEW

**Comment by andrewconnell** [comment]
Where would this go.... there's no inclusion in the TOC or cross-linked from another page. In addition, it's the "policy" of this repo to not accept PR's that don't complete the new PR template provided. Please correct and resubmit. Thanks!

**Comment by chakkaradeep** [comment]
@andrewconnell This is a PR for product documentation managed by the product team. While this PR may not have the right inclusions in the details, @jackwi-alt  and I are in contact and working together, and @jackwi-alt has added me as the reviewer to this PR as well. 

In the future, it would be better to @ mention the reviewer, ask for more details, than just close the PR as you might not know what is happening behind the scenes within the product team.

Thank you!

**Comment by andrewconnell** [comment]
Sorry... I had replied to previous PR's & not received responses. Maybe I misunderstood a recent discussion with @VesaJuvonen, but my understanding was we wouldn't accept PRs without the minimal information.

**Comment by VesaJuvonen** [comment]
Hi @chakkaradeep and @jackwi-alt - we have requested our MVPs/vendors to require baseline submissions from all people who submit PRs - as if we provide exceptions for Microsoft submissions, we cannot demand higher quality from others in the community. Filling the PR form takes 2 min - so should not be an issue and I'd love that we all would work under the same rules - as we should be the example for the community by showing how to contribute.

Asking few mins more time for filling the PR as requested does not seem that unreasonable for anyone. Makes sense?

**Comment by chakkaradeep** [comment]
@VesaJuvonen Completely agree, but lets do follow up with PR owners and reviewers than closing the PR. In cases where we lack information, lets ask PR owner/reviewer to add more information.

**Comment by andrewconnell** [comment]
@chakkaradeep will do... only reason I started doing it this way is it seemed every time I was leaving a comment on the PR to a MSFT author, no one was responding and it would sit there (this has been going on for months). Closing it was the only way to get their attention & respond. The author of a PR is on the notification chain when someone replies, so an @mention isn't really necessary...

**Comment by VesaJuvonen** [comment]
Can we address the broken links on this one, before merging live. Thx.

**Comment by VesaJuvonen** [comment]
Happy to help as needed, just let me know.

**Comment by jackwi-alt** [comment]
Vesa: Precisely, what links are broken?

**Comment by VesaJuvonen** [comment]
This is from the Build report. Something to fix as these will be reported as part of all builds. Build reports are generated with all merges which then start the docs build process for validating the merged docs. These are also generated for all PRs which is a great way to check the status even before merging.

—-

Please see 3 more validated files in report below. 
 
docs/business-apps/power-automate/guidance/customize-page-approvals.md
Line 15: [Warning] Invalid file link:(~/business-apps/power-automate/guidance/handle-news-posts).
Line 17: [Warning] Invalid file link:(~/business-apps/power-automate/guidance/parallel-approvals).
Line 16: [Warning] Invalid file link:(~/business-apps/power-automate/guidance/auto-approve-pages).

**Comment by VesaJuvonen** [comment]
As we have other pending things to get out, fixed this quickly now. There were few issues on the submission:

- Unnecessary TOC for the page, which is auto-generated by docs platform
- TOC contained broken links which did not work
- One of the four images had broken path in it - fixed now

Provided fixes are at https://github.com/SharePoint/sp-dev-docs/commit/91ab57d0ad5b9699d3f6a9024a94c8e5224a4c6d

I'd strongly recommend installing https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-authoring-pack as that provides great check tooling for the doc edits. Reduces possibility of small issues here and there.

For MSFTs or v-accounts - great resource for would be following - https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-tools?branch=master

If there's any further questions on the tooling, process, etc. Let me know.

**Pull request merged**
