### PR TITLE
Remove Line-breaks in code

### LINKED ISSUE #7078: Code samples not correct
Examples and code don't match. Especially column formatting is applied, but not present in these code examples.
Also, code samples are formatted for readability, but will not be accapted by SPO.
Example:  "Color coded group header" and  "Color coded group header with aggregate" is not just View formatting, but also column formatting to decorate the City column
Also, the lines with "`=if(@group.fieldData ...`" should appear on one line, and the parentheses are unbalanced (closing ')' is missing)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 002a1ee9-dc9f-8dc1-6f3c-ef23297b83d4
* Version Independent ID: 82565c7e-b264-94f5-8708-d4757482e133
* Content: [Use view formatting to customize SharePoint](https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting)
* Content Source: [docs/declarative-customization/view-formatting.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/declarative-customization/view-formatting.md)
* Product: **sharepoint**
* GitHub Login: @VesaJuvonen
* Microsoft Alias: **vesaj**

### PR DESCRIPTION
**Pull request by Jwaegebaert**
## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #7078 

## What's in this Pull Request?

JSON Doesn't allow line-breaks. 
Meaning when a user copies a code example and uses it within SPO they will get an error.
I removed the line-breaks and added an extra ')' to the strings because they were missing one closing char.

There is a side effect to this fix. It diminshes the readability of the example.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[5c9d581](https://github.com/Jwaegebaert/sp-dev-docs/commits/5c9d5818759dd4423b3c51762c91ab5c70835dc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/view-formatting.md](https://github.com/Jwaegebaert/sp-dev-docs/blob/patch-1/docs/declarative-customization/view-formatting.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting?branch=pr-en-us-7300) | [Details](#user-content-fb5713e9dcc2d94ce97edac0dc112a95-69596f96)

<a id="fb5713e9dcc2d94ce97edac0dc112a95-69596f96"></a>
### [docs/declarative-customization/view-formatting.md](https://github.com/Jwaegebaert/sp-dev-docs/blob/patch-1/docs/declarative-customization/view-formatting.md)
 - **Line 39, Column 78**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#style-guidelines' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 39, Column 216**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 754, Column 212**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 791, Column 230**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 799, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 803, Column 226**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 829, Column 101**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#special-string-values' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 866, Column 106**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#foreach' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C7%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109071407443618-7300%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=GA%2BYy3WL0j%2FPR6%2BAw4Jcwv4KfwtYZ%2BcDtGiG1hGWLIE%3D&st=2021-09-07T14%3A04%3A04Z&se=2021-10-08T14%3A09%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by andrewconnell** [comment]
There are a few things we need to address before we can merge this... can you assist?

- while you can't have line breaks in a real JSON doc, the point of this page is *documentation* which means the reader has to be able to understand it... so we need to leave the line breaks in there for readability. but maybe put a note using the MSDOCS note format right before the block indicating line breaks have been added for readability
- can definitely add the missing `)` to the docs
- as you can see from the build report, for this to get merged, all absolute links to `docs.microsoft.com` must be removed... only relative links can be used

can you address these things?

**Review by andrewconnell — CHANGES_REQUESTED** [review]
Please see the comment I left in the main thread of this PR...

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[6b9e3e4](https://github.com/Jwaegebaert/sp-dev-docs/commits/6b9e3e4ad585a61f674bde192b4653dc1b70ff7d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/view-formatting.md](https://github.com/Jwaegebaert/sp-dev-docs/blob/patch-1/docs/declarative-customization/view-formatting.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting?branch=pr-en-us-7300) | [Details](#user-content-fb5713e9dcc2d94ce97edac0dc112a95-10c5dbed)

<a id="fb5713e9dcc2d94ce97edac0dc112a95-10c5dbed"></a>
### [docs/declarative-customization/view-formatting.md](https://github.com/Jwaegebaert/sp-dev-docs/blob/patch-1/docs/declarative-customization/view-formatting.md)
 - **Line 39, Column 78**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#style-guidelines' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 39, Column 216**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 797, Column 212**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 834, Column 230**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 842, Column 190**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 846, Column 226**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#detailed-syntax-reference' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 872, Column 101**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#special-string-values' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 909, Column 106**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/declarative-customization/column-formatting#foreach' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109091351530585-7300%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7UoIqPEl5%2FrCnqHek3IKv3hYm%2FAXXPe8MstzHpR2Zn8%3D&st=2021-09-09T13%3A48%3A15Z&se=2021-10-10T13%3A53%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[26b358d](https://github.com/Jwaegebaert/sp-dev-docs/commits/26b358dba4e44d4042e0f49fe14b5a76af2c5839)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/view-formatting.md](https://github.com/Jwaegebaert/sp-dev-docs/blob/patch-1/docs/declarative-customization/view-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting?branch=pr-en-us-7300) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C9%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109091414198649-7300%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=w%2BoMmDQEa7WmuaMA2mub3182eIadJUsnVDF6svaIFtI%3D&st=2021-09-09T14%3A11%3A16Z&se=2021-10-10T14%3A16%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Jwaegebaert** [comment]
Hey @andrewconnell, Thanks for your suggestions. I completely understand the readability factor, so reverted those changes and added a note, warning users of these line breaks. Also changed the build recommendations regarding the absolute links.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[69c25d6](https://github.com/Jwaegebaert/sp-dev-docs/commits/69c25d67a2df24bb5545d886552487ed32e4a8e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/declarative-customization/view-formatting.md](https://github.com/Jwaegebaert/sp-dev-docs/blob/patch-1/docs/declarative-customization/view-formatting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/view-formatting?branch=pr-en-us-7300) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C14%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202109141037482196-7300%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=RJ8QNNW%2FwYy9l4OJslKEdzuQuRPzqFzpDhmR7vvdFyg%3D&st=2021-09-14T10%3A33%3A41Z&se=2021-10-15T10%3A38%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
@Jwaegebaert Please see the changes I had to make before we merged this. Notice the links to other pages within the site. 

The links were relative links pointing to paths within the GH repo (ie: `blob/master`). We can't do that... when these pages are published, those links won't be valid. Rather, these should just be relative to where they are and where they're pointing in the docs.

**Pull request merged**
