### PR TITLE
Update working-with-lists-and-list-items-with-rest.md

### PR DESCRIPTION
**Pull request by krakp**
Broken link + 2 references to 2013 where the articles just talk about SP in general

| Q                   | A
| ---------------     | ---
| content fix?        | yes
| New article?        | no
| Related issues?     | no

#### What's in this Pull Request?

Broken link + 2 references to 2013 where the articles just talk about SP in general

#### Guidance
*You can delete this section when you are submitting the pull request.* 
* *Please update this PR information accordingly. We'll use this as part of our release notes in monthly communications.*
* *Please target your PR to 'staging' branch.*

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Piotrek, appreciated.

**Comment by krakp** [comment]
Thanks! What's the mechanism (and timing) to get it propagated to https://dev.office.com/sharepoint/docs/apis/rest/working-with-lists-and-list-items-with-rest? That's where I found the issue and it is still broken actually.

**Comment by VesaJuvonen** [comment]
Was just merged to master - should be changed in roughly 3-5 minutes.

**Comment by krakp** [comment]
Indeed - it is fine now -Thanks!

**Pull request merged**
