### PR TITLE
Update on NODE_NO_HTTP2 = 1

### PR DESCRIPTION
**Pull request by StfBauer**
Remark what need to be done to be able to launch local workbench especially for SharePoint 2016 projects.

#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #X, partially #Y, mentioned in #Z

#### What's in this Pull Request?
Additional remark for web part development that targets on-premises environments

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[4cb14cb](https://github.com/StfBauer/sp-dev-docs/pull/3144/commits/4cb14cbfe269fa77bd4a404965bda28b9c8ca412)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[4cb14cb](https://github.com/StfBauer/sp-dev-docs/pull/3144/commits/4cb14cbfe269fa77bd4a404965bda28b9c8ca412)_: 

:clock10: **Incremental building**: average incremental building time is _46 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[4cb14cb](https://github.com/StfBauer/sp-dev-docs/pull/3144/commits/4cb14cbfe269fa77bd4a404965bda28b9c8ca412)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/set-up-your-development-environment.md](https://github.com/StfBauer/sp-dev-docs/blob/patch-6/docs/spfx/set-up-your-development-environment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-development-environment?branch=pr-en-us-3144) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C19%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201812191107090492-3144%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ytrSSMVRhckraFKX2Or8eSaqq9vAHsuERtrspj%2Fjocc%3D&st=2018-12-19T11%3A04%3A04Z&se=2019-01-19T11%3A09%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by andrewconnell** [comment]
@StfBauer Looks like a typo in the submission "I case" => "In case"...

But I'd also provide more detail than just this paragraph... I suspect most people don't understand what's up in this scenario. Maybe just reference a clear closed issue so people can see additional details as to the WHY. I don't think we want to provide too much detail here as it can get confusing.

**Comment by StfBauer** [comment]
Thanx @andrewconnell - In this case, we may refer to #1002 - It has many details and the complete history in it. What do you think?

**Comment by VesaJuvonen** [comment]
Let's not, however, add a reference to the issue itself, as that might freak out people even more... In best case scenario we would have specific on-prem guidance around setting things up and not combine both, but as that does not exist, let's add this note on the article and keep as such for now.

**Pull request merged**
