### PR TITLE
Patch 5

### LINKED ISSUE #6330: The images referenced in build-a-hello-world-extension.md are deleted
This document contains links to images of the application customizer code that are missing:

docs/images/ext-app-vscode-app-base.png
docs/images/ext-app-vscode-manifest.png
docs/images/ext-app-vscode-methods.png
docs/images/ext-app-vscode-serve.png

The images are deleted in the commit 8829271
https://github.com/SharePoint/sp-dev-docs/commit/882927125377daa3dde632b3b49073331f63b435#diff-9f8b34ed85d744cd20009d1fb81b2949

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a9a92b8-9e9e-e314-d549-c8e39b6bc68b
* Version Independent ID: 9a905f1b-4aa8-a72d-efbd-9022bf7e331f
* Content: [Build your first SharePoint Framework Extension (Hello World part 1)](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension)
* Content Source: [docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/extensions/get-started/build-a-hello-world-extension.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

### PR DESCRIPTION
**Pull request by panjkov**
## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #6330 

## What's in this Pull Request?

The document build-a-hello-world-extension.md mentions specific content of the application customizer code that was referred as images, which were deleted in one of the commits. This pull request restores those images and links to the images in the document content thus improving quality of the document (the document implies that images are there although they are deleted).

### CODE REVIEW

**Comment by panjkov** [comment]
Would it make more sense to add real code snippets instead of images for explanations of code in Application Customizer ? cc @andrewconnell

**Comment by andrewconnell** [comment]
Absolutely... code is MUCH preferred as it's (1) easier for people to copy/paste & (2) easier to maintain the docs.

**Comment by andrewconnell** [comment]
Would you mind updating the PR to use snippets instead of images @panjkov ?

**Comment by panjkov** [comment]
Sure, will do that, probably tomorrow.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by panjkov** [comment]
@andrewconnell I updated the document with code snippets. Please review.
I see a small issue, perhaps you know the answer: The comments in the manifest json file are rendering with red background as errors in GitHub edit experience on the web, not sure how it will look like on the docs site.

**Comment by andrewconnell** [comment]
Comments aren't valid in JSON so that's why they are being flagged. Not important in this scenario though.

**Pull request merged**
