### PR TITLE
Managing tenant properties doc improvements

### LINKED ISSUE #4409: Add Get/Set-PnPStorageEntity to documentation (need less permissions)
Using PnP PowerShell you can manage tenant properties without being tenant admin. It's enough to be member in the Owners group of the app catalog site (even when using tenant scope) which can make a huge difference regarding who is able to manage the properties.

Those cmdlets should be mentioned:
```
Connect-PnPOnline
Set-PnPStorageEntity
Get-PnPStorageEntity
```

Related: https://github.com/microsoft/Office365DSC/issues/177

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22ce8c13-ed38-bd19-de74-c8c42c064887
* Version Independent ID: 2eef7358-714e-853c-634e-ee15814b7cdf
* Content: [SharePoint Online tenant properties](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/tenant-properties)
* Content Source: [docs/spfx/tenant-properties.md](https://github.com/SharePoint/sp-dev-docs/blob/master/docs/spfx/tenant-properties.md)
* Product: **sharepoint**
* Technology: **sharepoint-framework**
* GitHub Login: @spdevdocs
* Microsoft Alias: **spdevdocs**

### PR DESCRIPTION
**Pull request by heinrich-ulbricht**
#### Category
- [x] Content fix
- [ ] New article

#### Related issues:
- fixes #4409 

#### What's in this Pull Request?

Added PnP PowerShell as option for managing tenant properties.
Added documentation about no-script sites and site collection app catalogs.

### CODE REVIEW

**Comment by heinrich-ulbricht** [comment]
@andrewconnell I'm not sure if all my links to related documentation are correct. I tried to use server relative URLs. Does this look ok? Is this somehow automatically checked? I currently don't know how to check those links especially when linking to other repos like /powershell. I'm also very open to spelling/grammar corrections.

**Comment by andrewconnell** [comment]
I'll review the links before merging... thanks!

**Comment by heinrich-ulbricht** [comment]
Will do asap.

**Comment by andrewconnell** [comment]
@heinrich-ulbricht bump ;)

**Comment by andrewconnell** [comment]
Nudge... will close this in a few days if it's still left unresolved. Thanks!

**Comment by heinrich-ulbricht** [comment]
I'll have a look in the coming week to hopefully finish this.

**Comment by heinrich-ulbricht** [comment]
Easy one, just some formatting. In my mind there was a nightmarish intricate long manual comparison of two nearly different documents waiting for me. Phew. Hope it's ok now.

**Pull request merged**
