### PR TITLE
Added section on auto-prefixing to current documentation

### PR DESCRIPTION
**Pull request by StfBauer**
| Q                   | A
| ---------------     | ---
| content fix?        | yes
| New article?        | no
| Related issues?     | no

#### What's in this Pull Request?
New section on concerning CSS vendor prefixes handling in SPFx was added.

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/css-recommendations.md](https://github.com/StfBauer/sp-dev-docs/blob/master/docs/spfx/css-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C20%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711201855291385-1063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=yHMIBaJPbIPdKO4oCL4fWv8o7D81GzR9o8rlPHxT84Y%3D&st=2017-11-20T18%3A51%3A34Z&se=2017-12-21T18%3A56%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/css-recommendations.md](https://github.com/StfBauer/sp-dev-docs/blob/master/docs/spfx/css-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711280847052332-1063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rXahDY5zMfxT2Y7l9K6VSPx7Jbn6LloREmMxc94opmI%3D&st=2017-11-28T08%3A42%3A59Z&se=2017-12-29T08%3A47%3A59Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx Stefan, appreciated. Really good stuff to get included around the prefixing.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/css-recommendations.md](https://github.com/StfBauer/sp-dev-docs/blob/master/docs/spfx/css-recommendations.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C11%5C28%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201711280847392380-1063%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=JLlHFASabQJ6Kw%2B8XBqg6cJT2slZLqTyjUcBrUOku2Q%3D&st=2017-11-28T08%3A44%3A23Z&se=2017-12-29T08%3A49%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
