### PR TITLE
Edit complete

### PR DESCRIPTION
**Pull request by Linda-Editor**
| Q                   | A
| ---------------     | ---
| content fix?        | yes
| New article?        | no

#### What's in this Pull Request?

Added numbered lists, corrected punctuation and grammar, changed some passive to active.

### CODE REVIEW

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/Linda-Editor/sp-dev-docs/blob/patch-3/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C17%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710172010349252-949%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xZCEDsGjOBA72wPPYJC%2FpX86uiWi5LF19U%2FS0E04iEU%3D&st=2017-10-17T20%3A09%3A00Z&se=2017-11-17T20%3A14%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/Linda-Editor/sp-dev-docs/blob/patch-3/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C17%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710172049081732-949%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rHWbDwq%2Fngk9UA1VFOJ8VuJ8%2BufpJ5qtIsa5TMnUBH8%3D&st=2017-10-17T20%3A45%3A15Z&se=2017-11-17T20%3A50%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/Linda-Editor/sp-dev-docs/blob/patch-3/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C10%5C17%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201710172159342112-949%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=upg3buAhBG%2FuksruJ88Tv4C%2F94A9iAa3ypNslXWK6E0%3D&st=2017-10-17T21%3A55%3A48Z&se=2017-11-17T22%3A00%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx Linda, appreciated.

**Pull request merged**
