### PR TITLE
[Bulk] Validation: fix description and update date

### PR DESCRIPTION
**Pull request by reemsabaw1**
## Category

- [x] Content fix
- [ ] New article

## Related issues

**Global effort to fix build validation errors**

## What's in this Pull Request?

Description-missing fix.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[abda508](https://github.com/reemsabaw1/sp-dev-docs/commits/abda50832251d5062acd371a9978be2fe1bca85b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8124) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-a7c5dc1f)

<a id="0842ac3c5a7d8f4a0a8b70cb62539114-a7c5dc1f"></a>
### [docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206101239233964-8124/BuildReport?accessString=8580f72533d8f2f2474e0743d0e84a129c7bb1d210349c1896eb309291004d74).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by reemsabaw1** [comment]
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

**Review by andrewconnell — APPROVED** [review]

**Comment by andrewconnell** [comment]
Please resolve the merge conflicts and resubmit.

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[160a805](https://github.com/reemsabaw1/sp-dev-docs/commits/160a805ecaaea7c769a9d983dcf1c607e5425eda)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd1/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8124) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-0856aa55)

<a id="0842ac3c5a7d8f4a0a8b70cb62539114-0856aa55"></a>
### [docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd1/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206231546553891-8124/BuildReport?accessString=91f590b71f0343044bc50332becef06c64e9db28c4db282749c3b8e94e5e8322).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by andrewconnell — APPROVED** [review]

**Pull request merged**
