### PR TITLE
Link is obsolete and no longer relevant 

### LINKED ISSUE #2057: [LOC] Invalid link in a 2 articles
#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

**Current:** link "SharePoint: Perform basic data access operations on files and folders by using REST" (http://code.msdn.microsoft.com/SharePoint-Perform-ab9c4ae5) redirect to 404 error page.
Broken link was found in 2 articles:
- working-with-folders-and-files-with-rest.md (https://github.com/SharePoint/sp-dev-docs/blob/live/docs/sp-add-ins/working-with-folders-and-files-with-rest.md)
- complete-basic-operations-using-sharepoint-rest-endpoints.md (https://github.com/SharePoint/sp-dev-docs/blob/live/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md)

**Expected:** link should be fixed or removed from the articles

**Repro steps:**
1. go to https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints and https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest
2. check "SharePoint: Perform basic data access operations on files and folders by using REST" in _See also_ section
3. click the link --> 404 error page

sp_addin

### PR DESCRIPTION
**Pull request by cakriwut**
…com/sharepoint-2013-perform-ab9c4ae5)

#### Category
- [x] Content fix
- [ ] New article
- Related issues: fixes #2057

#### What's in this Pull Request?

> The link [Perform basic data operations on files and folders using REST](https://code.msdn.microsoft.com/sharepoint-2013-perform-ab9c4ae5) is obsolete.

#### Guidance

> Remove circular references.

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[1d9cf50](https://github.com/cakriwut/sp-dev-docs/pull/3255/commits/1d9cf501a73c131a783d919cb36a8d9757386392)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[1d9cf50](https://github.com/cakriwut/sp-dev-docs/pull/3255/commits/1d9cf501a73c131a783d919cb36a8d9757386392)_: 

:clock10: **Incremental building**: average incremental building time is _44 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[1d9cf50](https://github.com/cakriwut/sp-dev-docs/pull/3255/commits/1d9cf501a73c131a783d919cb36a8d9757386392)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2057/docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints?branch=pr-en-us-3255) |
[docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/cakriwut/sp-dev-docs/blob/patching-issue-2057/docs/sp-add-ins/working-with-folders-and-files-with-rest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest?branch=pr-en-us-3255) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C13%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901131107548090-3255%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=j0LY1UVHuBRiZRFLLj1ebvB07qdOIuEzFPKPYR3eVeo%3D&st=2019-01-13T11%3A04%3A43Z&se=2019-02-13T11%3A09%3A43Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by andrewconnell** [comment]
@cakriwut It looks like this PR, along with the other ones, are all getting merged on top of each other... is that what you're doing? I haven't reviewed, but this is going to cause issues when merging as if there are conflicts after the first merge, it slows the process down and we'll have to push back, asking you to break them up anyway.

A good practice is to keep each PR's content separate from each other's PR. Please don't keep adding to the PR after you've submitted it... you can always open a new PR to submit new content. More atomic PR's

**Comment by cakriwut** [comment]
Thanks @andrewconnell , actually after I submit PR there is new update in __master__ that touches all files (#3249). So I rebase my patching-* branch based on latest master.
Otherwise, if it is too risky - I can submit new PR  based on (#3249)

**Comment by VesaJuvonen** [comment]
thx @cakriwut, appreciated.

**Pull request merged**
