### PR TITLE
Update integrate-with-teams-introduction.md

### PR DESCRIPTION
**Pull request by panjkov**
Clarified some sentences, fixed few typos

#### Category
- [x] Content fix
- [ ] New article

#### What's in this Pull Request?

Clarified sentences, fixed few typos

### CODE REVIEW

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[c859b12](https://github.com/panjkov/sp-dev-docs/pull/3222/commits/c859b129313623b75f1ded918b81210cb694d112)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[c859b12](https://github.com/panjkov/sp-dev-docs/pull/3222/commits/c859b129313623b75f1ded918b81210cb694d112)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[c859b12](https://github.com/panjkov/sp-dev-docs/pull/3222/commits/c859b129313623b75f1ded918b81210cb694d112)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/integrate-with-teams-introduction.md](https://github.com/panjkov/sp-dev-docs/blob/patch-6/docs/spfx/integrate-with-teams-introduction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction?branch=pr-en-us-3222) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901082134510508-3222%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=4nAc0o5Xi3W%2BGSzEJFpOSC6LtIBJk9gP7DB5nhNpiYA%3D&st=2019-01-08T21%3A31%3A34Z&se=2019-02-08T21%3A36%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[2132e8f](https://github.com/panjkov/sp-dev-docs/pull/3222/commits/2132e8fea84768219e612b21d3e1a67ad2ab8895)_: 

:clock10: **Preparing**: average preparing time is _1 min(s) 7 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[2132e8f](https://github.com/panjkov/sp-dev-docs/pull/3222/commits/2132e8fea84768219e612b21d3e1a67ad2ab8895)_: 

:clock10: **Incremental building**: average incremental building time is _45 sec(s)_

**Comment by spdevdocs** [comment]
OPS Build status updates of commit _[2132e8f](https://github.com/panjkov/sp-dev-docs/pull/3222/commits/2132e8fea84768219e612b21d3e1a67ad2ab8895)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/integrate-with-teams-introduction.md](https://github.com/panjkov/sp-dev-docs/blob/patch-6/docs/spfx/integrate-with-teams-introduction.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/integrate-with-teams-introduction?branch=pr-en-us-3222) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C1%5C8%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C201901082142454750-3222%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=eTePA638awZZaq5FEPcRBWBVNJ2rnBu66chXZ4BinEQ%3D&st=2019-01-08T21%3A39%3A32Z&se=2019-02-08T21%3A44%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by VesaJuvonen** [comment]
thx Dragan, appreciated.

**Pull request merged**
