### PR TITLE
Update article "Use an Office 365 SharePoint site to authorize provider-hosted add-ins on an on-premises SharePoint site"

### PR DESCRIPTION
**Pull request by Yvand**
#### Category
- [X] Content fix
- [ ] New article

#### What's in this Pull Request?

I propose to update [this article](https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on) with the following changes:

- Remove the replacement of the SharePoint STS certificate, unnecessary
- Remove unnecessary prerequisites
- Add a step to install required NuGet package MSOnlineExt
- Update the title from "Use an Office 365 SharePoint site to authorize provider-hosted add-ins on an on-premises SharePoint site" to "Use ACS to authorize low-trust provider-hosted add-ins on an on-premises SharePoint site", which I think is more relevant
- Other minor updates to the content

I tested and validated all my changes on 2 separate environments, both provisioned using [this template](https://azure.microsoft.com/en-us/resources/templates/sharepoint-adfs/):

- a SharePoint 2013 farm (Windows Server 2012 R2)
- a SharePoint 2019 farm (Windows Server 2016)

### CODE REVIEW

**Comment by Yvand** [comment]
This PR is 2 weeks old and I got no feedback, is this getting some attention?

**Comment by Yvand** [comment]
I submitted this PR 1 month ago, can someone look at this?

**Comment by VesaJuvonen** [comment]
thx  @Yvand, appreciated. Sorry for the massive delay on getting things processed.

**Comment by Yvand** [comment]
Awesome, thanks @VesaJuvonen !

**Comment by Yvand** [comment]
@VesaJuvonen something went wrong with the merge: some of the changes were lost.
I think it happened when resolving the conflict with the previous PR.
I'll check this in detail and submit a new PR

**Pull request merged**
