### PR TITLE
Create onenote-migration-service

### PR DESCRIPTION
**Pull request by JoanneHendrickson**
NEW ARTICLE

article for new onenote conversion service on SPO side

### CODE REVIEW

**Comment by JoanneHendrickson** [comment]
onenote-migration-flow

**Comment by VesaJuvonen** [comment]
thx @JoanneHendrickson, adding it to the TOC as well.

**Comment by VesaJuvonen** [comment]
and moving it to the right location as it definitely should not be in the root of the GitHub repository... but taking care of this.

**Comment by VesaJuvonen** [comment]
and renaming the file with .md extension based on doc requirements.

**Comment by VesaJuvonen** [comment]
Doc also had a reference to onenote-migration-flow.png image, which was not provided with the pull request, so removed the section from the doc. Not quite sure what's the objective here as didn't see any communications around this. Happy to help to get things fixed if needed.

Removed following section until image is found.
--

### Example

The following example shows SPMT using the SPO OneNote converting service, which is running in SPO background.  

OneNote migration process

**Pull request merged**
