### PR TITLE
Adds information about using MGT in SPFx

### PR DESCRIPTION
**Pull request by waldekmastykarz**
## Category

- [ ] Content fix
- [x] New article

## Related issues

N/A

## What's in this Pull Request?

- new article explaining what is MGT and why you'd use it in SPFx
- tutorial showing how to build a web part that uses MGT

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[5c2f5ad](https://github.com/waldekmastykarz/sp-dev-docs/commits/5c2f5ada1995496fb9e8d3f535a3638be695c2da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit?branch=pr-en-us-7062) | [Details](#user-content-d0f14257f076519a3baa29b196c772a6-75339510)
[docs/spfx/use-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/use-microsoft-graph-toolkit.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-microsoft-graph-toolkit?branch=pr-en-us-7062) | [Details](#user-content-a460844e96d2ac7a580f676eba61269a-75339510)
[docs/toc.yml](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-microsoft-graph-toolkit?branch=pr-en-us-7062) |

<a id="d0f14257f076519a3baa29b196c772a6-75339510"></a>
### [docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

<a id="a460844e96d2ac7a580f676eba61269a-75339510"></a>
### [docs/spfx/use-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/use-microsoft-graph-toolkit.md)
 - **Line 17, Column 189**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/components/agenda?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 58, Column 422**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/overview?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 62, Column 95**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 272**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka#react' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 77, Column 385**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 85, Column 290**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/api-access?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 89, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/overview?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 90, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106011445487793-7062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BiilVG6YMbm%2FbCzgHrnOHICfB3uRdVN7AvWxGPB13DI%3D&st=2021-06-01T14%3A42%3A02Z&se=2021-07-02T14%3A47%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[34f701c](https://github.com/waldekmastykarz/sp-dev-docs/commits/34f701cc1ea070e3966429bfd8d081aee003400f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/use-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/use-microsoft-graph-toolkit.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-microsoft-graph-toolkit?branch=pr-en-us-7062) | [Details](#user-content-a460844e96d2ac7a580f676eba61269a-6a22c95f)
[docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit?branch=pr-en-us-7062) |
[docs/toc.yml](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-microsoft-graph-toolkit?branch=pr-en-us-7062) |

<a id="a460844e96d2ac7a580f676eba61269a-6a22c95f"></a>
### [docs/spfx/use-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/use-microsoft-graph-toolkit.md)
 - **Line 17, Column 189**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/components/agenda?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 58, Column 422**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/overview?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 62, Column 95**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 65, Column 272**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka#react' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 77, Column 385**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 85, Column 290**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/api-access?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 89, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/overview?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 90, Column 3**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/graph/toolkit/get-started/mgt-spfx?WT.mc_id=m365-29707-wmastyka' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106011448077708-7062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c9%2FWIp96tnc%2F594TzXyQg8dxayrypWtyzv8IngxJPRQ%3D&st=2021-06-01T14%3A44%3A18Z&se=2021-07-02T14%3A49%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by VesaJuvonen** [comment]
Docs Build status updates of commit _[2f09775](https://github.com/waldekmastykarz/sp-dev-docs/commits/2f09775cb28381494cf733b172bf96f3051a8498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/use-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/use-microsoft-graph-toolkit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-microsoft-graph-toolkit?branch=pr-en-us-7062) |
[docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit?branch=pr-en-us-7062) |
[docs/toc.yml](https://github.com/waldekmastykarz/sp-dev-docs/blob/mgt/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-microsoft-graph-toolkit?branch=pr-en-us-7062) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106011449197036-7062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IW7nQnabBXQdZA9mzHi1yZAJJRFaUHY4U5B0OK0eut4%3D&st=2021-06-01T14%3A45%3A31Z&se=2021-07-02T14%3A50%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by waldekmastykarz** [comment]
Hey @andrewconnell, is there anything that I should adjust on this PR before we can merge it?

**Comment by andrewconnell** [comment]
Not from my POV. It's not merged because I can't merge new content. That's why @VesaJuvonen is assigned to this one.

**Pull request merged**
